-- ============================================================================
-- ANALYSE INSERTION BR_DATA - Pourquoi 22.36 passe et 2817 non ?
-- ============================================================================
-- Date: 07/02/2025
-- Objectif: Identifier les conditions d'insertion qui excluent la transaction 2817
--
-- TRANSACTIONS À COMPARER:
-- ------------------------
-- ✅ INSEREE    : Montant 22.36  | NumeroClient=00838038 | SettlementMode=VO | RIB=30004021180001020705492
-- ❌ NON INSEREE: Montant 2817   | NumeroClient=90141615 | SettlementMode=VO | RIB=30004021180001611183292
-- ============================================================================

PROMPT ============================================================================
PROMPT 1. VERIFICATION DES COMPTES BANCAIRES
PROMPT ============================================================================

SELECT
    'Compte 22.36' AS Transaction,
    RCB.ID_COMPTE_BANCAIRE,
    RCB.IDENTIFICATION,
    RCB.BANKCODE,
    RCB.BRANCHCODE,
    RCB.NOM
FROM TA_RN_COMPTE_BANCAIRE RCB
WHERE RCB.IDENTIFICATION = '00010207054'
UNION ALL
SELECT
    'Compte 2817' AS Transaction,
    RCB.ID_COMPTE_BANCAIRE,
    RCB.IDENTIFICATION,
    RCB.BANKCODE,
    RCB.BRANCHCODE,
    RCB.NOM
FROM TA_RN_COMPTE_BANCAIRE RCB
WHERE RCB.IDENTIFICATION = '00016111832';

PROMPT
PROMPT ============================================================================
PROMPT 2. VERIFICATION PARAMETRAGE GESTION (TA_RN_GESTION_JC)
PROMPT ============================================================================
PROMPT Cette table contient les couples PRODUIT/MODE_REGLEMENT autorises

-- Recherche pour NumeroClient 00838038 (22.36)
SELECT
    '22.36 (00838038)' AS Transaction,
    RGJ.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RCA.NOM AS NOM_COMPTE_ACCURATE,
    RCA.FLAG_ACTIF AS COMPTE_ACTIF,
    RGJ.ID_PRODUIT,
    RP.CODE_PRODUIT,
    RP.LIBELLE AS LIBELLE_PRODUIT,
    RGJ.ID_MODE_REGLEMENT,
    RMR.CODE_MODE_REGLEMENT,
    RMR.LIBELLE AS LIBELLE_MODE_REGLEMENT
FROM TA_RN_GESTION_JC RGJ
    INNER JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RGJ.ID_COMPTE_ACCURATE
    INNER JOIN TA_RN_PRODUIT RP ON RP.ID_PRODUIT = RGJ.ID_PRODUIT
    INNER JOIN TA_RN_MODE_REGLEMENT RMR ON RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
WHERE (RP.CODE_PRODUIT = 'ALL' OR RP.CODE_PRODUIT = '00838038')
  AND (RMR.CODE_MODE_REGLEMENT = 'ALL' OR RMR.CODE_MODE_REGLEMENT = 'VO')
ORDER BY RCA.FLAG_ACTIF DESC;

PROMPT
PROMPT Recherche pour NumeroClient 90141615 (2817)...

SELECT
    '2817 (90141615)' AS Transaction,
    RGJ.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RCA.NOM AS NOM_COMPTE_ACCURATE,
    RCA.FLAG_ACTIF AS COMPTE_ACTIF,
    RGJ.ID_PRODUIT,
    RP.CODE_PRODUIT,
    RP.LIBELLE AS LIBELLE_PRODUIT,
    RGJ.ID_MODE_REGLEMENT,
    RMR.CODE_MODE_REGLEMENT,
    RMR.LIBELLE AS LIBELLE_MODE_REGLEMENT
FROM TA_RN_GESTION_JC RGJ
    INNER JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RGJ.ID_COMPTE_ACCURATE
    INNER JOIN TA_RN_PRODUIT RP ON RP.ID_PRODUIT = RGJ.ID_PRODUIT
    INNER JOIN TA_RN_MODE_REGLEMENT RMR ON RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
WHERE (RP.CODE_PRODUIT = 'ALL' OR RP.CODE_PRODUIT = '90141615')
  AND (RMR.CODE_MODE_REGLEMENT = 'ALL' OR RMR.CODE_MODE_REGLEMENT = 'VO')
ORDER BY RCA.FLAG_ACTIF DESC;

PROMPT
PROMPT ============================================================================
PROMPT 3. VERIFICATION LIEN COMPTE_BANCAIRE <-> COMPTE_ACCURATE
PROMPT ============================================================================

-- Pour le compte 00010207054 (22.36)
SELECT
    '22.36 (RIB 00010207054)' AS Transaction,
    RCB.ID_COMPTE_BANCAIRE,
    RCB.IDENTIFICATION,
    RCB.NOM AS NOM_COMPTE_BANCAIRE,
    RPB.ID_PERIMETRE_BANQUE,
    RPB.FLAG_ACTIF AS PERIMETRE_BANQUE_ACTIF,
    RBA.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RCA.NOM AS NOM_COMPTE_ACCURATE,
    RCA.FLAG_ACTIF AS COMPTE_ACCURATE_ACTIF
FROM TA_RN_COMPTE_BANCAIRE RCB
    LEFT JOIN TA_RN_PERIMETRE_BANQUE RPB ON RPB.ID_COMPTE_BANCAIRE = RCB.ID_COMPTE_BANCAIRE
    LEFT JOIN TA_RN_BANQUE_ACCURATE RBA ON RBA.ID_PERIMETRE_BANQUE = RPB.ID_PERIMETRE_BANQUE
    LEFT JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RBA.ID_COMPTE_ACCURATE
WHERE RCB.IDENTIFICATION = '00010207054';

PROMPT
-- Pour le compte 00016111832 (2817)
SELECT
    '2817 (RIB 00016111832)' AS Transaction,
    RCB.ID_COMPTE_BANCAIRE,
    RCB.IDENTIFICATION,
    RCB.NOM AS NOM_COMPTE_BANCAIRE,
    RPB.ID_PERIMETRE_BANQUE,
    RPB.FLAG_ACTIF AS PERIMETRE_BANQUE_ACTIF,
    RBA.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RCA.NOM AS NOM_COMPTE_ACCURATE,
    RCA.FLAG_ACTIF AS COMPTE_ACCURATE_ACTIF
FROM TA_RN_COMPTE_BANCAIRE RCB
    LEFT JOIN TA_RN_PERIMETRE_BANQUE RPB ON RPB.ID_COMPTE_BANCAIRE = RCB.ID_COMPTE_BANCAIRE
    LEFT JOIN TA_RN_BANQUE_ACCURATE RBA ON RBA.ID_PERIMETRE_BANQUE = RPB.ID_PERIMETRE_BANQUE
    LEFT JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RBA.ID_COMPTE_ACCURATE
WHERE RCB.IDENTIFICATION = '00016111832';

PROMPT
PROMPT ============================================================================
PROMPT 4. TEST DE LA CONDITION D'INSERTION (SIMULATION)
PROMPT ============================================================================
PROMPT Condition du script RNADGENJUCGES01.sql ligne 895-900:
PROMPT EXISTS (SELECT 1 FROM TA_RN_MODE_REGLEMENT, TA_RN_PRODUIT, TA_RN_GESTION_JC
PROMPT     WHERE TA_RN_MODE_REGLEMENT.ID_MODE_REGLEMENT = TA_RN_GESTION_JC.ID_MODE_REGLEMENT
PROMPT     AND TA_RN_PRODUIT.ID_PRODUIT = TA_RN_GESTION_JC.ID_PRODUIT
PROMPT     AND (TA_RN_MODE_REGLEMENT.CODE_MODE_REGLEMENT='ALL' OR CODE='VO')
PROMPT     AND (TA_RN_PRODUIT.CODE_PRODUIT='ALL' OR CODE='00838038' ou '90141615'))

-- Test pour 22.36 (NumeroClient=00838038, SettlementMode=VO)
SELECT
    '22.36 - TEST CONDITION' AS Test,
    CASE
        WHEN COUNT(*) > 0 THEN 'CONDITION VALIDE - INSERTION OK'
        ELSE 'CONDITION NON VALIDE - PAS D INSERTION'
    END AS Resultat,
    COUNT(*) AS Nb_Matches
FROM TA_RN_MODE_REGLEMENT RMR,
     TA_RN_PRODUIT RP,
     TA_RN_GESTION_JC RGJ
WHERE RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
  AND RP.ID_PRODUIT = RGJ.ID_PRODUIT
  AND (RMR.CODE_MODE_REGLEMENT = 'ALL' OR RMR.CODE_MODE_REGLEMENT = 'VO')
  AND (RP.CODE_PRODUIT = 'ALL' OR RP.CODE_PRODUIT = '00838038');

PROMPT
-- Test pour 2817 (NumeroClient=90141615, SettlementMode=VO)
SELECT
    '2817 - TEST CONDITION' AS Test,
    CASE
        WHEN COUNT(*) > 0 THEN 'CONDITION VALIDE - INSERTION OK'
        ELSE 'CONDITION NON VALIDE - PAS D INSERTION'
    END AS Resultat,
    COUNT(*) AS Nb_Matches
FROM TA_RN_MODE_REGLEMENT RMR,
     TA_RN_PRODUIT RP,
     TA_RN_GESTION_JC RGJ
WHERE RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
  AND RP.ID_PRODUIT = RGJ.ID_PRODUIT
  AND (RMR.CODE_MODE_REGLEMENT = 'ALL' OR RMR.CODE_MODE_REGLEMENT = 'VO')
  AND (RP.CODE_PRODUIT = 'ALL' OR RP.CODE_PRODUIT = '90141615');

PROMPT
PROMPT ============================================================================
PROMPT 5. VERIFICATION TABLE IMPORT (TA_RN_IMPORT_GESTION_JC)
PROMPT ============================================================================
PROMPT Les deux transactions sont-elles bien importees dans la table temporaire ?

SELECT
    'Import 22.36' AS Transaction,
    NUMEROCLIENT,
    SETTLEMENTMODE,
    OPERATIONNETAMOUNT,
    BENEFICIARYNAME,
    NOMCLIENT,
    COMMENTAIRE,
    IDENTIFICATIONRIB,
    BANKCODE,
    BRANCHCODE,
    RIBCHECKDIGIT
FROM TA_RN_IMPORT_GESTION_JC
WHERE OPERATIONNETAMOUNT = '22.36'
  AND ROWNUM <= 5;

PROMPT
SELECT
    'Import 2817' AS Transaction,
    NUMEROCLIENT,
    SETTLEMENTMODE,
    OPERATIONNETAMOUNT,
    BENEFICIARYNAME,
    NOMCLIENT,
    COMMENTAIRE,
    IDENTIFICATIONRIB,
    BANKCODE,
    BRANCHCODE,
    RIBCHECKDIGIT
FROM TA_RN_IMPORT_GESTION_JC
WHERE OPERATIONNETAMOUNT = '2817'
  AND ROWNUM <= 5;

PROMPT
PROMPT ============================================================================
PROMPT 6. LISTE DES PRODUITS PARAMETRES
PROMPT ============================================================================

SELECT
    ID_PRODUIT,
    CODE_PRODUIT,
    LIBELLE
FROM TA_RN_PRODUIT
WHERE CODE_PRODUIT IN ('ALL', '00838038', '90141615')
   OR CODE_PRODUIT LIKE '%838%'
   OR CODE_PRODUIT LIKE '%141%'
ORDER BY CODE_PRODUIT;

PROMPT
PROMPT ============================================================================
PROMPT 7. RESUME DIAGNOSTIC
PROMPT ============================================================================
PROMPT Pour que la transaction soit inseree dans BR_DATA, il faut:
PROMPT 1. Compte bancaire existe (IDENTIFICATION dans TA_RN_COMPTE_BANCAIRE)
PROMPT 2. Lien compte bancaire -> perimetre banque -> compte accurate existe
PROMPT 3. Perimetre banque ACTIF (FLAG_ACTIF = 1 dans TA_RN_PERIMETRE_BANQUE)
PROMPT 4. Compte accurate ACTIF (FLAG_ACTIF = 1 dans TA_RN_COMPTE_ACCURATE)
PROMPT 5. Couple PRODUIT/MODE_REGLEMENT parametre dans TA_RN_GESTION_JC
PROMPT    - PRODUIT = NumeroClient (90141615) OU 'ALL'
PROMPT    - MODE_REGLEMENT = SettlementMode (VO) OU 'ALL'
PROMPT 6. Transaction presente dans TA_RN_IMPORT_GESTION_JC
PROMPT
PROMPT Verifiez les resultats ci-dessus pour identifier le point bloquant !
PROMPT ============================================================================
