-- ============================================================
-- SCRIPT DE COMPARAISON : ORIGINAL vs OPTIMISE
-- Ticket : DTC-670
-- Date : 19/02/2026
-- Objectif : Valider qu'il n'y a AUCUNE regression
-- ============================================================
-- Execution : sqlplus user/pwd@instance @COMPARAISON_ORIGINAL_VS_OPTIMISE.sql
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200
SET PAGESIZE 1000
SET TIMING ON
SET ECHO OFF
SET FEEDBACK ON

PROMPT ============================================================
PROMPT COMPARAISON REQUETE ORIGINAL vs OPTIMISE - DTC-670
PROMPT Date execution :
SELECT TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS') AS DATE_EXECUTION FROM DUAL;
PROMPT ============================================================

-- ============================================================
-- ETAPE 1 : COMPTAGE DES LIGNES
-- ============================================================
PROMPT
PROMPT [ETAPE 1/4] COMPTAGE DES LIGNES
PROMPT ============================================================

WITH
-- ============================================================
-- REQUETE ORIGINALE (copie exacte)
-- ============================================================
requete_originale AS (
    -- Requete OUTSTANDING (suspens en cours)
    SELECT /*+  optimizer_features_enable('10.2.0.4') */ DISTINCT
        '28/02/2026' AS DATE_ARRETE,
        (SELECT DECODE(RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Controle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison')
         FROM BS_ACCTS BS_ACCTS2
         WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
        (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
        (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
        BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
        BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
        BS_ACCTS.ACCT_CURRENCY AS DEVISE,
        TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
        BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
        DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
            DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'),
            'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')) AS SENS_ATTENDU,
        DECODE(BRR_TRANSACTIONS.SIDE,'STATEMENT', 'B','CASHBOOK', 'C') AS COTE_SUSPENS,
        TO_DATE('28/02/2026', 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
        MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
        (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
         WHERE MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
           AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
            'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
            'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
        BA_CPME.METHODE AS METHODE_PROVISION,
        (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
         WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID)
           AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
           AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
        0 AS MONTANT_PROVISION,
        BRR_TRANSACTIONS.STATE AS STATUT,
        NULL AS DATE_APUREMENT,
        NULL AS DC_MAX,
        SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
        BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
        BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
        DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
            NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
            DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') AS SENS_DELTA,
        '' AS NUMERO_FICHE,
        '' AS DERNIER_STATUT,
        BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
        CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
            WHEN TO_DATE('01/01/1980','DD/MM/RRRR') THEN NULL
            ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
        END AS ANNOTE_LE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND BRR_TRANSACTIONS.STATE = 'OUTSTANDING'

    UNION

    -- Requete RECONCILED (suspens rapproches)
    SELECT /*+  optimizer_features_enable('10.2.0.4') */ DISTINCT
        '28/02/2026' AS DATE_ARRETE,
        (SELECT DECODE(RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Controle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison')
         FROM BS_ACCTS BS_ACCTS2
         WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
        (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
        (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
        BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
        BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
        BS_ACCTS.ACCT_CURRENCY AS DEVISE,
        TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
        BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
        DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
            DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'),
            'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')) AS SENS_ATTENDU,
        DECODE(BRR_TRANSACTIONS.SIDE,'STATEMENT', 'B','CASHBOOK', 'C') AS COTE_SUSPENS,
        TO_DATE('28/02/2026', 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
        MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
        (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
         WHERE MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
           AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
            'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
            'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
        BA_CPME.METHODE AS METHODE_PROVISION,
        (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
         WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID)
           AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
           AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
        0 AS MONTANT_PROVISION,
        BRR_TRANSACTIONS.STATE AS STATUT,
        TO_DATE(BRR_TRANSACTIONS.UPDATE_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,
        (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) AS DC_MAX,
        SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
        BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
        BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
        DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
            NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
            DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') AS SENS_DELTA,
        '' AS NUMERO_FICHE,
        '' AS DERNIER_STATUT,
        BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
        CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
            WHEN TO_DATE('01/01/1980','DD/MM/RRRR') THEN NULL
            ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
        END AS ANNOTE_LE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND BRR_TRANSACTIONS.STATE = 'RECONCILED'
)
SELECT 'ORIGINAL' AS VERSION, COUNT(*) AS NB_LIGNES FROM requete_originale;

PROMPT
PROMPT Comptage OPTIMISE en cours...

WITH
-- ============================================================
-- REQUETE OPTIMISEE (version DTC-670)
-- ============================================================
params AS (
    SELECT TO_DATE('28/02/2026', 'DD/MM/RRRR') AS date_arrete FROM DUAL
),
compte_hierarchie AS (
    SELECT
        H.ACCOUNT_ID,
        H.LEVEL_02_ACCOUNT_ID,
        H.LEVEL_03_ACCOUNT_ID,
        B2.ACCT_NUM AS SERVICE,
        B3.ACCT_NUM AS TYPE_CODE,
        RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE,
        DECODE(RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Controle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison') AS TYPE_RAPRO
    FROM BRR_ACCOUNT_HIERARCHIES H
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
),
transactions_base AS (
    SELECT /*+ USE_HASH(T A H) */
        T.RECORD_ID,
        T.ACCOUNT_ID,
        T.TRANSACTION_DATE,
        T.NARRATIVE,
        T.AMOUNT,
        T.PAYMENT_OR_RECEIPT,
        T.SIDE,
        T.NUMERIC_TWO,
        T.FLAG_C,
        T.STATE,
        T.UPDATE_TIME,
        T.RECONCILIATION_REFERENCE,
        T.CHARACTER_SIXTEEN,
        T.LAST_NOTE_TEXT,
        T.DATE_LAST_NOTE_ADDED,
        T.PAYMENT_OR_RECEIPT || T.SIDE AS PAY_SIDE,
        P.date_arrete,
        P.date_arrete - T.TRANSACTION_DATE AS ANCIENNETE_J,
        MONTHS_BETWEEN(P.date_arrete, T.TRANSACTION_DATE) AS ANCIENNETE_M
    FROM BRR_TRANSACTIONS T
    CROSS JOIN params P
    WHERE T.TRANSACTION_DATE <= P.date_arrete
      AND T.STATE IN ('OUTSTANDING', 'RECONCILED')
),
dc_max_calc AS (
    SELECT
        RECONCILIATION_REFERENCE,
        ACCOUNT_ID,
        MAX(TRANSACTION_DATE) AS DC_MAX
    FROM BRR_TRANSACTIONS
    WHERE STATE = 'RECONCILED'
    GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
),
donnees_completes AS (
    SELECT
        '28/02/2026' AS DATE_ARRETE,
        CH.TYPE_RAPRO,
        CH.SERVICE,
        (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
        CM.COMPTE_BANCAIRE,
        A.ACCT_NAME AS LIBELLE_COMPTE,
        A.ACCT_CURRENCY AS DEVISE,
        TO_CHAR(T.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
        T.NARRATIVE AS LIBELLE_SUSPENS,
        DECODE(T.PAY_SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT) AS DEBIT,
        DECODE(T.PAY_SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT) AS CREDIT,
        DECODE(T.NUMERIC_TWO, 0,
            DECODE(T.PAY_SIDE, 'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC', 'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
            'A' || T.FLAG_C || DECODE(T.PAY_SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')
        ) AS SENS_ATTENDU,
        DECODE(T.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
        T.ANCIENNETE_J,
        T.ANCIENNETE_M,
        BACA.LIBELLE_ANCIENNETE AS BORNE_ANCIENNETE,
        CASE WHEN T.PAY_SIDE IN ('PAYMENTSTATEMENT', 'RECEIPTCASHBOOK') THEN PIMO.LIBELLE_PILIER END AS PILIER_MONTANT_DEBIT,
        CASE WHEN T.PAY_SIDE IN ('RECEIPTSTATEMENT', 'PAYMENTCASHBOOK') THEN PIMO.LIBELLE_PILIER END AS PILIER_MONTANT_CREDIT,
        CM.METHODE AS METHODE_PROVISION,
        MEPR.TAUX,
        0 AS MONTANT_PROVISION,
        T.STATE AS STATUT,
        CASE WHEN T.STATE = 'RECONCILED' THEN TO_DATE(T.UPDATE_TIME, 'DD/MM/RRRR') END AS DATE_APUREMENT,
        CASE WHEN T.STATE = 'RECONCILED' THEN DCM.DC_MAX END AS DC_MAX,
        SUBSTR(T.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
        T.LAST_NOTE_TEXT AS COMMENTAIRE,
        T.NUMERIC_TWO AS NETTING,
        COALESCE(
            DECODE(T.PAY_SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT),
            DECODE(T.PAY_SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT)
        ) AS DELTA,
        DECODE(T.PAY_SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
        '' AS NUMERO_FICHE,
        '' AS DERNIER_STATUT,
        T.RECORD_ID AS ID_ECRITURE,
        CASE T.DATE_LAST_NOTE_ADDED
            WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
            ELSE TO_CHAR(T.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
        END AS ANNOTE_LE,
        T.date_arrete AS P_DATE_ARRETE
    FROM transactions_base T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN BA_CATEG_ANCIENNETE BACA
        ON T.ANCIENNETE_M >= BACA.BORNE_INF
        AND T.ANCIENNETE_M < BACA.BORNE_SUP
    LEFT JOIN BA_PILIERS_MONTANTS PIMO
        ON T.AMOUNT >= PIMO.BORNE_INF
        AND T.AMOUNT < PIMO.BORNE_SUP
    LEFT JOIN BA_METHODE_PROVISION MEPR
        ON MEPR.METHODE = CM.METHODE
        AND T.ANCIENNETE_M >= MEPR.BORNE_INF
        AND T.ANCIENNETE_M < MEPR.BORNE_SUP
    LEFT JOIN dc_max_calc DCM
        ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
        AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
        AND T.STATE = 'RECONCILED'
),
requete_optimisee AS (
    SELECT DISTINCT
        DATE_ARRETE, TYPE_RAPRO, SERVICE, SOCIETE, COMPTE_BANCAIRE, LIBELLE_COMPTE, DEVISE,
        DATE_OPERATION_SUSPENS, LIBELLE_SUSPENS, DEBIT, CREDIT, SENS_ATTENDU, COTE_SUSPENS,
        ANCIENNETE_J, ANCIENNETE_M, BORNE_ANCIENNETE, PILIER_MONTANT_DEBIT, PILIER_MONTANT_CREDIT,
        METHODE_PROVISION, TAUX, MONTANT_PROVISION, STATUT, DATE_APUREMENT, DC_MAX,
        PRIORITE, COMMENTAIRE, NETTING, DELTA, SENS_DELTA, NUMERO_FICHE, DERNIER_STATUT,
        ID_ECRITURE, ANNOTE_LE
    FROM donnees_completes
    WHERE (STATUT = 'OUTSTANDING')
       OR (STATUT = 'RECONCILED' AND DC_MAX >= P_DATE_ARRETE)
)
SELECT 'OPTIMISE' AS VERSION, COUNT(*) AS NB_LIGNES FROM requete_optimisee;


-- ============================================================
-- ETAPE 2 : RESUME COMPTAGE
-- ============================================================
PROMPT
PROMPT [ETAPE 2/4] RESUME COMPTAGE
PROMPT ============================================================

SELECT
    'ORIGINAL' AS VERSION,
    (SELECT COUNT(*) FROM (
        -- Copie requete originale pour comptage
        SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID
        FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
             BS_ACCTS BS_ACCTS,
             BA_COMPTE_METHODE BA_CPME
        WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
          AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
          AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
          AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
          AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
          AND (
              (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
              OR
              (BRR_TRANSACTIONS.STATE = 'RECONCILED'
               AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
          )
    )) AS NB_RECORD_ID
FROM DUAL;


-- ============================================================
-- ETAPE 3 : VERIFICATION DIFFERENCES (MINUS)
-- ============================================================
PROMPT
PROMPT [ETAPE 3/4] LIGNES DANS ORIGINAL MAIS PAS DANS OPTIMISE
PROMPT ============================================================
PROMPT (Si aucune ligne = OK)

SELECT 'ORIGINAL_ONLY' AS SOURCE, ID_ECRITURE, STATUT, COMPTE_BANCAIRE
FROM (
    -- ORIGINAL
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE, BRR_TRANSACTIONS.STATE AS STATUT, BA_CPME.COMPTE_BANCAIRE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
    MINUS
    -- OPTIMISE (IDs seulement)
    SELECT DISTINCT T.RECORD_ID, T.STATE, CM.COMPTE_BANCAIRE
    FROM BRR_TRANSACTIONS T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN BRR_ACCOUNT_HIERARCHIES H ON H.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN (
        SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
        FROM BRR_TRANSACTIONS WHERE STATE = 'RECONCILED'
        GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
    ) DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE AND DCM.ACCOUNT_ID = T.ACCOUNT_ID AND T.STATE = 'RECONCILED'
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
      AND T.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND T.STATE IN ('OUTSTANDING', 'RECONCILED')
      AND (
          (T.STATE = 'OUTSTANDING')
          OR
          (T.STATE = 'RECONCILED' AND DCM.DC_MAX >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 100;


PROMPT
PROMPT [ETAPE 4/4] LIGNES DANS OPTIMISE MAIS PAS DANS ORIGINAL
PROMPT ============================================================
PROMPT (Si aucune ligne = OK)

SELECT 'OPTIMISE_ONLY' AS SOURCE, ID_ECRITURE, STATUT, COMPTE_BANCAIRE
FROM (
    -- OPTIMISE (IDs seulement)
    SELECT DISTINCT T.RECORD_ID AS ID_ECRITURE, T.STATE AS STATUT, CM.COMPTE_BANCAIRE
    FROM BRR_TRANSACTIONS T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN BRR_ACCOUNT_HIERARCHIES H ON H.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN (
        SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
        FROM BRR_TRANSACTIONS WHERE STATE = 'RECONCILED'
        GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
    ) DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE AND DCM.ACCOUNT_ID = T.ACCOUNT_ID AND T.STATE = 'RECONCILED'
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
      AND T.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND T.STATE IN ('OUTSTANDING', 'RECONCILED')
      AND (
          (T.STATE = 'OUTSTANDING')
          OR
          (T.STATE = 'RECONCILED' AND DCM.DC_MAX >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
    MINUS
    -- ORIGINAL
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID, BRR_TRANSACTIONS.STATE, BA_CPME.COMPTE_BANCAIRE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 100;


-- ============================================================
-- RESUME FINAL
-- ============================================================
PROMPT
PROMPT ============================================================
PROMPT RESUME FINAL
PROMPT ============================================================
PROMPT
PROMPT Si les etapes 3 et 4 ne retournent AUCUNE ligne :
PROMPT   => AUCUNE REGRESSION - Les deux requetes sont equivalentes
PROMPT
PROMPT Si des lignes apparaissent :
PROMPT   => REGRESSION DETECTEE - Analyser les ID_ECRITURE affiches
PROMPT
PROMPT ============================================================
PROMPT FIN DU SCRIPT DE COMPARAISON
PROMPT ============================================================

SET TIMING OFF
