-- ============================================================================
-- COMPARAISON COMPLÈTE - Comptes Accurate 394 vs 342
-- ============================================================================
-- Date: 07/02/2026
-- Objectif: Comparer TOUS les champs pour identifier les différences
-- ============================================================================

SET LINESIZE 300
SET PAGESIZE 100

PROMPT ============================================================================
PROMPT COMPARAISON COMPLÈTE DES COMPTES ACCURATE
PROMPT ============================================================================
PROMPT
PROMPT Compte 394 (BNPP05492-EUR) → Transaction 22.36 ✅ PASSE dans BR_DATA
PROMPT Compte 342 (BBNP83292-EUR) → Transaction 2817  ❌ BLOQUÉE
PROMPT

PROMPT ============================================================================
PROMPT 1. VUE CÔTE À CÔTE - Tous les champs de TA_RN_COMPTE_ACCURATE
PROMPT ============================================================================

SELECT
    '394 (22.36)' AS COMPTE,
    ID_COMPTE_ACCURATE,
    NUM_COMPTE_ACCURATE,
    NOM,
    FLAG_ACTIF,
    TYPE_RAPPRO
FROM TA_RN_COMPTE_ACCURATE
WHERE ID_COMPTE_ACCURATE = 394

UNION ALL

SELECT
    '342 (2817)' AS COMPTE,
    ID_COMPTE_ACCURATE,
    NUM_COMPTE_ACCURATE,
    NOM,
    FLAG_ACTIF,
    TYPE_RAPPRO
FROM TA_RN_COMPTE_ACCURATE
WHERE ID_COMPTE_ACCURATE = 342;

PROMPT
PROMPT ============================================================================
PROMPT 2. COMPARAISON CHAMP PAR CHAMP - Identification des différences
PROMPT ============================================================================

WITH compte_394 AS (
    SELECT * FROM TA_RN_COMPTE_ACCURATE WHERE ID_COMPTE_ACCURATE = 394
),
compte_342 AS (
    SELECT * FROM TA_RN_COMPTE_ACCURATE WHERE ID_COMPTE_ACCURATE = 342
)
SELECT
    'NUM_COMPTE_ACCURATE' AS CHAMP,
    C394.NUM_COMPTE_ACCURATE AS VALEUR_394,
    C342.NUM_COMPTE_ACCURATE AS VALEUR_342,
    CASE WHEN C394.NUM_COMPTE_ACCURATE = C342.NUM_COMPTE_ACCURATE THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM compte_394 C394, compte_342 C342

UNION ALL

SELECT
    'NOM' AS CHAMP,
    NVL(C394.NOM, 'NULL') AS VALEUR_394,
    NVL(C342.NOM, 'NULL') AS VALEUR_342,
    CASE WHEN NVL(C394.NOM, 'NULL') = NVL(C342.NOM, 'NULL') THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM compte_394 C394, compte_342 C342

UNION ALL

SELECT
    'TYPE_RAPPRO' AS CHAMP,
    C394.TYPE_RAPPRO AS VALEUR_394,
    C342.TYPE_RAPPRO AS VALEUR_342,
    CASE WHEN C394.TYPE_RAPPRO = C342.TYPE_RAPPRO THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM compte_394 C394, compte_342 C342

UNION ALL

SELECT
    'FLAG_ACTIF' AS CHAMP,
    C394.FLAG_ACTIF AS VALEUR_394,
    C342.FLAG_ACTIF AS VALEUR_342,
    CASE WHEN C394.FLAG_ACTIF = C342.FLAG_ACTIF THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM compte_394 C394, compte_342 C342;

PROMPT
PROMPT ============================================================================
PROMPT 3. VÉRIFICATION DES LIENS - TA_RN_BANQUE_ACCURATE
PROMPT ============================================================================

SELECT
    '394 (22.36)' AS COMPTE,
    BA.ID_PERIMETRE_BANQUE,
    BA.ID_COMPTE_ACCURATE
FROM TA_RN_BANQUE_ACCURATE BA
WHERE BA.ID_COMPTE_ACCURATE = 394

UNION ALL

SELECT
    '342 (2817)' AS COMPTE,
    BA.ID_PERIMETRE_BANQUE,
    BA.ID_COMPTE_ACCURATE
FROM TA_RN_BANQUE_ACCURATE BA
WHERE BA.ID_COMPTE_ACCURATE = 342

ORDER BY 1;

PROMPT
PROMPT ============================================================================
PROMPT 4. VÉRIFICATION DES PÉRIMÈTRES BANQUE
PROMPT ============================================================================

SELECT
    '394 (22.36)' AS COMPTE,
    PB.ID_PERIMETRE_BANQUE,
    PB.ID_COMPTE_BANCAIRE,
    PB.ID_DEVISE,
    PB.FLAG_ACTIF,
    CB.IDENTIFICATION AS RIB,
    CB.NOM AS NOM_COMPTE_BANCAIRE
FROM TA_RN_BANQUE_ACCURATE BA
    JOIN TA_RN_PERIMETRE_BANQUE PB ON PB.ID_PERIMETRE_BANQUE = BA.ID_PERIMETRE_BANQUE
    JOIN TA_RN_COMPTE_BANCAIRE CB ON CB.ID_COMPTE_BANCAIRE = PB.ID_COMPTE_BANCAIRE
WHERE BA.ID_COMPTE_ACCURATE = 394

UNION ALL

SELECT
    '342 (2817)' AS COMPTE,
    PB.ID_PERIMETRE_BANQUE,
    PB.ID_COMPTE_BANCAIRE,
    PB.ID_DEVISE,
    PB.FLAG_ACTIF,
    CB.IDENTIFICATION AS RIB,
    CB.NOM AS NOM_COMPTE_BANCAIRE
FROM TA_RN_BANQUE_ACCURATE BA
    JOIN TA_RN_PERIMETRE_BANQUE PB ON PB.ID_PERIMETRE_BANQUE = BA.ID_PERIMETRE_BANQUE
    JOIN TA_RN_COMPTE_BANCAIRE CB ON CB.ID_COMPTE_BANCAIRE = PB.ID_COMPTE_BANCAIRE
WHERE BA.ID_COMPTE_ACCURATE = 342

ORDER BY 1;

PROMPT
PROMPT ============================================================================
PROMPT 5. COMPARAISON DES TRANSACTIONS - Caractéristiques dans TA_RN_IMPORT_GESTION_JC
PROMPT ============================================================================

SELECT
    'Transaction 22.36' AS TRANSACTION,
    IMP.OPERATIONNETAMOUNT AS MONTANT,
    IMP.PAYMENTREFERENCE,
    IMP.NUMEROCLIENT,
    IMP.SETTLEMENTMODE,
    IMP.IDENTIFICATIONRIB,
    IMP.OPERATIONNETAMOUNTCURRENCY AS CURRENCY,
    IMP.VALUEDATE,
    IMP.TRADEDATE
FROM TA_RN_IMPORT_GESTION_JC IMP
WHERE IMP.OPERATIONNETAMOUNT = '22.36'
  AND ROWNUM = 1

UNION ALL

SELECT
    'Transaction 2817' AS TRANSACTION,
    IMP.OPERATIONNETAMOUNT AS MONTANT,
    IMP.PAYMENTREFERENCE,
    IMP.NUMEROCLIENT,
    IMP.SETTLEMENTMODE,
    IMP.IDENTIFICATIONRIB,
    IMP.OPERATIONNETAMOUNTCURRENCY AS CURRENCY,
    IMP.VALUEDATE,
    IMP.TRADEDATE
FROM TA_RN_IMPORT_GESTION_JC IMP
WHERE IMP.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1;

PROMPT
PROMPT ============================================================================
PROMPT 6. COMPARAISON DES CHAMPS CRITIQUES DES TRANSACTIONS
PROMPT ============================================================================

WITH trans_22 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION_JC WHERE OPERATIONNETAMOUNT = '22.36' AND ROWNUM = 1
),
trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION_JC WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
)
SELECT
    'SETTLEMENTMODE' AS CHAMP,
    T22.SETTLEMENTMODE AS VALEUR_22_36,
    T2817.SETTLEMENTMODE AS VALEUR_2817,
    CASE WHEN NVL(T22.SETTLEMENTMODE, 'NULL') = NVL(T2817.SETTLEMENTMODE, 'NULL') THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM trans_22 T22, trans_2817 T2817

UNION ALL

SELECT
    'OPERATIONNETAMOUNTCURRENCY' AS CHAMP,
    T22.OPERATIONNETAMOUNTCURRENCY AS VALEUR_22_36,
    T2817.OPERATIONNETAMOUNTCURRENCY AS VALEUR_2817,
    CASE WHEN NVL(T22.OPERATIONNETAMOUNTCURRENCY, 'NULL') = NVL(T2817.OPERATIONNETAMOUNTCURRENCY, 'NULL') THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM trans_22 T22, trans_2817 T2817

UNION ALL

SELECT
    'TYPEREGLEMENT' AS CHAMP,
    T22.TYPEREGLEMENT AS VALEUR_22_36,
    T2817.TYPEREGLEMENT AS VALEUR_2817,
    CASE WHEN NVL(T22.TYPEREGLEMENT, 'NULL') = NVL(T2817.TYPEREGLEMENT, 'NULL') THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM trans_22 T22, trans_2817 T2817

UNION ALL

SELECT
    'STATUTREGLEMENT' AS CHAMP,
    T22.STATUTREGLEMENT AS VALEUR_22_36,
    T2817.STATUTREGLEMENT AS VALEUR_2817,
    CASE WHEN NVL(T22.STATUTREGLEMENT, 'NULL') = NVL(T2817.STATUTREGLEMENT, 'NULL') THEN '✅ IDENTIQUE' ELSE '❌ DIFFÉRENT' END AS STATUT
FROM trans_22 T22, trans_2817 T2817;

PROMPT
PROMPT ============================================================================
PROMPT 7. VÉRIFICATION TA_RN_GESTION_JC - Paramétrage des comptes
PROMPT ============================================================================

SELECT
    '394 (22.36)' AS COMPTE,
    GJ.ID_COMPTE_ACCURATE,
    GJ.ID_PRODUIT,
    GJ.ID_MODE_REGLEMENT,
    P.CODE_PRODUIT,
    P.LIBELLE AS LIBELLE_PRODUIT,
    MR.CODE_MODE_REGLEMENT,
    MR.LIBELLE AS LIBELLE_MODE_REGLEMENT
FROM TA_RN_GESTION_JC GJ
    LEFT JOIN TA_RN_PRODUIT P ON P.ID_PRODUIT = GJ.ID_PRODUIT
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.ID_MODE_REGLEMENT = GJ.ID_MODE_REGLEMENT
WHERE GJ.ID_COMPTE_ACCURATE = 394

UNION ALL

SELECT
    '342 (2817)' AS COMPTE,
    GJ.ID_COMPTE_ACCURATE,
    GJ.ID_PRODUIT,
    GJ.ID_MODE_REGLEMENT,
    P.CODE_PRODUIT,
    P.LIBELLE AS LIBELLE_PRODUIT,
    MR.CODE_MODE_REGLEMENT,
    MR.LIBELLE AS LIBELLE_MODE_REGLEMENT
FROM TA_RN_GESTION_JC GJ
    LEFT JOIN TA_RN_PRODUIT P ON P.ID_PRODUIT = GJ.ID_PRODUIT
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.ID_MODE_REGLEMENT = GJ.ID_MODE_REGLEMENT
WHERE GJ.ID_COMPTE_ACCURATE = 342

ORDER BY 1;

PROMPT
PROMPT Si aucune ligne → Compte non paramétré dans TA_RN_GESTION_JC
PROMPT

PROMPT ============================================================================
PROMPT 8. COMPTAGE - Combien de comptes Accurate ont TYPE_RAPPRO='B' et sont dans GESTION_JC ?
PROMPT ============================================================================

SELECT
    CA.TYPE_RAPPRO,
    COUNT(DISTINCT CA.ID_COMPTE_ACCURATE) AS NB_COMPTES_TOTAL,
    COUNT(DISTINCT GJ.ID_COMPTE_ACCURATE) AS NB_COMPTES_DANS_GESTION_JC
FROM TA_RN_COMPTE_ACCURATE CA
    LEFT JOIN TA_RN_GESTION_JC GJ ON GJ.ID_COMPTE_ACCURATE = CA.ID_COMPTE_ACCURATE
WHERE CA.TYPE_RAPPRO = 'B'
  AND CA.FLAG_ACTIF = 'O'
GROUP BY CA.TYPE_RAPPRO;

PROMPT
PROMPT ============================================================================
PROMPT 9. RÉSUMÉ DES DIFFÉRENCES CLÉS
PROMPT ============================================================================

PROMPT
PROMPT Vérifiez les sections ci-dessus pour identifier:
PROMPT - Section 2: Différences dans les champs de TA_RN_COMPTE_ACCURATE (❌)
PROMPT - Section 4: Différences dans ID_DEVISE ou FLAG_ACTIF du périmètre banque
PROMPT - Section 6: Différences dans SETTLEMENTMODE, TYPEREGLEMENT, etc.
PROMPT - Section 7: Présence ou absence dans TA_RN_GESTION_JC
PROMPT
PROMPT Ces différences expliquent pourquoi 22.36 passe mais 2817 est bloqué !
PROMPT

PROMPT ============================================================================
PROMPT FIN COMPARAISON
PROMPT ============================================================================
