-- ============================================================================
-- COMPARAISON COMPLÈTE - Transaction 22.36 vs 2817
-- ============================================================================
-- Date: 07/02/2026
-- Objectif: Comparer TOUS les attributs pour identifier la différence de filtrage
-- ============================================================================

PROMPT ============================================================================
PROMPT 1. DONNÉES BRUTES - TA_RN_IMPORT_GESTION_JC
PROMPT ============================================================================

-- Transaction 22.36
SELECT
    '===== TRANSACTION 22.36 =====' AS SEPARATOR,
    T.*
FROM TA_RN_IMPORT_GESTION_JC T
WHERE OPERATIONNETAMOUNT = '22.36'
  AND ROWNUM = 1;

PROMPT

-- Transaction 2817
SELECT
    '===== TRANSACTION 2817 =====' AS SEPARATOR,
    T.*
FROM TA_RN_IMPORT_GESTION_JC T
WHERE OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1;

PROMPT
PROMPT ============================================================================
PROMPT 2. COMPARAISON CÔTE À CÔTE DES ATTRIBUTS CLÉS
PROMPT ============================================================================

SELECT
    'NumeroClient' AS Attribut,
    T1.NUMEROCLIENT AS Val_22_36,
    T2.NUMEROCLIENT AS Val_2817,
    CASE WHEN T1.NUMEROCLIENT = T2.NUMEROCLIENT THEN 'IDENTIQUE' ELSE 'DIFFÉRENT' END AS Statut
FROM TA_RN_IMPORT_GESTION_JC T1,
     TA_RN_IMPORT_GESTION_JC T2
WHERE T1.OPERATIONNETAMOUNT = '22.36'
  AND T2.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1

UNION ALL

SELECT
    'SettlementMode' AS Attribut,
    T1.SETTLEMENTMODE AS Val_22_36,
    T2.SETTLEMENTMODE AS Val_2817,
    CASE WHEN T1.SETTLEMENTMODE = T2.SETTLEMENTMODE THEN 'IDENTIQUE' ELSE 'DIFFÉRENT' END AS Statut
FROM TA_RN_IMPORT_GESTION_JC T1,
     TA_RN_IMPORT_GESTION_JC T2
WHERE T1.OPERATIONNETAMOUNT = '22.36'
  AND T2.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1

UNION ALL

SELECT
    'BankCode' AS Attribut,
    T1.BANKCODE AS Val_22_36,
    T2.BANKCODE AS Val_2817,
    CASE WHEN T1.BANKCODE = T2.BANKCODE THEN 'IDENTIQUE' ELSE 'DIFFÉRENT' END AS Statut
FROM TA_RN_IMPORT_GESTION_JC T1,
     TA_RN_IMPORT_GESTION_JC T2
WHERE T1.OPERATIONNETAMOUNT = '22.36'
  AND T2.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1

UNION ALL

SELECT
    'BranchCode' AS Attribut,
    T1.BRANCHCODE AS Val_22_36,
    T2.BRANCHCODE AS Val_2817,
    CASE WHEN T1.BRANCHCODE = T2.BRANCHCODE THEN 'IDENTIQUE' ELSE 'DIFFÉRENT' END AS Statut
FROM TA_RN_IMPORT_GESTION_JC T1,
     TA_RN_IMPORT_GESTION_JC T2
WHERE T1.OPERATIONNETAMOUNT = '22.36'
  AND T2.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1

UNION ALL

SELECT
    'IdentificationRIB' AS Attribut,
    T1.IDENTIFICATIONRIB AS Val_22_36,
    T2.IDENTIFICATIONRIB AS Val_2817,
    CASE WHEN T1.IDENTIFICATIONRIB = T2.IDENTIFICATIONRIB THEN 'IDENTIQUE' ELSE 'DIFFÉRENT' END AS Statut
FROM TA_RN_IMPORT_GESTION_JC T1,
     TA_RN_IMPORT_GESTION_JC T2
WHERE T1.OPERATIONNETAMOUNT = '22.36'
  AND T2.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1

UNION ALL

SELECT
    'Commentaire' AS Attribut,
    SUBSTR(T1.COMMENTAIRE, 1, 50) AS Val_22_36,
    SUBSTR(T2.COMMENTAIRE, 1, 50) AS Val_2817,
    CASE WHEN T1.COMMENTAIRE = T2.COMMENTAIRE THEN 'IDENTIQUE' ELSE 'DIFFÉRENT' END AS Statut
FROM TA_RN_IMPORT_GESTION_JC T1,
     TA_RN_IMPORT_GESTION_JC T2
WHERE T1.OPERATIONNETAMOUNT = '22.36'
  AND T2.OPERATIONNETAMOUNT = '2817'
  AND ROWNUM = 1;

PROMPT
PROMPT ============================================================================
PROMPT 3. VÉRIFICATION DES COMPTES BANCAIRES ASSOCIÉS
PROMPT ============================================================================

-- Pour 22.36
SELECT
    '22.36 - RIB 00010207054' AS Transaction,
    RCB.ID_COMPTE_BANCAIRE,
    RCB.IDENTIFICATION,
    RCB.NOM,
    RCB.BANKCODE,
    RCB.BRANCHCODE,
    RPB.ID_PERIMETRE_BANQUE,
    RPB.FLAG_ACTIF AS PERIMETRE_ACTIF,
    RCA.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RCA.TYPE_RAPPRO,
    RCA.FLAG_ACTIF AS COMPTE_ACTIF
FROM TA_RN_COMPTE_BANCAIRE RCB
    LEFT JOIN TA_RN_PERIMETRE_BANQUE RPB ON RPB.ID_COMPTE_BANCAIRE = RCB.ID_COMPTE_BANCAIRE
    LEFT JOIN TA_RN_BANQUE_ACCURATE RBA ON RBA.ID_PERIMETRE_BANQUE = RPB.ID_PERIMETRE_BANQUE
    LEFT JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RBA.ID_COMPTE_ACCURATE
WHERE RCB.IDENTIFICATION = '00010207054';

PROMPT

-- Pour 2817
SELECT
    '2817 - RIB 00016111832' AS Transaction,
    RCB.ID_COMPTE_BANCAIRE,
    RCB.IDENTIFICATION,
    RCB.NOM,
    RCB.BANKCODE,
    RCB.BRANCHCODE,
    RPB.ID_PERIMETRE_BANQUE,
    RPB.FLAG_ACTIF AS PERIMETRE_ACTIF,
    RCA.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RCA.TYPE_RAPPRO,
    RCA.FLAG_ACTIF AS COMPTE_ACTIF
FROM TA_RN_COMPTE_BANCAIRE RCB
    LEFT JOIN TA_RN_PERIMETRE_BANQUE RPB ON RPB.ID_COMPTE_BANCAIRE = RCB.ID_COMPTE_BANCAIRE
    LEFT JOIN TA_RN_BANQUE_ACCURATE RBA ON RBA.ID_PERIMETRE_BANQUE = RPB.ID_PERIMETRE_BANQUE
    LEFT JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RBA.ID_COMPTE_ACCURATE
WHERE RCB.IDENTIFICATION = '00016111832';

PROMPT
PROMPT ============================================================================
PROMPT 4. VÉRIFICATION PARAMÉTRAGE GESTION_JC POUR LES COMPTES ACCURATE
PROMPT ============================================================================

-- Pour compte 394 (22.36)
SELECT
    '394 (22.36)' AS Compte,
    RGJ.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RP.CODE_PRODUIT,
    RMR.CODE_MODE_REGLEMENT
FROM TA_RN_GESTION_JC RGJ
    JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RGJ.ID_COMPTE_ACCURATE
    JOIN TA_RN_PRODUIT RP ON RP.ID_PRODUIT = RGJ.ID_PRODUIT
    JOIN TA_RN_MODE_REGLEMENT RMR ON RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
WHERE RGJ.ID_COMPTE_ACCURATE = 394;

PROMPT

-- Pour compte 342 (2817)
SELECT
    '342 (2817)' AS Compte,
    RGJ.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RP.CODE_PRODUIT,
    RMR.CODE_MODE_REGLEMENT
FROM TA_RN_GESTION_JC RGJ
    JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RGJ.ID_COMPTE_ACCURATE
    JOIN TA_RN_PRODUIT RP ON RP.ID_PRODUIT = RGJ.ID_PRODUIT
    JOIN TA_RN_MODE_REGLEMENT RMR ON RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
WHERE RGJ.ID_COMPTE_ACCURATE = 342;

PROMPT
PROMPT ============================================================================
PROMPT 5. TEST DE LA CONDITION D'INSERTION COMPLÈTE (avec compte accurate)
PROMPT ============================================================================

-- Test pour 22.36 avec compte 394
SELECT
    '22.36 (Compte 394)' AS Test,
    RGJ.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RP.CODE_PRODUIT,
    RMR.CODE_MODE_REGLEMENT,
    'MATCH TROUVÉ DANS GESTION_JC' AS Resultat
FROM TA_RN_GESTION_JC RGJ
    JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RGJ.ID_COMPTE_ACCURATE
    JOIN TA_RN_PRODUIT RP ON RP.ID_PRODUIT = RGJ.ID_PRODUIT
    JOIN TA_RN_MODE_REGLEMENT RMR ON RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
WHERE RGJ.ID_COMPTE_ACCURATE = 394
  AND (RP.CODE_PRODUIT = 'ALL' OR RP.CODE_PRODUIT = '00838038')
  AND (RMR.CODE_MODE_REGLEMENT = 'ALL' OR RMR.CODE_MODE_REGLEMENT = 'VO');

PROMPT

-- Test pour 2817 avec compte 342
SELECT
    '2817 (Compte 342)' AS Test,
    RGJ.ID_COMPTE_ACCURATE,
    RCA.NUM_COMPTE_ACCURATE,
    RP.CODE_PRODUIT,
    RMR.CODE_MODE_REGLEMENT,
    'MATCH TROUVÉ DANS GESTION_JC' AS Resultat
FROM TA_RN_GESTION_JC RGJ
    JOIN TA_RN_COMPTE_ACCURATE RCA ON RCA.ID_COMPTE_ACCURATE = RGJ.ID_COMPTE_ACCURATE
    JOIN TA_RN_PRODUIT RP ON RP.ID_PRODUIT = RGJ.ID_PRODUIT
    JOIN TA_RN_MODE_REGLEMENT RMR ON RMR.ID_MODE_REGLEMENT = RGJ.ID_MODE_REGLEMENT
WHERE RGJ.ID_COMPTE_ACCURATE = 342
  AND (RP.CODE_PRODUIT = 'ALL' OR RP.CODE_PRODUIT = '90141615')
  AND (RMR.CODE_MODE_REGLEMENT = 'ALL' OR RMR.CODE_MODE_REGLEMENT = 'VO');

PROMPT
PROMPT ============================================================================
PROMPT 6. VÉRIFICATION DANS BR_DATA
PROMPT ============================================================================

-- Chercher 22.36 dans BR_DATA
SELECT
    'BR_DATA - 22.36' AS Source,
    COUNT(*) AS NB_LIGNES,
    CASE
        WHEN COUNT(*) > 0 THEN 'TROUVÉ - Transaction insérée'
        ELSE 'NON TROUVÉ - Transaction absente'
    END AS Statut
FROM BANKREC.BR_DATA
WHERE AMOUNT IN (22.36, -22.36);

PROMPT

-- Chercher 2817 dans BR_DATA
SELECT
    'BR_DATA - 2817' AS Source,
    COUNT(*) AS NB_LIGNES,
    CASE
        WHEN COUNT(*) > 0 THEN 'TROUVÉ - Transaction insérée'
        ELSE 'NON TROUVÉ - Transaction absente'
    END AS Statut
FROM BANKREC.BR_DATA
WHERE AMOUNT IN (2817, -2817);

PROMPT
PROMPT ============================================================================
PROMPT RÉSUMÉ DIAGNOSTIC
PROMPT ============================================================================
PROMPT Ce script compare TOUS les attributs des deux transactions.
PROMPT
PROMPT POINTS DE VÉRIFICATION :
PROMPT 1. Attributs IMPORT (NumeroClient, SettlementMode, BankCode, etc.)
PROMPT 2. Comptes bancaires et leur statut (FLAG_ACTIF)
PROMPT 3. Comptes accurate et TYPE_RAPPRO
PROMPT 4. Paramétrage GESTION_JC
PROMPT 5. Présence dans BR_DATA
PROMPT
PROMPT OBJECTIF : Identifier LA différence qui cause le filtrage de 2817
PROMPT ============================================================================
