-- ============================================================================
-- DIAGNOSTIC COMPLET - Pourquoi 2817 EUR est rejetée ?
-- ============================================================================
-- Date: 07/02/2026
-- Objectif: Analyser les données existantes pour comprendre le rejet de 2817
-- ============================================================================

SET LINESIZE 300
SET PAGESIZE 200

PROMPT ============================================================================
PROMPT DIAGNOSTIC - Transaction 2817 EUR vs 22.36 EUR
PROMPT ============================================================================

PROMPT
PROMPT ============================================================================
PROMPT 1. LES TRANSACTIONS SONT-ELLES DANS TA_RN_IMPORT_GESTION ?
PROMPT ============================================================================

SELECT
    OPERATIONNETAMOUNT AS MONTANT,
    PAYMENTREFERENCE,
    NUMEROCLIENT AS CODE_CLIENT,
    IDENTIFICATIONRIB AS RIB,
    SETTLEMENTMODE AS MODE_REGLT,
    OPERATIONNETAMOUNTCURRENCY AS DEVISE,
    TYPEREGLEMENT AS TYPE_REGLT,
    STATUTREGLEMENT AS STATUT,
    IDENTIFICATION AS CODE_SOCIETE,
    ID_CHARGEMENT_GESTION
FROM TA_RN_IMPORT_GESTION
WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
ORDER BY OPERATIONNETAMOUNT;

PROMPT
PROMPT Si vide → Les transactions ne sont PAS dans TA_RN_IMPORT_GESTION
PROMPT        → Soit pas encore importées, soit dans TA_RN_IMPORT_GESTION_JC
PROMPT

PROMPT ============================================================================
PROMPT 2. VÉRIFICATION - Sont-elles dans TA_RN_IMPORT_GESTION_JC ?
PROMPT ============================================================================

SELECT
    OPERATIONNETAMOUNT AS MONTANT,
    PAYMENTREFERENCE,
    NUMEROCLIENT AS CODE_CLIENT,
    IDENTIFICATIONRIB AS RIB,
    COUNT(*) AS NB
FROM TA_RN_IMPORT_GESTION_JC
WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
GROUP BY OPERATIONNETAMOUNT, PAYMENTREFERENCE, NUMEROCLIENT, IDENTIFICATIONRIB
ORDER BY OPERATIONNETAMOUNT;

PROMPT
PROMPT Si présentes dans _JC → Mauvais script ! Les comptes ont TYPE_RAPPRO='J' pas 'B'
PROMPT

PROMPT ============================================================================
PROMPT 3. MAPPING DES COMPTES ACCURATE 394 et 342
PROMPT ============================================================================
PROMPT Compte 394 → Transaction 22.36 EUR
PROMPT Compte 342 → Transaction 2817 EUR

-- Compte 394 (22.36)
SELECT
    '394 (22.36)' AS COMPTE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO,
    CA.FLAG_ACTIF,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CBS.NUMERO AS NUM_CBS,
    CBS.RIBBANKCODE||CBS.RIBBRANCHCODE||CBS.RIBIDENTIFICATION||CBS.RIBCHECKDIGIT AS RIB_COMPLET,
    CBS.GENERATIONCONTREPARTIE,
    GA.ID_COMPTE_ACCURATE
FROM TA_RN_COMPTE_ACCURATE CA
    LEFT JOIN TA_RN_GESTION_ACCURATE GA ON GA.ID_COMPTE_ACCURATE = CA.ID_COMPTE_ACCURATE
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE CA.ID_COMPTE_ACCURATE = 394

UNION ALL

-- Compte 342 (2817)
SELECT
    '342 (2817)' AS COMPTE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO,
    CA.FLAG_ACTIF,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CBS.NUMERO AS NUM_CBS,
    CBS.RIBBANKCODE||CBS.RIBBRANCHCODE||CBS.RIBIDENTIFICATION||CBS.RIBCHECKDIGIT AS RIB_COMPLET,
    CBS.GENERATIONCONTREPARTIE,
    GA.ID_COMPTE_ACCURATE
FROM TA_RN_COMPTE_ACCURATE CA
    LEFT JOIN TA_RN_GESTION_ACCURATE GA ON GA.ID_COMPTE_ACCURATE = CA.ID_COMPTE_ACCURATE
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE CA.ID_COMPTE_ACCURATE = 342

ORDER BY 1;

PROMPT
PROMPT ============================================================================
PROMPT 4. DIAGNOSTIC - Compte 342 dans TA_RN_GESTION_ACCURATE ?
PROMPT ============================================================================

SELECT
    CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌ ROOT CAUSE' END AS RESULTAT,
    COUNT(*) AS NB_LIENS
FROM TA_RN_GESTION_ACCURATE
WHERE ID_COMPTE_ACCURATE = 342;

PROMPT
PROMPT Si NON → ROOT CAUSE TROUVÉE !
PROMPT    Le compte 342 n'est pas paramétré dans TA_RN_GESTION_ACCURATE
PROMPT    → La transaction 2817 ne peut PAS être exportée
PROMPT

PROMPT ============================================================================
PROMPT 5. DÉTAILS RIB - Transactions 22.36 et 2817
PROMPT ============================================================================

WITH trans AS (
    SELECT
        OPERATIONNETAMOUNT,
        PAYMENTREFERENCE,
        NUMEROCLIENT,
        RIBBANKCODE,
        RIBBRANCHCODE,
        IDENTIFICATIONRIB,
        RIBCHECKDIGIT,
        SETTLEMENTMODE,
        TYPEREGLEMENT,
        IDENTIFICATION AS CODE_SOCIETE,
        OPERATIONNETAMOUNTCURRENCY
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    T.OPERATIONNETAMOUNT AS MONTANT,
    T.RIBBANKCODE||T.RIBBRANCHCODE||T.IDENTIFICATIONRIB||T.RIBCHECKDIGIT AS RIB_COMPLET,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    GA.ID_COMPTE_ACCURATE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO,
    T.SETTLEMENTMODE,
    T.TYPEREGLEMENT,
    T.CODE_SOCIETE,
    T.OPERATIONNETAMOUNTCURRENCY
FROM trans T
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = T.RIBBANKCODE
       AND CBS.RIBBRANCHCODE = T.RIBBRANCHCODE
       AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
       AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
    LEFT JOIN TA_RN_GESTION_ACCURATE GA
        ON GA.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
    LEFT JOIN TA_RN_COMPTE_ACCURATE CA
        ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
ORDER BY T.OPERATIONNETAMOUNT;

PROMPT
PROMPT ============================================================================
PROMPT 6. VÉRIFICATION CODE SOCIÉTÉ - 2817
PROMPT ============================================================================

WITH trans_2817 AS (
    SELECT IDENTIFICATION AS CODE_SOCIETE
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT = '2817'
      AND ROWNUM = 1
)
SELECT
    T.CODE_SOCIETE,
    S.ID_SOCIETE,
    S.NOM,
    CASE WHEN S.ID_SOCIETE IS NOT NULL THEN 'OUI ✅' ELSE 'NON ❌ SOCIETE INEXISTANTE' END AS EXISTE_TA_RN_SOCIETE
FROM trans_2817 T
    LEFT JOIN TA_RN_SOCIETE S ON S.CODE = T.CODE_SOCIETE;

PROMPT
PROMPT Si SOCIETE INEXISTANTE → Le code société n'existe pas dans TA_RN_SOCIETE
PROMPT    → La fonction LibelleSociete() retourne ''
PROMPT    → Vérifier si cela empêche le traitement
PROMPT

PROMPT ============================================================================
PROMPT 7. EXCLUSIONS - Transaction 2817
PROMPT ============================================================================

WITH trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
),
cbs_342 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342 AND ROWNUM = 1
)
SELECT
    'Exclusion SOCIETE' AS TYPE_EXCLUSION,
    T2817.IDENTIFICATION AS VALEUR,
    CASE WHEN ES.ID_SOCIETE IS NOT NULL THEN 'OUI ❌ EXCLUE' ELSE 'NON ✅' END AS EXCLUE
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_SOCIETE S ON S.CODE = T2817.IDENTIFICATION
    LEFT JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_SOCIETE = S.ID_SOCIETE
        AND ES.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    'Exclusion DEVISE' AS TYPE_EXCLUSION,
    T2817.OPERATIONNETAMOUNTCURRENCY AS VALEUR,
    CASE WHEN ED.ID_DEVISE IS NOT NULL THEN 'OUI ❌ EXCLUE' ELSE 'NON ✅' END AS EXCLUE
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_DEVISE D ON D.CODE_ISO_DEVISE = T2817.OPERATIONNETAMOUNTCURRENCY
    LEFT JOIN TA_RN_EXCLUSION_DEVISE ED ON ED.ID_DEVISE = D.ID_DEVISE
        AND ED.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    'Exclusion MODE_REGLEMENT' AS TYPE_EXCLUSION,
    T2817.SETTLEMENTMODE AS VALEUR,
    CASE WHEN EMR.ID_MODE_REGLEMENT IS NOT NULL THEN 'OUI ❌ EXCLUE' ELSE 'NON ✅' END AS EXCLUE
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.CODE_MODE_REGLEMENT = T2817.SETTLEMENTMODE
    LEFT JOIN TA_RN_EXCLUSION_MR EMR ON EMR.ID_MODE_REGLEMENT = MR.ID_MODE_REGLEMENT
        AND EMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    'Exclusion TYPE_REGLEMENT' AS TYPE_EXCLUSION,
    T2817.TYPEREGLEMENT AS VALEUR,
    CASE WHEN ETR.ID_COMPTE_BANCAIRE_SYSTEME IS NOT NULL THEN 'OUI ❌ EXCLUE' ELSE 'NON ✅' END AS EXCLUE
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_EXCLUSION_TR ETR ON ETR.TYPE_REGLEMENT = T2817.TYPEREGLEMENT
        AND ETR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME;

PROMPT
PROMPT ============================================================================
PROMPT 8. MODE CUMUL - Transaction 2817
PROMPT ============================================================================

WITH trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
),
cbs_342 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342 AND ROWNUM = 1
)
SELECT
    T2817.NUMEROCLIENT,
    T2817.SETTLEMENTMODE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN CMR.ID_MODE_REGLEMENT IS NOT NULL THEN 'OUI ❌ MODE CUMUL ACTIF' ELSE 'NON ✅' END AS MODE_CUMUL
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.CODE_MODE_REGLEMENT = T2817.SETTLEMENTMODE
    LEFT JOIN TA_RN_PRODUIT P ON P.CODE_PRODUIT = T2817.NUMEROCLIENT OR P.CODE_PRODUIT = 'ALL'
    LEFT JOIN TA_RN_CUMUL_MR CMR ON CMR.ID_MODE_REGLEMENT = MR.ID_MODE_REGLEMENT
        AND CMR.ID_PRODUIT = P.ID_PRODUIT
        AND CMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME;

PROMPT
PROMPT Si MODE CUMUL ACTIF → La transaction sera cumulée, pas exportée en détail
PROMPT

PROMPT ============================================================================
PROMPT 9. PRÉSENCE DANS TA_RN_EXPORT ?
PROMPT ============================================================================

SELECT
    SOURCE,
    ACCNUM,
    ORAMT AS MONTANT,
    TRDAT AS DATE_TRADE,
    ORAMTCCY AS DEVISE,
    ID_CHARGEMENT
FROM TA_RN_EXPORT
WHERE SOURCE = 'GEST'
  AND ORAMT IN ('22.36', '2817')
ORDER BY ORAMT;

PROMPT
PROMPT Si seulement 22.36 → 2817 a été filtrée AVANT l'export
PROMPT Si vide pour les deux → Aucune exportée (problème global)
PROMPT

PROMPT ============================================================================
PROMPT 10. RÉSUMÉ DIAGNOSTIC
PROMPT ============================================================================

SELECT '22.36 dans TA_RN_IMPORT_GESTION ?' AS VERIFICATION,
       CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END AS RESULTAT
FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '22.36'
UNION ALL
SELECT '2817 dans TA_RN_IMPORT_GESTION ?',
       CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END
FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817'
UNION ALL
SELECT 'Compte 394 dans TA_RN_GESTION_ACCURATE ?',
       CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END
FROM TA_RN_GESTION_ACCURATE WHERE ID_COMPTE_ACCURATE = 394
UNION ALL
SELECT 'Compte 342 dans TA_RN_GESTION_ACCURATE ?',
       CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌ ROOT CAUSE' END
FROM TA_RN_GESTION_ACCURATE WHERE ID_COMPTE_ACCURATE = 342
UNION ALL
SELECT '22.36 dans TA_RN_EXPORT ?',
       CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END
FROM TA_RN_EXPORT WHERE SOURCE = 'GEST' AND ORAMT = '22.36'
UNION ALL
SELECT '2817 dans TA_RN_EXPORT ?',
       CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END
FROM TA_RN_EXPORT WHERE SOURCE = 'GEST' AND ORAMT = '2817';

PROMPT
PROMPT ============================================================================
PROMPT INTERPRÉTATION
PROMPT ============================================================================
PROMPT
PROMPT CAS 1: Si 2817 PAS dans TA_RN_IMPORT_GESTION
PROMPT   → Pas encore importée OU mauvaise table (vérifier _JC)
PROMPT
PROMPT CAS 2: Si 2817 dans IMPORT mais compte 342 PAS dans TA_RN_GESTION_ACCURATE
PROMPT   → ROOT CAUSE : Paramétrage manquant
PROMPT   → Solution: Ajouter le lien dans TA_RN_GESTION_ACCURATE
PROMPT
PROMPT CAS 3: Si 2817 dans IMPORT et compte 342 dans GESTION_ACCURATE mais PAS dans EXPORT
PROMPT   → Filtre d'exclusion actif (SOCIETE, DEVISE, MODE_REGLT, TYPE_REGLT, CUMUL)
PROMPT   → Analyser la section 7 et 8
PROMPT
PROMPT CAS 4: Si 2817 dans EXPORT mais PAS dans BR_DATA
PROMPT   → Problème APRÈS l'export (processus Oracle Bankrec)
PROMPT
PROMPT ============================================================================
PROMPT FIN DIAGNOSTIC
PROMPT ============================================================================
