-- ============================================================
-- REQUETE OPTIMISEE - DTC 670
-- SQL_ID original : 4v9ag77cam8uu
-- Date : 20/02/2026
-- ============================================================
-- STRATEGIE : Modifications MINIMALES
--   1. Nouveaux HINTS pour forcer un meilleur plan d'execution
--   2. INDEX recommandes (a creer sur la base)
--   3. Pas de reecriture complete de la requete
-- ============================================================

-- ============================================================
-- PARTIE 1 : INDEX A CREER (AVANT EXECUTION)
-- ============================================================
-- IMPORTANT : Executer ces CREATE INDEX en production AVANT le batch

-- Index sur BRR_TRANSACTIONS (table principale - millions de lignes)
CREATE INDEX IDX_BRR_TRANS_STATE_DATE ON BANKREC.BR_DATA(STATE, TRANS_DATE);
CREATE INDEX IDX_BRR_TRANS_ACCT_STATE ON BANKREC.BR_DATA(ACCT_ID, STATE);
CREATE INDEX IDX_BRR_TRANS_REC_REF ON BANKREC.BR_DATA(REC_GROUP, ACCT_ID, TRANS_DATE);

-- Index sur BRR_ACCOUNT_HIERARCHIES (DEJA EXISTANT - ORA-01408)
-- CREATE INDEX IDX_BRR_HIER_ACCT ON BANKREC.BRR_ACCOUNT_HIERARCHIES(ACCOUNT_ID);

-- Index sur tables de parametrage EXP_RNAPA (DEJA EXISTANTS - ORA-01408)
-- CREATE INDEX EXP_RNAPA.IDX_BA_CATEG_ANC_BORNES ON EXP_RNAPA.BA_CATEG_ANCIENNETE(BORNE_INF, BORNE_SUP);
-- CREATE INDEX EXP_RNAPA.IDX_BA_PILIERS_BORNES ON EXP_RNAPA.BA_PILIERS_MONTANTS(BORNE_INF, BORNE_SUP);
-- CREATE INDEX EXP_RNAPA.IDX_BA_METH_PROV ON EXP_RNAPA.BA_METHODE_PROVISION(METHODE, BORNE_INF, BORNE_SUP);

-- Statistiques (executer apres creation des index)
EXEC DBMS_STATS.GATHER_TABLE_STATS('BANKREC', 'BR_DATA', CASCADE => TRUE);


-- ============================================================
-- PARTIE 2 : REQUETE OPTIMISEE (MODIFICATIONS MINIMALES)
-- ============================================================
-- Changements effectues :
--   [H1] Hint LEADING pour forcer l'ordre de jointure
--   [H2] Hint USE_HASH pour les jointures volumineuses
--   [H3] Hint NO_MERGE pour empecher le merge des sous-requetes
--   [H4] Hint CARDINALITY pour aider l'optimiseur
--   [H5] Suppression du hint optimizer_features_enable obsolete
--   [U1] UNION ALL au lieu de UNION (statuts exclusifs = pas de doublons)
-- ============================================================

SELECT /*+ LEADING(BRR_TRANSACTIONS BS_ACCTS BA_CPME)
           USE_HASH(BS_ACCTS BA_CPME)
           NO_MERGE
           CARDINALITY(BRR_TRANSACTIONS 100000) */ DISTINCT
    (SELECT TO_CHAR(:B1) FROM DUAL) AS DATE_ARRETE,
    (SELECT /*+ NO_UNNEST */ DECODE(RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2),
        'RB', 'Rapprochement Bancaire',
        'RC', 'Rapprochement de Contrôle',
        'JC', 'Justification de compte',
        'CL', 'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                FROM BRR_ACCOUNT_HIERARCHIES H
                                WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT /*+ NO_UNNEST */ B.ACCT_NUM
     FROM BS_ACCTS B
     WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                        FROM BRR_ACCOUNT_HIERARCHIES H
                        WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT /*+ NO_UNNEST */ ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC',
            'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
            'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    -- [OPT] Calcul direct sans sous-requete DUAL
    TO_DATE(:B1, 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT /*+ NO_UNNEST */ LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT /*+ NO_UNNEST */ TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE MEPR.METHODE = BA_CPME.METHODE  -- [OPT] Utilise BA_CPME.METHODE directement
       AND MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    NULL AS DATE_APUREMENT,
    NULL AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
        'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT /*+ NO_UNNEST */ (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = :B2
  AND (SELECT /*+ NO_UNNEST */ B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE(:B1, 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'OUTSTANDING'  -- [OPT] Sans parentheses

UNION ALL  -- [U1] UNION ALL au lieu de UNION (pas de doublons possibles)

SELECT /*+ LEADING(BRR_TRANSACTIONS BS_ACCTS BA_CPME)
           USE_HASH(BS_ACCTS BA_CPME)
           NO_MERGE
           CARDINALITY(BRR_TRANSACTIONS 100000) */ DISTINCT
    (SELECT TO_CHAR(:B1) FROM DUAL) AS DATE_ARRETE,
    (SELECT /*+ NO_UNNEST */ DECODE(RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2),
        'RB', 'Rapprochement Bancaire',
        'RC', 'Rapprochement de Contrôle',
        'JC', 'Justification de compte',
        'CL', 'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                FROM BRR_ACCOUNT_HIERARCHIES H
                                WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT /*+ NO_UNNEST */ B.ACCT_NUM
     FROM BS_ACCTS B
     WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                        FROM BRR_ACCOUNT_HIERARCHIES H
                        WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT /*+ NO_UNNEST */ ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC',
            'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
            'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    -- [OPT] Calcul direct sans sous-requete DUAL
    TO_DATE(:B1, 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT /*+ NO_UNNEST */ LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT /*+ NO_UNNEST */ LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT /*+ NO_UNNEST */ TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE MEPR.METHODE = BA_CPME.METHODE  -- [OPT] Utilise BA_CPME.METHODE directement
       AND MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(:B1, 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    TO_DATE(BRR_TRANSACTIONS.UPDATE_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,
    -- [CRITIQUE] Sous-requete DC_MAX - cause principale ORA-01555
    (SELECT /*+ NO_UNNEST INDEX(E IDX_BRR_TRANS_REC_REF) */ MAX(E.TRANSACTION_DATE)
     FROM BRR_TRANSACTIONS E
     WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
       AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
        'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT /*+ NO_UNNEST */ (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = :B2
  AND (SELECT /*+ NO_UNNEST */ B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE(:B1, 'DD/MM/RRRR')
  -- [CRITIQUE] Sous-requete DC_MAX dans WHERE - 2eme execution
  AND (SELECT /*+ NO_UNNEST INDEX(E IDX_BRR_TRANS_REC_REF) */ MAX(E.TRANSACTION_DATE)
       FROM BRR_TRANSACTIONS E
       WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
         AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE(:B1, 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'RECONCILED'  -- [OPT] Sans parentheses

ORDER BY SERVICE, SOCIETE, COMPTE_BANCAIRE, DATE_OPERATION_SUSPENS, NETTING;


-- ============================================================
-- PARTIE 3 : RESUME DES MODIFICATIONS
-- ============================================================
/*
MODIFICATIONS APPLIQUEES :
--------------------------

[HINTS]
1. Suppression de optimizer_features_enable('10.2.0.4') - obsolete
2. Ajout LEADING(BRR_TRANSACTIONS BS_ACCTS BA_CPME) - ordre jointure
3. Ajout USE_HASH(BS_ACCTS BA_CPME) - force hash join
4. Ajout NO_MERGE - empeche le merge des sous-requetes
5. Ajout CARDINALITY(BRR_TRANSACTIONS 100000) - aide l'optimiseur
6. Ajout NO_UNNEST sur toutes les sous-requetes scalaires
7. Ajout INDEX(E IDX_BRR_TRANS_REC_REF) sur DC_MAX

[CODE]
1. UNION -> UNION ALL (statuts exclusifs, pas de doublons)
2. Suppression (SELECT ... FROM DUAL) pour ANCIENNETE_J et ANCIENNETE_M
3. Utilisation directe de BA_CPME.METHODE au lieu de sous-requete
4. Suppression des parentheses inutiles autour de STATE = '...'

[INDEX REQUIS]
1. IDX_BRR_TRANS_STATE_DATE sur BR_DATA(STATE, TRANS_DATE)
2. IDX_BRR_TRANS_ACCT_STATE sur BR_DATA(ACCT_ID, STATE)
3. IDX_BRR_TRANS_REC_REF sur BR_DATA(REC_GROUP, ACCT_ID, TRANS_DATE) -- CRITIQUE pour DC_MAX

GAIN ATTENDU :
- UNION ALL : ~10% (evite le tri pour dedoublonnage)
- Hints NO_UNNEST : ~20% (evite transformation couteuse)
- Index REC_REF : ~50% sur DC_MAX (acces direct au lieu de full scan)
- Suppression SELECT FROM DUAL : ~5% (evite context switch)

TOTAL ESTIME : 40-60% de reduction du temps d'execution
*/
