-- ============================================================
-- DTC670 - EXTRACTION SOURCE (Version Originale - Sans CTE)
-- ============================================================
-- SQL_ID : 4v9ag77cam8uu
-- Date : 21/02/2026
-- ============================================================
-- Ce script utilise la REQUETE ORIGINALE (sous-requetes scalaires)
-- pour comparaison avec la version optimisee CTE
-- ============================================================
-- COMPARAISON :
--   - SOURCE  : DTC670_4v9ag77cam8uu_EXTRACTION_SOURCE.sql (ce fichier)
--   - OPTIMISE: DTC670_4v9ag77cam8uu_EXTRACTION_COMPLETE.sql
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 2000
SET PAGESIZE 0
SET TRIMSPOOL ON
SET FEEDBACK OFF
SET HEADING OFF
SET TIMING ON

-- ============================================================
-- SCHEMA : Utiliser le schema EXP_RNAPA pour les synonymes
-- ============================================================
ALTER SESSION SET CURRENT_SCHEMA = EXP_RNAPA;

-- Parametres (MODIFIER selon vos besoins)
DEFINE P_DATE_ARRETE = '28/02/2026'
DEFINE P_TYPE_RAPRO = 'RB'

PROMPT ============================================================
PROMPT DTC670 - EXTRACTION SOURCE (Version Originale)
PROMPT Date arrete : &P_DATE_ARRETE
PROMPT Type rapro  : &P_TYPE_RAPRO
PROMPT ============================================================

-- ============================================================
-- ETAPE 1/4 : TRUNCATE TABLE BA_ATTENDUS_GEST
-- ============================================================
PROMPT [1/4] Truncate BA_ATTENDUS_GEST...
TRUNCATE TABLE BA_ATTENDUS_GEST;

-- ============================================================
-- ETAPE 2/4 : INSERT avec REQUETE ORIGINALE (sous-requetes scalaires)
-- ============================================================
PROMPT [2/4] Insertion donnees ORIGINALES (sous-requetes scalaires)...

INSERT INTO BA_ATTENDUS_GEST (
    DATE_ARRETE, TYPE_RAPRO, SERVICE, SOCIETE, COMPTE_BANCAIRE, LIBELLE_COMPTE,
    DEVISE, DATE_OPERATION_SUSPENS, LIBELLE_SUSPENS, DEBIT, CREDIT, SENS_ATTENDU, COTE_SUSPENS,
    ANCIENNETE_J, ANCIENNETE_M, BORNE_ANCIENNETE, PILIER_MONTANT_DEBIT, PILIER_MONTANT_CREDIT,
    METHODE_PROVISION, TAUX, MONTANT_PROVISION, STATUT, DATE_APUREMENT, DC_MAX, PRIORITE, COMMENTAIRE,
    NETTING, DELTA, SENS_DELTA, NUMERO_FICHE, DERNIER_STATUT, RECORD_ID, ANNOTE_LE
)
-- ============================================================
-- REQUETE ORIGINALE - OUTSTANDING
-- ============================================================
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')) AS DATE_ARRETE,
    (SELECT DECODE(RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2),
        'RB', 'Rapprochement Bancaire',
        'RC', 'Rapprochement de Controle',
        'JC', 'Justification de compte',
        'CL', 'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                FROM BRR_ACCOUNT_HIERARCHIES H
                                WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT B.ACCT_NUM
     FROM BS_ACCTS B
     WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                        FROM BRR_ACCOUNT_HIERARCHIES H
                        WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC',
            'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
            'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = BA_CPME.METHODE
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    NULL AS DATE_APUREMENT,
    NULL AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
        'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = '&P_TYPE_RAPRO'
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'OUTSTANDING'

UNION

-- ============================================================
-- REQUETE ORIGINALE - RECONCILED
-- ============================================================
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')) AS DATE_ARRETE,
    (SELECT DECODE(RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2),
        'RB', 'Rapprochement Bancaire',
        'RC', 'Rapprochement de Controle',
        'JC', 'Justification de compte',
        'CL', 'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                FROM BRR_ACCOUNT_HIERARCHIES H
                                WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT B.ACCT_NUM
     FROM BS_ACCTS B
     WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                        FROM BRR_ACCOUNT_HIERARCHIES H
                        WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC',
            'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
            'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = BA_CPME.METHODE
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    TO_DATE(BRR_TRANSACTIONS.UPDATE_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,
    -- DC_MAX : Sous-requete scalaire (GOULOT D'ETRANGLEMENT - executee par ligne!)
    (SELECT MAX(E.TRANSACTION_DATE)
     FROM BRR_TRANSACTIONS E
     WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
       AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
        'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = '&P_TYPE_RAPRO'
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  -- GOULOT D'ETRANGLEMENT : Cette sous-requete est executee pour CHAQUE ligne!
  AND (SELECT MAX(E.TRANSACTION_DATE)
       FROM BRR_TRANSACTIONS E
       WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
         AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'RECONCILED';

COMMIT;

PROMPT [2/4] Insertion terminee.
SELECT COUNT(*) || ' lignes inserees dans BA_ATTENDUS_GEST (VERSION SOURCE)' FROM BA_ATTENDUS_GEST;

-- ============================================================
-- ETAPE 3/4 : Recalcul NETTING (lignes preletrees)
-- ============================================================
PROMPT [3/4] Recalcul des lignes preletrees (NETTING)...

DECLARE
    v_min_record_id NUMBER;
    v_sum_delta NUMBER;
BEGIN
    FOR rec IN (
        SELECT DISTINCT DATE_ARRETE, TYPE_RAPRO, SERVICE, SOCIETE,
               COMPTE_BANCAIRE, LIBELLE_COMPTE, DEVISE, NETTING
        FROM BA_ATTENDUS_GEST
        WHERE NETTING != 0
        ORDER BY SOCIETE, COMPTE_BANCAIRE, DEVISE
    ) LOOP
        SELECT MIN(RECORD_ID) INTO v_min_record_id
        FROM BA_ATTENDUS_GEST
        WHERE DATE_ARRETE = rec.DATE_ARRETE
          AND SOCIETE = rec.SOCIETE
          AND COMPTE_BANCAIRE = rec.COMPTE_BANCAIRE
          AND DEVISE = rec.DEVISE
          AND NETTING = rec.NETTING;

        SELECT SUM(DELTA) INTO v_sum_delta
        FROM BA_ATTENDUS_GEST
        WHERE DATE_ARRETE = rec.DATE_ARRETE
          AND SOCIETE = rec.SOCIETE
          AND COMPTE_BANCAIRE = rec.COMPTE_BANCAIRE
          AND DEVISE = rec.DEVISE
          AND NETTING = rec.NETTING;

        UPDATE BA_ATTENDUS_GEST
        SET DELTA = v_sum_delta, TAUX = 0, MONTANT_PROVISION = 0
        WHERE RECORD_ID = v_min_record_id;

        UPDATE BA_ATTENDUS_GEST
        SET DELTA = 0, TAUX = 0, MONTANT_PROVISION = 0
        WHERE DATE_ARRETE = rec.DATE_ARRETE
          AND SOCIETE = rec.SOCIETE
          AND COMPTE_BANCAIRE = rec.COMPTE_BANCAIRE
          AND DEVISE = rec.DEVISE
          AND NETTING = rec.NETTING
          AND RECORD_ID != v_min_record_id;
    END LOOP;
    COMMIT;
END;
/

PROMPT [3/4] Recalcul NETTING termine.

-- ============================================================
-- ETAPE 4/4 : EXPORT CSV
-- ============================================================
PROMPT [4/4] Generation du fichier CSV...

COLUMN filename NEW_VALUE output_file
SELECT 'ACCURATE_A' || TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), 'YYYY') ||
       '_M' || TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), 'MM') ||
       '_J' || TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), 'DD') ||
       '_' || TO_CHAR(SYSDATE, 'DD-MM-YYYY') ||
       '_&P_TYPE_RAPRO._BAATGS_SOURCE.txt' AS filename
FROM DUAL;

SPOOL /tmp/&output_file

SELECT 'DATE_ARRETE,TYPE_RAPRO,SERVICE,SOCIETE,COMPTE_BANCAIRE,LIBELLE_COMPTE,' ||
       'DEVISE,DATE_OPERATION_SUSPENS,LIBELLE_SUSPENS,DEBIT,CREDIT,CUMUL_DEBIT_CREDIT,SENS_ATTENDU,' ||
       'COTE_SUSPENS,ANCIENNETE_J,BORNE_ANCIENNETE,PILIER_MONTANT_DEBIT,PILIER_MONTANT_CREDIT,PILIER_MONTANT_CUMUL_DEBIT_CREDIT,' ||
       'METHODE_PROVISION,NETTING,DELTA,SENS_DELTA,ID_ECRITURE,TAUX,' ||
       'MONTANT_PROVISION,DATE_APUREMENT,POST_ARRETE_DC_MAX,PRIORITE,COMMENTAIRE,NUMERO_FICHE,DERNIER_STATUT,RECORD_ID,ANNOTE_LE'
FROM DUAL;

SELECT
    DATE_ARRETE || ',' ||
    TYPE_RAPRO || ',' ||
    SERVICE || ',' ||
    REPLACE(SOCIETE, ',', ' ') || ',' ||
    COMPTE_BANCAIRE || ',' ||
    REPLACE(LIBELLE_COMPTE, ',', ' ') || ',' ||
    DEVISE || ',' ||
    DATE_OPERATION_SUSPENS || ',' ||
    REPLACE(REPLACE(REPLACE(LIBELLE_SUSPENS, ',', ' '), CHR(10), '-'), CHR(13), '') || ',' ||
    NVL(TO_CHAR(DEBIT), '') || ',' ||
    NVL(TO_CHAR(CREDIT), '') || ',' ||
    NVL(TO_CHAR(NVL(DEBIT, CREDIT)), '') || ',' ||
    SENS_ATTENDU || ',' ||
    COTE_SUSPENS || ',' ||
    ANCIENNETE_J || ',' ||
    BORNE_ANCIENNETE || ',' ||
    PILIER_MONTANT_DEBIT || ',' ||
    PILIER_MONTANT_CREDIT || ',' ||
    NVL(PILIER_MONTANT_DEBIT, PILIER_MONTANT_CREDIT) || ',' ||
    METHODE_PROVISION || ',' ||
    NETTING || ',' ||
    CASE WHEN DELTA != 0 THEN REPLACE(TO_CHAR(DELTA), '.', ',') ELSE '-' END || ',' ||
    SENS_DELTA || ',' ||
    RECORD_ID || ',' ||
    CASE WHEN TAUX != 0 THEN TO_CHAR(TAUX*100) || '%' ELSE '-' END || ',' ||
    CASE WHEN MONTANT_PROVISION != 0 THEN REPLACE(TO_CHAR(MONTANT_PROVISION), '.', ',') ELSE '-' END || ',' ||
    NVL(TO_CHAR(DATE_APUREMENT), '') || ',' ||
    NVL(TO_CHAR(DC_MAX, 'DD/MM/RRRR'), '') || ',' ||
    PRIORITE || ',' ||
    REPLACE(REPLACE(REPLACE(COMMENTAIRE, ',', ' '), CHR(10), '-'), CHR(13), '') || ',' ||
    NUMERO_FICHE || ',' ||
    DERNIER_STATUT || ',' ||
    RECORD_ID || ',' ||
    ANNOTE_LE
FROM BA_ATTENDUS_GEST
ORDER BY SERVICE, SOCIETE, COMPTE_BANCAIRE, TO_DATE(DATE_OPERATION_SUSPENS, 'DD/MM/RRRR'), NETTING;

SPOOL OFF

PROMPT
PROMPT ============================================================
PROMPT EXTRACTION SOURCE TERMINEE
PROMPT Fichier genere : /tmp/&output_file
PROMPT ============================================================
PROMPT
PROMPT ATTENTION : Cette version utilise les sous-requetes scalaires
PROMPT             et sera BEAUCOUP plus lente que la version CTE !
PROMPT ============================================================

SET TIMING OFF
SET FEEDBACK ON
SET HEADING ON
