-- ============================================================
-- REQUETE SOURCE - DTC 671
-- SQL_ID : 7prpuy907rpz2
-- Curseur : Curseur_Attendus_DC_Max (PKG_RNADEXTAUTO01)
-- Date extraction : 20/02/2026
-- Parametres : :B1 = date_arrete (28/02/2026), :B2 = type_rapro (RB)
-- ============================================================
-- COMPARAISON AVEC DTC670 (4v9ag77cam8uu) :
-- -> FONCTIONNELLEMENT IDENTIQUE
-- -> Difference = espaces/formatage dans le SQL_TEXT
-- -> Oracle genere un SQL_ID different car le hash du texte change
-- ============================================================

SELECT /*+  optimizer_features_enable('10.2.0.4') */ DISTINCT
    (SELECT TO_CHAR(:B1 ) FROM DUAL) AS DATE_ARRETE,
    (SELECT DECODE(RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2),
        'RB',  'Rapprochement Bancaire',
        'RC',  'Rapprochement de Contrôle',
        'JC',  'Justification de compte',
        'CL',  'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                FROM BRR_ACCOUNT_HIERARCHIES H
                                WHERE H.ACCOUNT_ID =BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT B.ACCT_NUM
     FROM BS_ACCTS B
     WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                        FROM BRR_ACCOUNT_HIERARCHIES H
                        WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'RECEIPTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'PAYMENTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO,  0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC',
            'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
            'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE, 'STATEMENT',  'B', 'CASHBOOK',  'C') AS COTE_SUSPENS,
    (SELECT TO_DATE(:B1 ,  'DD/MM/RRRR') - TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR') FROM DUAL) AS ANCIENNETE_J,
    (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) >= BACA.BORNE_INF
       AND (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP) ,
        'RECEIPTCASHBOOK',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP) ,
        'PAYMENTCASHBOOK',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID)
       AND (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) >= MEPR.BORNE_INF
       AND (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    NULL AS DATE_APUREMENT,
    NULL AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN,  1, 5) AS PRIORITE ,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT),
        NULL,  DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'PAYMENTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
        'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED,  'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = :B2
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE(:B1 ,  'DD/MM/RRRR')
  AND (BRR_TRANSACTIONS.STATE='OUTSTANDING')

UNION

SELECT /*+  optimizer_features_enable('10.2.0.4') */ DISTINCT
    (SELECT TO_CHAR(:B1 ) FROM DUAL) AS DATE_ARRETE,
    (SELECT DECODE(RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2),
        'RB',  'Rapprochement Bancaire',
        'RC',  'Rapprochement de Contrôle',
        'JC',  'Justification de compte',
        'CL',  'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                FROM BRR_ACCOUNT_HIERARCHIES H
                                WHERE H.ACCOUNT_ID =BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT B.ACCT_NUM
     FROM BS_ACCTS B
     WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                        FROM BRR_ACCOUNT_HIERARCHIES H
                        WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR') AS DATE_OPERATION,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'RECEIPTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT,
        'PAYMENTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO,  0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC',
            'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
            'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE, 'STATEMENT',  'B', 'CASHBOOK',  'C') AS COTE_SUSPENS,
    (SELECT TO_DATE(:B1 ,  'DD/MM/RRRR') - TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR') FROM DUAL) AS ANCIENNETE_J,
    (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) >= BACA.BORNE_INF
       AND (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP) ,
        'RECEIPTCASHBOOK',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP) ,
        'PAYMENTCASHBOOK',  (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID)
       AND (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) >= MEPR.BORNE_INF
       AND (SELECT MONTHS_BETWEEN(TO_DATE(:B1 ,  'DD/MM/RRRR'),  TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE,  'DD/MM/RRRR')) FROM DUAL) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    TO_DATE(BRR_TRANSACTIONS.UPDATE_TIME,  'DD/MM/RRRR') AS DATE_APUREMENT,
    (SELECT MAX(E.TRANSACTION_DATE)
     FROM BRR_TRANSACTIONS E
     WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
       AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN,  1, 5) AS PRIORITE ,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT),
        NULL,  DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'RECEIPTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'PAYMENTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
            'PAYMENTSTATEMENT', BRR_TRANSACTIONS.AMOUNT, 'RECEIPTCASHBOOK',  BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C',
        'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED,  'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS ,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = :B2
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE(:B1 ,  'DD/MM/RRRR')
  AND (SELECT MAX(E.TRANSACTION_DATE)
       FROM BRR_TRANSACTIONS E
       WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
         AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE(:B1 ,  'DD/MM/RRRR')
  AND (BRR_TRANSACTIONS.STATE='RECONCILED')

ORDER BY SERVICE,  SOCIETE,  COMPTE_BANCAIRE,  DATE_OPERATION_SUSPENS,  NETTING;
