-- ============================================================
-- DTC670 - REQUETE CTE COMPLETE STANDALONE
-- ============================================================
-- SQL_ID : 4v9ag77cam8uu
-- Date : 20/02/2026
-- ============================================================
-- VERSION : Optimisation COMPLETE avec CTE
-- GAIN ATTENDU : 80-90% de reduction du temps d'execution
-- ============================================================
-- USAGE : Executer directement dans SQL*Plus ou SQL Developer
--         Les parametres seront demandes a l'execution
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 300
SET PAGESIZE 1000
SET TIMING ON

-- Parametres (modifier selon vos besoins)
DEFINE P_DATE_ARRETE = '28/02/2026'
DEFINE P_TYPE_RAPRO = 'RB'

PROMPT ============================================================
PROMPT DTC670 - REQUETE CTE COMPLETE STANDALONE
PROMPT Date arrete : &P_DATE_ARRETE
PROMPT Type rapro  : &P_TYPE_RAPRO
PROMPT ============================================================
PROMPT

-- ============================================================
-- REQUETE OPTIMISEE COMPLETE AVEC CTE
-- ============================================================
-- Optimisations appliquees :
--   1. CTE dc_max_calc : Calcul DC_MAX UNE SEULE FOIS
--   2. CTE compte_hierarchie : Factorisation hierarchie comptes
--   3. UNION ALL au lieu de UNION (statuts exclusifs)
--   4. Hints LEADING + USE_HASH + MATERIALIZE
--   5. Jointures ANSI explicites
-- ============================================================

WITH
-- CTE 1 : Pre-calcul DC_MAX (UNE SEULE FOIS pour toutes les transactions)
-- IMPORTANT: Pas de filtre STATE pour etre 100% equivalent a l'original
dc_max_calc AS (
    SELECT /*+ MATERIALIZE */
        RECONCILIATION_REFERENCE,
        ACCOUNT_ID,
        MAX(TRANSACTION_DATE) AS DC_MAX
    FROM BRR_TRANSACTIONS
    WHERE RECONCILIATION_REFERENCE IS NOT NULL
    GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
),
-- CTE 2 : Hierarchie des comptes (evite sous-requetes repetees)
compte_hierarchie AS (
    SELECT /*+ MATERIALIZE */
        H.ACCOUNT_ID,
        H.LEVEL_02_ACCOUNT_ID,
        H.LEVEL_03_ACCOUNT_ID,
        B2.ACCT_NUM AS SERVICE,
        RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE,
        DECODE(RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Controle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison') AS TYPE_RAPRO
    FROM BRR_ACCOUNT_HIERARCHIES H
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
)
-- ============================================================
-- PARTIE OUTSTANDING
-- ============================================================
SELECT /*+ LEADING(T A CH CM) USE_HASH(A CH CM) */ DISTINCT
    TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')) AS DATE_ARRETE,
    CH.TYPE_RAPRO AS TYPE_RAPRO,
    CH.SERVICE AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
    CM.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    A.ACCT_NAME AS LIBELLE_COMPTE,
    A.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(T.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    T.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT) AS DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT) AS CREDIT,
    DECODE(T.NUMERIC_TWO, 0,
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC', 'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||T.FLAG_C||DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')
    ) AS SENS_ATTENDU,
    DECODE(T.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR') - T.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE
     WHERE MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_CREDIT,
    CM.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION
     WHERE METHODE = CM.METHODE
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    T.STATE AS STATUT,
    NULL AS DATE_APUREMENT,
    NULL AS DC_MAX,
    SUBSTR(T.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    T.LAST_NOTE_TEXT AS COMMENTAIRE,
    T.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT),
        NULL, DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT),
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT)
    ) AS DELTA,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    T.RECORD_ID AS ID_ECRITURE,
    CASE T.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(T.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS T
JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
WHERE CH.TYPE_RAPRO_CODE = '&P_TYPE_RAPRO'
  AND CH.SERVICE = 'GESTION'
  AND T.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND T.STATE = 'OUTSTANDING'

UNION ALL  -- UNION ALL car OUTSTANDING et RECONCILED sont mutuellement exclusifs

-- ============================================================
-- PARTIE RECONCILED (avec DC_MAX pre-calcule)
-- ============================================================
SELECT /*+ LEADING(T A CH CM DCM) USE_HASH(A CH CM DCM) */ DISTINCT
    TO_CHAR(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')) AS DATE_ARRETE,
    CH.TYPE_RAPRO AS TYPE_RAPRO,
    CH.SERVICE AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
    CM.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    A.ACCT_NAME AS LIBELLE_COMPTE,
    A.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(T.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    T.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT) AS DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT) AS CREDIT,
    DECODE(T.NUMERIC_TWO, 0,
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC', 'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||T.FLAG_C||DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')
    ) AS SENS_ATTENDU,
    DECODE(T.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR') - T.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE
     WHERE MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_CREDIT,
    CM.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION
     WHERE METHODE = CM.METHODE
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    T.STATE AS STATUT,
    TO_DATE(T.UPDATE_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,
    DCM.DC_MAX AS DC_MAX,  -- DC_MAX depuis le CTE (calcule UNE SEULE FOIS)
    SUBSTR(T.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    T.LAST_NOTE_TEXT AS COMMENTAIRE,
    T.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT),
        NULL, DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT),
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT)
    ) AS DELTA,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    T.RECORD_ID AS ID_ECRITURE,
    CASE T.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(T.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS T
JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
JOIN dc_max_calc DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
                     AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
WHERE CH.TYPE_RAPRO_CODE = '&P_TYPE_RAPRO'
  AND CH.SERVICE = 'GESTION'
  AND T.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND T.STATE = 'RECONCILED'
  AND DCM.DC_MAX >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')  -- Filtre sur DC_MAX pre-calcule

ORDER BY SERVICE, SOCIETE, COMPTE_BANCAIRE, DATE_OPERATION_SUSPENS, NETTING;

PROMPT
PROMPT ============================================================
PROMPT FIN EXECUTION DTC670 CTE STANDALONE
PROMPT ============================================================

SET TIMING OFF

/*
============================================================
RESUME DES OPTIMISATIONS
============================================================

AVANT (Original) :
- DC_MAX calcule 2 fois par ligne via sous-requete correlee
- Sous-requetes hierarchie repetees pour chaque ligne
- UNION avec tri et dedoublonnage
- Hint optimizer_features_enable('10.2.0.4')

APRES (Optimise CTE) :
- DC_MAX calcule UNE SEULE FOIS dans CTE dc_max_calc
- Hierarchie pre-calculee dans CTE compte_hierarchie
- UNION ALL (pas de tri car statuts mutuellement exclusifs)
- Jointures ANSI explicites
- Hints LEADING + USE_HASH + MATERIALIZE

GAIN ATTENDU : 80-90% de reduction du temps d'execution

============================================================
FICHIERS ASSOCIES
============================================================
- DTC670_CTE_STANDALONE.sql        : Cette requete standalone
- DTC670_4v9ag77cam8uu_OPTIMISE.sql: Version minimale (hints seulement)
- PKG_RNADEXTAUTO01_DEPLOY_FULL.sql: Package complet avec CTE
- VERIFICATION_DTC670_FULL_OPTIM.sql: Script de verification
============================================================
*/
