-- ============================================================
-- TEMPLATE MIGRATION COMPTE CTL vers EUR
-- ============================================================
-- Date : 24/02/2026 (MAJ modele)
-- Usage : Migration compte BBNP*****-EUR-CTL vers BBNP*****-EUR
-- ============================================================
-- ETAPES :
--   1. DELETE balises du compte CTL
--   2. UPDATE TA_RN_GESTION_ACCURATE (bascule CTL -> EUR)
--   3. INSERT balises GEST sur le compte EUR (modele BBNP85504-EUR)
-- ============================================================

SET SERVEROUTPUT ON
SET LINESIZE 200
SET PAGESIZE 100

-- ============================================================
-- VARIABLES A MODIFIER
-- ============================================================
DEFINE COMPTE_CTL = 'BBNP95204-EUR-CTL'
DEFINE COMPTE_EUR = 'BBNP95204-EUR'
DEFINE COMPTE_MODELE = 'BBNP85504-EUR'

-- ============================================================
-- ETAPE 0 : VERIFICATION DES COMPTES
-- ============================================================
PROMPT ============================================================
PROMPT [0/3] VERIFICATION EXISTENCE DES COMPTES
PROMPT ============================================================

PROMPT
PROMPT Compte CTL (a supprimer les balises) :
SELECT ID_COMPTE_ACCURATE, NUM_COMPTE_ACCURATE, NOM, FLAG_ACTIF, TYPE_RAPPRO
FROM TA_RN_COMPTE_ACCURATE
WHERE NUM_COMPTE_ACCURATE = '&COMPTE_CTL';

PROMPT
PROMPT Compte EUR (cible) :
SELECT ID_COMPTE_ACCURATE, NUM_COMPTE_ACCURATE, NOM, FLAG_ACTIF, TYPE_RAPPRO
FROM TA_RN_COMPTE_ACCURATE
WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR';

PROMPT
PROMPT Compte MODELE (source balises) :
SELECT ID_COMPTE_ACCURATE, NUM_COMPTE_ACCURATE, NOM, FLAG_ACTIF, TYPE_RAPPRO
FROM TA_RN_COMPTE_ACCURATE
WHERE NUM_COMPTE_ACCURATE = '&COMPTE_MODELE';

-- ############################################################
-- ETAPE 1 : DELETE BALISES DU COMPTE CTL
-- ############################################################
PROMPT
PROMPT ============================================================
PROMPT [1/3] DELETE BALISES DU COMPTE CTL
PROMPT ============================================================

-- 1.1 VERIFICATION : Balises actuelles du compte CTL (ce qui sera supprime)
PROMPT
PROMPT [1.1] Balises ACTUELLES de &COMPTE_CTL (a supprimer) :
SELECT
    CA.NUM_COMPTE_ACCURATE,
    BPC.NUM_COL_FEEDER,
    B.NOM_BALISE,
    B.TYPE_BALISE,
    BPC.INDICATEUR_MANUEL_AUTO
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
JOIN TA_RN_BALISE B ON B.ID_BALISE = BPC.ID_BALISE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_CTL'
ORDER BY BPC.NUM_COL_FEEDER;

PROMPT
PROMPT [1.2] Nombre de balises a supprimer :
SELECT COUNT(*) AS NB_BALISES_A_SUPPRIMER
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_CTL';

-- 1.3 DELETE (decommenter pour executer)
/*
PROMPT
PROMPT [1.3] Execution DELETE...
DELETE FROM TA_RN_BALISE_PAR_COMPTE
WHERE ID_COMPTE_ACCURATE IN (
    SELECT ID_COMPTE_ACCURATE
    FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_CTL'
);

PROMPT Lignes supprimees :
SELECT SQL%ROWCOUNT || ' balises supprimees de &COMPTE_CTL' FROM DUAL;
*/

-- ############################################################
-- ETAPE 2 : UPDATE TA_RN_GESTION_ACCURATE (CTL -> EUR)
-- ############################################################
PROMPT
PROMPT ============================================================
PROMPT [2/3] UPDATE TA_RN_GESTION_ACCURATE (bascule CTL -> EUR)
PROMPT ============================================================

-- 2.1 VERIFICATION : Donnees actuelles dans TA_RN_GESTION_ACCURATE pour CTL
PROMPT
PROMPT [2.1] Donnees ACTUELLES dans TA_RN_GESTION_ACCURATE pour &COMPTE_CTL :
SELECT
    GA.*,
    CA.NUM_COMPTE_ACCURATE
FROM TA_RN_GESTION_ACCURATE GA
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_CTL';

PROMPT
PROMPT [2.2] Nombre de lignes a mettre a jour :
SELECT COUNT(*) AS NB_LIGNES_A_UPDATE
FROM TA_RN_GESTION_ACCURATE GA
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_CTL';

-- 2.3 UPDATE (decommenter pour executer)
/*
PROMPT
PROMPT [2.3] Execution UPDATE...
UPDATE TA_RN_GESTION_ACCURATE
SET ID_COMPTE_ACCURATE = (
    SELECT ID_COMPTE_ACCURATE
    FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
)
WHERE ID_COMPTE_ACCURATE = (
    SELECT ID_COMPTE_ACCURATE
    FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_CTL'
);

PROMPT Lignes mises a jour :
SELECT SQL%ROWCOUNT || ' lignes basculees de &COMPTE_CTL vers &COMPTE_EUR' FROM DUAL;
*/

-- 2.4 VERIFICATION POST-UPDATE
/*
PROMPT
PROMPT [2.4] Verification POST-UPDATE - Donnees maintenant sur &COMPTE_EUR :
SELECT
    GA.*,
    CA.NUM_COMPTE_ACCURATE
FROM TA_RN_GESTION_ACCURATE GA
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_EUR';
*/

-- ############################################################
-- ETAPE 3 : INSERT BALISES GEST SUR COMPTE EUR
-- ############################################################
PROMPT
PROMPT ============================================================
PROMPT [3/3] INSERT BALISES GEST sur &COMPTE_EUR
PROMPT ============================================================

-- 3.1 VERIFICATION : Balises actuelles du compte EUR (avant insertion)
PROMPT
PROMPT [3.1] Balises ACTUELLES de &COMPTE_EUR (GEST) :
SELECT
    CA.NUM_COMPTE_ACCURATE,
    BPC.NUM_COL_FEEDER,
    B.NOM_BALISE,
    B.TYPE_BALISE,
    BPC.INDICATEUR_MANUEL_AUTO
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
JOIN TA_RN_BALISE B ON B.ID_BALISE = BPC.ID_BALISE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
  AND B.TYPE_BALISE = 'GEST'
ORDER BY BPC.NUM_COL_FEEDER;

-- 3.2 VERIFICATION : Balises du compte MODELE (ce qui sera copie)
PROMPT
PROMPT [3.2] Balises MODELE &COMPTE_MODELE (a copier) :
SELECT
    CA.NUM_COMPTE_ACCURATE,
    BPC.NUM_COL_FEEDER,
    B.NOM_BALISE,
    B.TYPE_BALISE,
    BPC.INDICATEUR_MANUEL_AUTO
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
JOIN TA_RN_BALISE B ON B.ID_BALISE = BPC.ID_BALISE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_MODELE'
  AND B.TYPE_BALISE = 'GEST'
ORDER BY BPC.NUM_COL_FEEDER;

-- 3.3 PREVIEW des lignes qui seront inserees
PROMPT
PROMPT [3.3] PREVIEW - Lignes qui seront inserees :
SELECT
    '&COMPTE_EUR' AS COMPTE_CIBLE,
    BalRef.NUM_COL_FEEDER,
    B.NOM_BALISE,
    BalRef.INDICATEUR_MANUEL_AUTO,
    'A INSERER' AS ACTION
FROM TA_RN_BALISE_PAR_COMPTE BalRef
JOIN TA_RN_BALISE B ON B.ID_BALISE = BalRef.ID_BALISE
LEFT JOIN TA_RN_BALISE_PAR_COMPTE Balise1
    ON Balise1.NUM_COL_FEEDER = BalRef.NUM_COL_FEEDER
    AND Balise1.ID_BALISE = BalRef.ID_BALISE
    AND Balise1.INDICATEUR_MANUEL_AUTO = BalRef.INDICATEUR_MANUEL_AUTO
    AND Balise1.ID_COMPTE_ACCURATE IN (
        SELECT ID_COMPTE_ACCURATE FROM TA_RN_COMPTE_ACCURATE
        WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
    )
WHERE BalRef.ID_COMPTE_ACCURATE IN (
    SELECT ID_COMPTE_ACCURATE FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_MODELE'
)
AND BalRef.ID_BALISE IN (
    SELECT ID_BALISE FROM TA_RN_BALISE WHERE TYPE_BALISE = 'GEST'
)
AND Balise1.NUM_COL_FEEDER IS NULL
ORDER BY BalRef.NUM_COL_FEEDER;

-- 3.4 INSERT (decommenter pour executer)
/*
PROMPT
PROMPT [3.4] Execution INSERT...
INSERT INTO TA_RN_BALISE_PAR_COMPTE (
    ID_COMPTE_ACCURATE,
    NUM_COL_FEEDER,
    ID_BALISE,
    INDICATEUR_MANUEL_AUTO
)
SELECT
    (SELECT ID_COMPTE_ACCURATE FROM TA_RN_COMPTE_ACCURATE
     WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR') AS ID_COMPTE_ACCURATE,
    BalRef.NUM_COL_FEEDER,
    BalRef.ID_BALISE,
    BalRef.INDICATEUR_MANUEL_AUTO
FROM TA_RN_BALISE_PAR_COMPTE BalRef
LEFT JOIN TA_RN_BALISE_PAR_COMPTE Balise1
    ON Balise1.NUM_COL_FEEDER = BalRef.NUM_COL_FEEDER
    AND Balise1.ID_BALISE = BalRef.ID_BALISE
    AND Balise1.INDICATEUR_MANUEL_AUTO = BalRef.INDICATEUR_MANUEL_AUTO
    AND Balise1.ID_COMPTE_ACCURATE IN (
        SELECT ID_COMPTE_ACCURATE FROM TA_RN_COMPTE_ACCURATE
        WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
    )
WHERE BalRef.ID_COMPTE_ACCURATE IN (
    SELECT ID_COMPTE_ACCURATE FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_MODELE'
)
AND BalRef.ID_BALISE IN (
    SELECT ID_BALISE FROM TA_RN_BALISE WHERE TYPE_BALISE = 'GEST'
)
AND Balise1.NUM_COL_FEEDER IS NULL;

PROMPT Lignes inserees :
SELECT SQL%ROWCOUNT || ' balises inserees pour &COMPTE_EUR' FROM DUAL;

COMMIT;
*/

-- ############################################################
-- VERIFICATION FINALE
-- ############################################################
/*
PROMPT
PROMPT ============================================================
PROMPT VERIFICATION FINALE
PROMPT ============================================================

PROMPT
PROMPT Balises finales de &COMPTE_EUR :
SELECT
    CA.NUM_COMPTE_ACCURATE,
    BPC.NUM_COL_FEEDER,
    B.NOM_BALISE,
    B.TYPE_BALISE,
    BPC.INDICATEUR_MANUEL_AUTO
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
JOIN TA_RN_BALISE B ON B.ID_BALISE = BPC.ID_BALISE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
ORDER BY BPC.NUM_COL_FEEDER;

PROMPT
PROMPT Comparaison nombre de balises GEST :
SELECT '&COMPTE_EUR' AS COMPTE, COUNT(*) AS NB_BALISES_GEST
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
JOIN TA_RN_BALISE B ON B.ID_BALISE = BPC.ID_BALISE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_EUR' AND B.TYPE_BALISE = 'GEST'
UNION ALL
SELECT '&COMPTE_MODELE' AS COMPTE, COUNT(*) AS NB_BALISES_GEST
FROM TA_RN_BALISE_PAR_COMPTE BPC
JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = BPC.ID_COMPTE_ACCURATE
JOIN TA_RN_BALISE B ON B.ID_BALISE = BPC.ID_BALISE
WHERE CA.NUM_COMPTE_ACCURATE = '&COMPTE_MODELE' AND B.TYPE_BALISE = 'GEST';
*/

-- ############################################################
-- ROLLBACK COMPLET (en cas de probleme)
-- ############################################################
/*
PROMPT
PROMPT ============================================================
PROMPT ROLLBACK COMPLET
PROMPT ============================================================

-- Rollback INSERT (supprimer balises GEST du compte EUR)
DELETE FROM TA_RN_BALISE_PAR_COMPTE
WHERE ID_COMPTE_ACCURATE IN (
    SELECT ID_COMPTE_ACCURATE FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
)
AND ID_BALISE IN (
    SELECT ID_BALISE FROM TA_RN_BALISE WHERE TYPE_BALISE = 'GEST'
);

-- Rollback UPDATE (rebascule EUR -> CTL)
UPDATE TA_RN_GESTION_ACCURATE
SET ID_COMPTE_ACCURATE = (
    SELECT ID_COMPTE_ACCURATE
    FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_CTL'
)
WHERE ID_COMPTE_ACCURATE = (
    SELECT ID_COMPTE_ACCURATE
    FROM TA_RN_COMPTE_ACCURATE
    WHERE NUM_COMPTE_ACCURATE = '&COMPTE_EUR'
);

COMMIT;
PROMPT Rollback termine.
*/
