-- ============================================================
-- PKG_RNADEXTAUTO01 - VERSION OPTIMISEE COMPLETE
-- Date : 20/02/2026
-- SQL_ID : 4v9ag77cam8uu (DTC670)
-- ============================================================
-- OPTIMISATION COMPLETE :
--   1. CTE dc_max_calc : Calcul DC_MAX UNE SEULE FOIS
--   2. CTE compte_hierarchie : Factorise les jointures hierarchie
--   3. UNION ALL au lieu de UNION
--   4. Hints optimises
-- ============================================================
-- GAIN ATTENDU : 80-90% de reduction du temps d'execution
-- ============================================================

-- ============================================================
-- CURSEUR OPTIMISE COMPLET - Remplace Curseur_Attendus_DC_Max
-- ============================================================
-- A INSERER dans le package PKG_RNADEXTAUTO01 (lignes 471-629)
-- ============================================================

CURSOR Curseur_Attendus_DC_Max IS
WITH
-- CTE 1 : Pre-calcul DC_MAX (UNE SEULE FOIS pour toutes les transactions)
-- IMPORTANT: Pas de filtre STATE pour etre 100% equivalent a l'original
dc_max_calc AS (
    SELECT /*+ MATERIALIZE */
        RECONCILIATION_REFERENCE,
        ACCOUNT_ID,
        MAX(TRANSACTION_DATE) AS DC_MAX
    FROM BRR_TRANSACTIONS
    WHERE RECONCILIATION_REFERENCE IS NOT NULL
    GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
),
-- CTE 2 : Hierarchie des comptes (evite sous-requetes repetees)
compte_hierarchie AS (
    SELECT /*+ MATERIALIZE */
        H.ACCOUNT_ID,
        H.LEVEL_02_ACCOUNT_ID,
        H.LEVEL_03_ACCOUNT_ID,
        B2.ACCT_NUM AS SERVICE,
        RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE,
        DECODE(RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Contrôle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison') AS TYPE_RAPRO
    FROM BRR_ACCOUNT_HIERARCHIES H
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
)
-- Requete principale OUTSTANDING
SELECT /*+ LEADING(T A CH CM) USE_HASH(A CH CM) */ DISTINCT
    TO_CHAR(s_DateArrete) AS DATE_ARRETE,
    CH.TYPE_RAPRO AS TYPE_RAPRO,
    CH.SERVICE AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
    CM.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    A.ACCT_NAME AS LIBELLE_COMPTE,
    A.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(T.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    T.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT) AS DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT) AS CREDIT,
    DECODE(T.NUMERIC_TWO, 0,
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC', 'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||T.FLAG_C||DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')
    ) AS SENS_ATTENDU,
    DECODE(T.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE(s_DateArrete, 'DD/MM/RRRR') - T.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE
     WHERE MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_CREDIT,
    CM.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION
     WHERE METHODE = CM.METHODE
       AND MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    T.STATE AS STATUT,
    NULL AS DATE_APUREMENT,
    NULL AS DC_MAX,
    SUBSTR(T.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    T.LAST_NOTE_TEXT AS COMMENTAIRE,
    T.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT),
        NULL, DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT),
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT)
    ) AS DELTA,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    T.RECORD_ID AS ID_ECRITURE,
    CASE T.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(T.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS T
JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
WHERE CH.TYPE_RAPRO_CODE = s_TypeRapro
  AND CH.SERVICE = 'GESTION'
  AND T.TRANSACTION_DATE <= TO_DATE(s_DateArrete, 'DD/MM/RRRR')
  AND T.STATE = 'OUTSTANDING'

UNION ALL  -- UNION ALL car OUTSTANDING et RECONCILED sont mutuellement exclusifs

-- Requete principale RECONCILED (avec DC_MAX pre-calcule)
SELECT /*+ LEADING(T A CH CM DCM) USE_HASH(A CH CM DCM) */ DISTINCT
    TO_CHAR(s_DateArrete) AS DATE_ARRETE,
    CH.TYPE_RAPRO AS TYPE_RAPRO,
    CH.SERVICE AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
    CM.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    A.ACCT_NAME AS LIBELLE_COMPTE,
    A.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(T.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    T.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT) AS DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT) AS CREDIT,
    DECODE(T.NUMERIC_TWO, 0,
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC', 'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
        'A'||T.FLAG_C||DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')
    ) AS SENS_ATTENDU,
    DECODE(T.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE(s_DateArrete, 'DD/MM/RRRR') - T.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE
     WHERE MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_DEBIT,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS WHERE T.AMOUNT >= BORNE_INF AND T.AMOUNT < BORNE_SUP)
    ) AS PILIER_MONTANT_CREDIT,
    CM.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION
     WHERE METHODE = CM.METHODE
       AND MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) >= BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE(s_DateArrete, 'DD/MM/RRRR'), T.TRANSACTION_DATE) < BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    T.STATE AS STATUT,
    TO_DATE(T.UPDATE_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,
    DCM.DC_MAX AS DC_MAX,  -- DC_MAX depuis le CTE (calcule UNE SEULE FOIS)
    SUBSTR(T.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    T.LAST_NOTE_TEXT AS COMMENTAIRE,
    T.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT),
        NULL, DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT),
        DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT)
    ) AS DELTA,
    DECODE(T.PAYMENT_OR_RECEIPT||T.SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    T.RECORD_ID AS ID_ECRITURE,
    CASE T.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(T.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS T
JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
JOIN dc_max_calc DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
                     AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
WHERE CH.TYPE_RAPRO_CODE = s_TypeRapro
  AND CH.SERVICE = 'GESTION'
  AND T.TRANSACTION_DATE <= TO_DATE(s_DateArrete, 'DD/MM/RRRR')
  AND T.STATE = 'RECONCILED'
  AND DCM.DC_MAX >= TO_DATE(s_DateArrete, 'DD/MM/RRRR')  -- Filtre sur DC_MAX pre-calcule

ORDER BY SERVICE, SOCIETE, COMPTE_BANCAIRE, DATE_OPERATION_SUSPENS, NETTING;


-- ============================================================
-- RESUME DES OPTIMISATIONS
-- ============================================================
/*
AVANT (Original) :
- DC_MAX calcule 2 fois par ligne (SELECT + WHERE) via sous-requete correlee
- Sous-requetes hierarchie repetees pour chaque ligne
- UNION avec tri et dedoublonnage

APRES (Optimise) :
- DC_MAX calcule UNE SEULE FOIS dans CTE dc_max_calc
- Hierarchie pre-calculee dans CTE compte_hierarchie
- UNION ALL (pas de tri)
- Jointures ANSI explicites
- Hints LEADING + USE_HASH

GAIN ATTENDU : 80-90% de reduction du temps d'execution
RISQUE : Necessite tests approfondis avant deploiement
*/
