-- ============================================================
-- Requete Base des Attendus Gestion (BAATGS)
-- Sql_id : 7prpuy907rpz2
-- Date : 18/02/2026
-- Parametres : DATE_ARRETE = 28/02/2026, TYPE = RB
-- ============================================================

-- Requete OUTSTANDING (suspens en cours)
SELECT /*+  optimizer_features_enable('10.2.0.4') */ DISTINCT
    '28/02/2026' AS DATE_ARRETE,
    (SELECT DECODE(RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2),
        'RB', 'Rapprochement Bancaire',
        'RC', 'Rapprochement de Controle',
        'JC', 'Justification de compte',
        'CL', 'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE,'STATEMENT', 'B','CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE('28/02/2026', 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID)
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    NULL AS DATE_APUREMENT,
    NULL AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980','DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
  AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'OUTSTANDING'

UNION

-- Requete RECONCILED (suspens rapproches)
SELECT /*+  optimizer_features_enable('10.2.0.4') */ DISTINCT
    '28/02/2026' AS DATE_ARRETE,
    (SELECT DECODE(RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2),
        'RB', 'Rapprochement Bancaire',
        'RC', 'Rapprochement de Controle',
        'JC', 'Justification de compte',
        'CL', 'Compte de liaison')
     FROM BS_ACCTS BS_ACCTS2
     WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS TYPE_RAPRO,
    (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) AS SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS ACCTS2 WHERE ACCTS2.ACCT_ID = BS_ACCTS.ACCT_GROUP) AS SOCIETE,
    BA_CPME.COMPTE_BANCAIRE AS COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME AS LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE AS LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) AS CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0,
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'),
        'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')) AS SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE,'STATEMENT', 'B','CASHBOOK', 'C') AS COTE_SUSPENS,
    TO_DATE('28/02/2026', 'DD/MM/RRRR') - BRR_TRANSACTIONS.TRANSACTION_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) AS ANCIENNETE_M,
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE BRR_TRANSACTIONS.AMOUNT >= PIMO.BORNE_INF AND BRR_TRANSACTIONS.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    BA_CPME.METHODE AS METHODE_PROVISION,
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID)
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), BRR_TRANSACTIONS.TRANSACTION_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE AS STATUT,
    TO_DATE(BRR_TRANSACTIONS.UPDATE_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,
    (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) AS DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT AS COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO AS NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        NULL, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT),
        DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) AS DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED
        WHEN TO_DATE('01/01/1980','DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT RPAD(ACCT_NUM,LENGTH(ACCT_NUM)-2) FROM BS_ACCTS BS_ACCTS2 WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
  AND (SELECT B.ACCT_NUM FROM BS_ACCTS B WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID FROM BRR_ACCOUNT_HIERARCHIES H WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'RECONCILED'

ORDER BY SERVICE, SOCIETE, COMPTE_BANCAIRE, DATE_OPERATION_SUSPENS, NETTING;
