-- ============================================================
-- Requete BAATGS - VERSION V2 ACCES DIRECT BR_DATA
-- CORRIGEE pour resultat IDENTIQUE a l'original
-- Date : 18/02/2026
-- Parametres : DATE_ARRETE = 28/02/2026, TYPE = RB
-- ============================================================
-- Mapping colonnes BR_DATA -> BRR_TRANSACTIONS :
--   br_data.trans_date     -> TRANSACTION_DATE
--   br_data.acct_id        -> ACCOUNT_ID
--   br_data.rec_group      -> RECONCILIATION_REFERENCE
--   br_data.user_sixteen   -> CHARACTER_SIXTEEN
--   br_data.quantity       -> NUMERIC_TWO
--   br_data.note_add       -> DATE_LAST_NOTE_ADDED
--   br_data.upd_time       -> UPDATE_TIME
--   br_data.state = 3      -> 'OUTSTANDING'
--   br_data.state = 4      -> 'RECONCILED'
--   br_data.cs_flag = 'C'  -> SIDE = 'CASHBOOK'
--   br_data.cs_flag = 'S'  -> SIDE = 'STATEMENT'
--   br_data.pr_flag = 'P'  -> PAYMENT_OR_RECEIPT = 'PAYMENT'
--   br_data.pr_flag = 'R'  -> PAYMENT_OR_RECEIPT = 'RECEIPT'
-- ============================================================

WITH
-- Hierarchie des comptes (filtre RB + GESTION)
compte_hierarchie AS (
    SELECT /*+ MATERIALIZE */
        H.ACCOUNT_ID,
        B2.ACCT_NUM AS SERVICE,
        DECODE(RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Controle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison') AS TYPE_RAPRO
    FROM BRR_ACCOUNT_HIERARCHIES H
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
),

-- DC_MAX : MAX(TRANS_DATE) par groupe - INCLUT state 3 ET 4 (comme l'original)
dc_max_calc AS (
    SELECT /*+ MATERIALIZE */
        REC_GROUP,
        ACCT_ID,
        MAX(TRANS_DATE) AS DC_MAX
    FROM BR_DATA
    WHERE STATE IN (3, 4)  -- OUTSTANDING ET RECONCILED (comme la vue BRR_TRANSACTIONS)
      AND CS_FLAG IN ('C', 'S')
    GROUP BY REC_GROUP, ACCT_ID
)

-- ==================== PARTIE 1 : OUTSTANDING ====================
SELECT /*+ USE_HASH(D A CH CM) */ DISTINCT
    '28/02/2026' AS DATE_ARRETE,
    CH.TYPE_RAPRO,
    CH.SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
    CM.COMPTE_BANCAIRE,
    A.ACCT_NAME AS LIBELLE_COMPTE,
    A.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(D.TRANS_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    D.NARRATIVE AS LIBELLE_SUSPENS,
    -- DEBIT : PAYMENTSTATEMENT ou RECEIPTCASHBOOK
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'PAYMENTSTATEMENT', D.AMOUNT,
        'RECEIPTCASHBOOK', D.AMOUNT) AS DEBIT,
    -- CREDIT : RECEIPTSTATEMENT ou PAYMENTCASHBOOK
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'RECEIPTSTATEMENT', D.AMOUNT,
        'PAYMENTCASHBOOK', D.AMOUNT) AS CREDIT,
    -- SENS_ATTENDU
    DECODE(D.QUANTITY, 0,
        DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
            'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'),
        'A' || D.FLAG_C || DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
            'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')
    ) AS SENS_ATTENDU,
    DECODE(D.CS_FLAG, 'S', 'B', 'C') AS COTE_SUSPENS,
    TO_DATE('28/02/2026', 'DD/MM/RRRR') - D.TRANS_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) AS ANCIENNETE_M,
    -- BORNE_ANCIENNETE
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    -- PILIER_MONTANT_DEBIT
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    -- PILIER_MONTANT_CREDIT
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    CM.METHODE AS METHODE_PROVISION,
    -- TAUX
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = A.ACCT_ID)
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    'OUTSTANDING' AS STATUT,  -- Valeur fixe pour OUTSTANDING
    NULL AS DATE_APUREMENT,   -- NULL pour OUTSTANDING (comme l'original)
    NULL AS DC_MAX,           -- NULL pour OUTSTANDING (comme l'original)
    SUBSTR(D.USER_SIXTEEN, 1, 5) AS PRIORITE,
    D.LAST_NOTE_TEXT AS COMMENTAIRE,
    D.QUANTITY AS NETTING,
    -- DELTA
    DECODE(DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),'PAYMENTSTATEMENT',D.AMOUNT,'RECEIPTCASHBOOK',D.AMOUNT),
        NULL, DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),'RECEIPTSTATEMENT',D.AMOUNT,'PAYMENTCASHBOOK',D.AMOUNT),
        DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),'PAYMENTSTATEMENT',D.AMOUNT,'RECEIPTCASHBOOK',D.AMOUNT)) AS DELTA,
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    D.RECORD_ID AS ID_ECRITURE,
    CASE D.NOTE_ADD
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(D.NOTE_ADD, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BR_DATA D
JOIN BS_ACCTS A ON A.ACCT_ID = D.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = D.ACCT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
WHERE D.STATE = 3  -- OUTSTANDING
  AND D.CS_FLAG IN ('C', 'S')
  AND D.TRANS_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')

UNION

-- ==================== PARTIE 2 : RECONCILED ====================
SELECT /*+ USE_HASH(D A CH CM DCM) */ DISTINCT
    '28/02/2026' AS DATE_ARRETE,
    CH.TYPE_RAPRO,
    CH.SERVICE,
    (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
    CM.COMPTE_BANCAIRE,
    A.ACCT_NAME AS LIBELLE_COMPTE,
    A.ACCT_CURRENCY AS DEVISE,
    TO_CHAR(D.TRANS_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
    D.NARRATIVE AS LIBELLE_SUSPENS,
    -- DEBIT
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'PAYMENTSTATEMENT', D.AMOUNT,
        'RECEIPTCASHBOOK', D.AMOUNT) AS DEBIT,
    -- CREDIT
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'RECEIPTSTATEMENT', D.AMOUNT,
        'PAYMENTCASHBOOK', D.AMOUNT) AS CREDIT,
    -- SENS_ATTENDU
    DECODE(D.QUANTITY, 0,
        DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
            'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'),
        'A' || D.FLAG_C || DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
            'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')
    ) AS SENS_ATTENDU,
    DECODE(D.CS_FLAG, 'S', 'B', 'C') AS COTE_SUSPENS,
    TO_DATE('28/02/2026', 'DD/MM/RRRR') - D.TRANS_DATE AS ANCIENNETE_J,
    MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) AS ANCIENNETE_M,
    -- BORNE_ANCIENNETE
    (SELECT LIBELLE_ANCIENNETE FROM BA_CATEG_ANCIENNETE BACA
     WHERE MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) >= BACA.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) < BACA.BORNE_SUP) AS BORNE_ANCIENNETE,
    -- PILIER_MONTANT_DEBIT
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'PAYMENTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP),
        'RECEIPTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_DEBIT,
    -- PILIER_MONTANT_CREDIT
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'RECEIPTSTATEMENT', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP),
        'PAYMENTCASHBOOK', (SELECT LIBELLE_PILIER FROM BA_PILIERS_MONTANTS PIMO WHERE D.AMOUNT >= PIMO.BORNE_INF AND D.AMOUNT < PIMO.BORNE_SUP)) AS PILIER_MONTANT_CREDIT,
    CM.METHODE AS METHODE_PROVISION,
    -- TAUX
    (SELECT TAUX FROM BA_METHODE_PROVISION MEPR
     WHERE METHODE = (SELECT METHODE FROM BA_COMPTE_METHODE CPME WHERE CPME.ACCOUNT_ID = A.ACCT_ID)
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) >= MEPR.BORNE_INF
       AND MONTHS_BETWEEN(TO_DATE('28/02/2026', 'DD/MM/RRRR'), D.TRANS_DATE) < MEPR.BORNE_SUP) AS TAUX,
    0 AS MONTANT_PROVISION,
    'RECONCILED' AS STATUT,  -- Valeur fixe pour RECONCILED
    TO_DATE(D.UPD_TIME, 'DD/MM/RRRR') AS DATE_APUREMENT,  -- Calcul pour RECONCILED
    DCM.DC_MAX AS DC_MAX,  -- MAX(TRANS_DATE) du groupe
    SUBSTR(D.USER_SIXTEEN, 1, 5) AS PRIORITE,
    D.LAST_NOTE_TEXT AS COMMENTAIRE,
    D.QUANTITY AS NETTING,
    -- DELTA
    DECODE(DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),'PAYMENTSTATEMENT',D.AMOUNT,'RECEIPTCASHBOOK',D.AMOUNT),
        NULL, DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),'RECEIPTSTATEMENT',D.AMOUNT,'PAYMENTCASHBOOK',D.AMOUNT),
        DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),'PAYMENTSTATEMENT',D.AMOUNT,'RECEIPTCASHBOOK',D.AMOUNT)) AS DELTA,
    DECODE(DECODE(D.PR_FLAG,'P','PAYMENT','RECEIPT') || DECODE(D.CS_FLAG,'C','CASHBOOK','STATEMENT'),
        'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') AS SENS_DELTA,
    '' AS NUMERO_FICHE,
    '' AS DERNIER_STATUT,
    D.RECORD_ID AS ID_ECRITURE,
    CASE D.NOTE_ADD
        WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
        ELSE TO_CHAR(D.NOTE_ADD, 'DD/MM/RRRR')
    END AS ANNOTE_LE
FROM BR_DATA D
JOIN BS_ACCTS A ON A.ACCT_ID = D.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = D.ACCT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN dc_max_calc DCM ON DCM.REC_GROUP = D.REC_GROUP AND DCM.ACCT_ID = D.ACCT_ID
WHERE D.STATE = 4  -- RECONCILED
  AND D.CS_FLAG IN ('C', 'S')
  AND D.TRANS_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND DCM.DC_MAX >= TO_DATE('28/02/2026', 'DD/MM/RRRR')  -- Condition filtre RECONCILED

ORDER BY SERVICE, SOCIETE, COMPTE_BANCAIRE, DATE_OPERATION_SUSPENS, NETTING;


-- ============================================================
-- INDEX RECOMMANDES SUR BR_DATA
-- ============================================================
-- SELECT INDEX_NAME, COLUMN_NAME FROM ALL_IND_COLUMNS WHERE TABLE_NAME = 'BR_DATA';

-- CREATE INDEX IDX_BR_DATA_STATE_DATE ON BR_DATA(STATE, TRANS_DATE, CS_FLAG, ACCT_ID);
-- CREATE INDEX IDX_BR_DATA_ACCT ON BR_DATA(ACCT_ID, STATE);
-- CREATE INDEX IDX_BR_DATA_REC ON BR_DATA(REC_GROUP, ACCT_ID, STATE);
