-- ============================================================================
-- SIMULATION DES FILTRES - RNADGENEXPGES01.sql
-- ============================================================================
-- Date: 07/02/2026
-- Objectif: Simuler EXACTEMENT les filtres de RNADGENEXPGES01.sql
--           pour comprendre pourquoi 2817 est bloqué mais 22.36 passe
-- ============================================================================

SET LINESIZE 300
SET PAGESIZE 100
SET SERVEROUTPUT ON

PROMPT ============================================================================
PROMPT SIMULATION DES FILTRES DE RNADGENEXPGES01.sql
PROMPT ============================================================================
PROMPT
PROMPT Transaction 22.36 : PAYMENTREF=55842680, RIB=00010207054
PROMPT Transaction 2817  : PAYMENTREF=55841990, RIB=00016111832
PROMPT

PROMPT ============================================================================
PROMPT ÉTAPE 1 : Récupération de l'ID_COMPTE_BANCAIRE_SYSTEME pour chaque RIB
PROMPT ============================================================================

WITH ribs AS (
    SELECT DISTINCT IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    CASE WHEN R.IDENTIFICATIONRIB = '00010207054' THEN '22.36' ELSE '2817' END AS TRANSACTION,
    R.BANKCODE || R.BRANCHCODE || R.IDENTIFICATIONRIB || R.RIBCHECKDIGIT AS RIB_COMPLET,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CBS.NUMERO AS NUM_COMPTE_BANCAIRE_SYSTEME,
    CBS.GENERATIONCONTREPARTIE
FROM ribs R
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = R.BANKCODE
        AND CBS.RIBBRANCHCODE = R.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = R.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = R.RIBCHECKDIGIT
ORDER BY 1;

PROMPT
PROMPT Si NULL → Le RIB n'existe pas dans TA_RN_COMPTE_BANCAIRE_SYSTEME ❌
PROMPT

PROMPT ============================================================================
PROMPT ÉTAPE 2 : Le compte accurate est-il dans TA_RN_GESTION_ACCURATE ?
PROMPT ============================================================================

WITH ribs AS (
    SELECT DISTINCT
        CASE WHEN IDENTIFICATIONRIB = '00010207054' THEN '22.36' ELSE '2817' END AS TRANSACTION,
        IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    R.TRANSACTION,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    GA.ID_COMPTE_ACCURATE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO,
    CASE WHEN GA.ID_COMPTE_ACCURATE IS NOT NULL THEN 'OUI ✅' ELSE 'NON ❌ BLOQUÉ' END AS DANS_GESTION_ACCURATE
FROM ribs R
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = R.BANKCODE
        AND CBS.RIBBRANCHCODE = R.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = R.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = R.RIBCHECKDIGIT
    LEFT JOIN TA_RN_GESTION_ACCURATE GA
        ON GA.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
    LEFT JOIN TA_RN_COMPTE_ACCURATE CA
        ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
ORDER BY 1;

PROMPT
PROMPT Si NON ❌ → Le compte n'est pas paramétré dans TA_RN_GESTION_ACCURATE
PROMPT              C'EST LE PROBLÈME ! Aucune ligne ne sera exportée vers TA_RN_EXPORT
PROMPT

PROMPT ============================================================================
PROMPT ÉTAPE 3 : FILTRE 1 - Exclusion SOCIETE
PROMPT ============================================================================

WITH trans_data AS (
    SELECT
        CASE WHEN OPERATIONNETAMOUNT = '22.36' THEN '22.36' ELSE '2817' END AS TRANSACTION,
        IDENTIFICATION AS CODE_SOCIETE,
        IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE,
        ROWNUM AS RN
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    T.TRANSACTION,
    T.CODE_SOCIETE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    S.ID_SOCIETE,
    ES.ID_SOCIETE AS SOCIETE_EXCLUE_ID,
    CASE
        WHEN ES.ID_SOCIETE IS NOT NULL THEN '❌ EXCLU - Transaction bloquée'
        WHEN S.ID_SOCIETE IS NULL THEN '⚠️ Société inconnue'
        ELSE '✅ PASSE'
    END AS FILTRE_SOCIETE
FROM trans_data T
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = T.BANKCODE
        AND CBS.RIBBRANCHCODE = T.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
    LEFT JOIN TA_RN_SOCIETE S ON S.CODE = T.CODE_SOCIETE
    LEFT JOIN TA_RN_EXCLUSION_SOCIETE ES
        ON ES.ID_SOCIETE = S.ID_SOCIETE
        AND ES.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
WHERE T.RN = 1
ORDER BY T.TRANSACTION;

PROMPT
PROMPT ============================================================================
PROMPT ÉTAPE 4 : FILTRE 2 - Exclusion DEVISE
PROMPT ============================================================================

WITH trans_data AS (
    SELECT
        CASE WHEN OPERATIONNETAMOUNT = '22.36' THEN '22.36' ELSE '2817' END AS TRANSACTION,
        OPERATIONNETAMOUNTCURRENCY AS DEVISE,
        IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE,
        ROWNUM AS RN
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    T.TRANSACTION,
    T.DEVISE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    D.ID_DEVISE,
    ED.ID_DEVISE AS DEVISE_EXCLUE_ID,
    CASE
        WHEN ED.ID_DEVISE IS NOT NULL THEN '❌ EXCLU - Transaction bloquée'
        WHEN D.ID_DEVISE IS NULL THEN '⚠️ Devise inconnue'
        ELSE '✅ PASSE'
    END AS FILTRE_DEVISE
FROM trans_data T
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = T.BANKCODE
        AND CBS.RIBBRANCHCODE = T.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
    LEFT JOIN TA_RN_DEVISE D ON D.CODE_ISO_DEVISE = T.DEVISE
    LEFT JOIN TA_RN_EXCLUSION_DEVISE ED
        ON ED.ID_DEVISE = D.ID_DEVISE
        AND ED.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
WHERE T.RN = 1
ORDER BY T.TRANSACTION;

PROMPT
PROMPT ============================================================================
PROMPT ÉTAPE 5 : FILTRE 3 - Exclusion MODE REGLEMENT
PROMPT ============================================================================

WITH trans_data AS (
    SELECT
        CASE WHEN OPERATIONNETAMOUNT = '22.36' THEN '22.36' ELSE '2817' END AS TRANSACTION,
        SETTLEMENTMODE,
        IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE,
        ROWNUM AS RN
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    T.TRANSACTION,
    T.SETTLEMENTMODE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    MR.ID_MODE_REGLEMENT,
    EMR.ID_MODE_REGLEMENT AS MODE_REGLEMENT_EXCLU_ID,
    CASE
        WHEN EMR.ID_MODE_REGLEMENT IS NOT NULL THEN '❌ EXCLU - Transaction bloquée'
        WHEN MR.ID_MODE_REGLEMENT IS NULL THEN '⚠️ Mode règlement inconnu'
        ELSE '✅ PASSE'
    END AS FILTRE_MODE_REGLEMENT
FROM trans_data T
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = T.BANKCODE
        AND CBS.RIBBRANCHCODE = T.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.CODE_MODE_REGLEMENT = T.SETTLEMENTMODE
    LEFT JOIN TA_RN_EXCLUSION_MR EMR
        ON EMR.ID_MODE_REGLEMENT = MR.ID_MODE_REGLEMENT
        AND EMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
WHERE T.RN = 1
ORDER BY T.TRANSACTION;

PROMPT
PROMPT ============================================================================
PROMPT ÉTAPE 6 : FILTRE 4 - Exclusion TYPE REGLEMENT
PROMPT ============================================================================

WITH trans_data AS (
    SELECT
        CASE WHEN OPERATIONNETAMOUNT = '22.36' THEN '22.36' ELSE '2817' END AS TRANSACTION,
        TYPEREGLEMENT,
        IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE,
        ROWNUM AS RN
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    T.TRANSACTION,
    T.TYPEREGLEMENT,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    ETR.TYPE_REGLEMENT AS TYPE_REGLEMENT_EXCLU,
    CASE
        WHEN ETR.TYPE_REGLEMENT IS NOT NULL THEN '❌ EXCLU - Transaction bloquée'
        ELSE '✅ PASSE'
    END AS FILTRE_TYPE_REGLEMENT
FROM trans_data T
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = T.BANKCODE
        AND CBS.RIBBRANCHCODE = T.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
    LEFT JOIN TA_RN_EXCLUSION_TR ETR
        ON ETR.TYPE_REGLEMENT = T.TYPEREGLEMENT
        AND ETR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
WHERE T.RN = 1
ORDER BY T.TRANSACTION;

PROMPT
PROMPT ============================================================================
PROMPT ÉTAPE 7 : FILTRE 5 - Cumul Mode Règlement (EXISTS TA_RN_CUMUL_MR)
PROMPT ============================================================================
PROMPT Ce filtre determine si la transaction doit etre cumulee ou en detail
PROMPT

WITH trans_data AS (
    SELECT
        CASE WHEN OPERATIONNETAMOUNT = '22.36' THEN '22.36' ELSE '2817' END AS TRANSACTION,
        SETTLEMENTMODE,
        NUMEROCLIENT,
        STATUTREGLEMENT,
        IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE,
        ROWNUM AS RN
    FROM TA_RN_IMPORT_GESTION
    WHERE OPERATIONNETAMOUNT IN ('22.36', '2817')
)
SELECT
    T.TRANSACTION,
    T.SETTLEMENTMODE,
    T.NUMEROCLIENT,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE
        WHEN EXISTS (
            SELECT 1
            FROM TA_RN_MODE_REGLEMENT MR2, TA_RN_CUMUL_MR CMR, TA_RN_PRODUIT P
            WHERE CMR.ID_MODE_REGLEMENT = MR2.ID_MODE_REGLEMENT
              AND CMR.ID_PRODUIT = P.ID_PRODUIT
              AND CMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
              AND (P.CODE_PRODUIT = T.NUMEROCLIENT OR P.CODE_PRODUIT = 'ALL')
              AND (MR2.CODE_MODE_REGLEMENT = T.SETTLEMENTMODE OR MR2.CODE_MODE_REGLEMENT = 'ALL')
        ) THEN 'OUI - Transaction sera CUMULEE'
        ELSE 'NON - Transaction en DETAIL ✅'
    END AS A_CUMULER,
    CASE
        WHEN T.SETTLEMENTMODE IN ('VO','PC','PQ','PM') AND T.STATUTREGLEMENT = 'ANNULE'
        THEN 'OUI - Transaction ANNULEE ✅ (passe le filtre)'
        ELSE 'NON'
    END AS FILTRE_ANNULE
FROM trans_data T
    LEFT JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
        ON CBS.RIBBANKCODE = T.BANKCODE
        AND CBS.RIBBRANCHCODE = T.BRANCHCODE
        AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
        AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
WHERE T.RN = 1
ORDER BY T.TRANSACTION;

PROMPT
PROMPT NOTE: Le filtre dans RNADGENEXPGES01.sql ligne 1000-1010 dit:
PROMPT   AND (NOT EXISTS cumul MR) OR (ANNULE pour VO/PC/PQ/PM)
PROMPT Donc si EXISTS cumul = OUI → Transaction est BLOQUÉE pour le detail (sauf si ANNULE)
PROMPT

PROMPT ============================================================================
PROMPT ÉTAPE 8 : SIMULATION COMPLETE - Quelle transaction PASSERAIT le filtre ?
PROMPT ============================================================================
PROMPT Condition globale pour insertion DETAIL dans TA_RN_EXPORT:
PROMPT   - NOT dans exclusion societe
PROMPT   - NOT dans exclusion devise
PROMPT   - NOT dans exclusion mode reglement
PROMPT   - NOT dans exclusion type reglement
PROMPT   - (NOT EXISTS cumul MR) OR (ANNULE)
PROMPT   - RIB correspond
PROMPT   - Dans TA_RN_GESTION_ACCURATE
PROMPT

DECLARE
    v_count_22 NUMBER := 0;
    v_count_2817 NUMBER := 0;
    v_msg VARCHAR2(4000);

    CURSOR c_22 IS
        WITH trans_data AS (
            SELECT
                IDENTIFICATION, OPERATIONNETAMOUNTCURRENCY, SETTLEMENTMODE, TYPEREGLEMENT,
                NUMEROCLIENT, STATUTREGLEMENT,
                IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE
            FROM TA_RN_IMPORT_GESTION
            WHERE OPERATIONNETAMOUNT = '22.36' AND ROWNUM = 1
        )
        SELECT COUNT(*) AS nb
        FROM trans_data T
            JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
                ON CBS.RIBBANKCODE = T.BANKCODE
                AND CBS.RIBBRANCHCODE = T.BRANCHCODE
                AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
                AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
            JOIN TA_RN_GESTION_ACCURATE GA ON GA.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
        WHERE NOT T.IDENTIFICATION IN (
                SELECT S.CODE FROM TA_RN_SOCIETE S, TA_RN_EXCLUSION_SOCIETE ES
                WHERE S.ID_SOCIETE = ES.ID_SOCIETE
                  AND ES.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND NOT T.OPERATIONNETAMOUNTCURRENCY IN (
                SELECT D.CODE_ISO_DEVISE FROM TA_RN_DEVISE D, TA_RN_EXCLUSION_DEVISE ED
                WHERE D.ID_DEVISE = ED.ID_DEVISE
                  AND ED.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND NOT T.SETTLEMENTMODE IN (
                SELECT MR.CODE_MODE_REGLEMENT FROM TA_RN_MODE_REGLEMENT MR, TA_RN_EXCLUSION_MR EMR
                WHERE MR.ID_MODE_REGLEMENT = EMR.ID_MODE_REGLEMENT
                  AND EMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND NOT T.TYPEREGLEMENT IN (
                SELECT TYPE_REGLEMENT FROM TA_RN_EXCLUSION_TR ETR
                WHERE ETR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND (
                NOT EXISTS (
                    SELECT 1 FROM TA_RN_MODE_REGLEMENT MR2, TA_RN_CUMUL_MR CMR, TA_RN_PRODUIT P
                    WHERE CMR.ID_MODE_REGLEMENT = MR2.ID_MODE_REGLEMENT
                      AND CMR.ID_PRODUIT = P.ID_PRODUIT
                      AND CMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
                      AND (P.CODE_PRODUIT = T.NUMEROCLIENT OR P.CODE_PRODUIT = 'ALL')
                      AND (MR2.CODE_MODE_REGLEMENT = T.SETTLEMENTMODE OR MR2.CODE_MODE_REGLEMENT = 'ALL')
                )
                OR (T.SETTLEMENTMODE IN ('VO','PC','PQ','PM') AND T.STATUTREGLEMENT = 'ANNULE')
            );

    CURSOR c_2817 IS
        WITH trans_data AS (
            SELECT
                IDENTIFICATION, OPERATIONNETAMOUNTCURRENCY, SETTLEMENTMODE, TYPEREGLEMENT,
                NUMEROCLIENT, STATUTREGLEMENT,
                IDENTIFICATIONRIB, RIBCHECKDIGIT, BANKCODE, BRANCHCODE
            FROM TA_RN_IMPORT_GESTION
            WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
        )
        SELECT COUNT(*) AS nb
        FROM trans_data T
            JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS
                ON CBS.RIBBANKCODE = T.BANKCODE
                AND CBS.RIBBRANCHCODE = T.BRANCHCODE
                AND CBS.RIBIDENTIFICATION = T.IDENTIFICATIONRIB
                AND CBS.RIBCHECKDIGIT = T.RIBCHECKDIGIT
            JOIN TA_RN_GESTION_ACCURATE GA ON GA.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
        WHERE NOT T.IDENTIFICATION IN (
                SELECT S.CODE FROM TA_RN_SOCIETE S, TA_RN_EXCLUSION_SOCIETE ES
                WHERE S.ID_SOCIETE = ES.ID_SOCIETE
                  AND ES.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND NOT T.OPERATIONNETAMOUNTCURRENCY IN (
                SELECT D.CODE_ISO_DEVISE FROM TA_RN_DEVISE D, TA_RN_EXCLUSION_DEVISE ED
                WHERE D.ID_DEVISE = ED.ID_DEVISE
                  AND ED.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND NOT T.SETTLEMENTMODE IN (
                SELECT MR.CODE_MODE_REGLEMENT FROM TA_RN_MODE_REGLEMENT MR, TA_RN_EXCLUSION_MR EMR
                WHERE MR.ID_MODE_REGLEMENT = EMR.ID_MODE_REGLEMENT
                  AND EMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND NOT T.TYPEREGLEMENT IN (
                SELECT TYPE_REGLEMENT FROM TA_RN_EXCLUSION_TR ETR
                WHERE ETR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
            )
          AND (
                NOT EXISTS (
                    SELECT 1 FROM TA_RN_MODE_REGLEMENT MR2, TA_RN_CUMUL_MR CMR, TA_RN_PRODUIT P
                    WHERE CMR.ID_MODE_REGLEMENT = MR2.ID_MODE_REGLEMENT
                      AND CMR.ID_PRODUIT = P.ID_PRODUIT
                      AND CMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME
                      AND (P.CODE_PRODUIT = T.NUMEROCLIENT OR P.CODE_PRODUIT = 'ALL')
                      AND (MR2.CODE_MODE_REGLEMENT = T.SETTLEMENTMODE OR MR2.CODE_MODE_REGLEMENT = 'ALL')
                )
                OR (T.SETTLEMENTMODE IN ('VO','PC','PQ','PM') AND T.STATUTREGLEMENT = 'ANNULE')
            );
BEGIN
    OPEN c_22;
    FETCH c_22 INTO v_count_22;
    CLOSE c_22;

    OPEN c_2817;
    FETCH c_2817 INTO v_count_2817;
    CLOSE c_2817;

    DBMS_OUTPUT.PUT_LINE('============================================================================');
    DBMS_OUTPUT.PUT_LINE('RÉSULTAT FINAL DE LA SIMULATION');
    DBMS_OUTPUT.PUT_LINE('============================================================================');
    DBMS_OUTPUT.PUT_LINE('');
    DBMS_OUTPUT.PUT_LINE('Transaction 22.36 passerait le filtre ? ' ||
        CASE WHEN v_count_22 > 0 THEN 'OUI ✅ (' || v_count_22 || ' ligne)' ELSE 'NON ❌' END);
    DBMS_OUTPUT.PUT_LINE('Transaction 2817 passerait le filtre ?  ' ||
        CASE WHEN v_count_2817 > 0 THEN 'OUI ✅ (' || v_count_2817 || ' ligne)' ELSE 'NON ❌' END);
    DBMS_OUTPUT.PUT_LINE('');

    IF v_count_22 > 0 AND v_count_2817 = 0 THEN
        DBMS_OUTPUT.PUT_LINE('⚠️ PROBLÈME IDENTIFIÉ: 22.36 passe mais 2817 est bloqué !');
        DBMS_OUTPUT.PUT_LINE('→ Vérifiez les étapes 1-7 ci-dessus pour identifier quel filtre bloque 2817');
    ELSIF v_count_22 = 0 AND v_count_2817 = 0 THEN
        DBMS_OUTPUT.PUT_LINE('⚠️ Les deux transactions sont bloquées !');
        DBMS_OUTPUT.PUT_LINE('→ Probablement un problème dans TA_RN_GESTION_ACCURATE (Étape 2)');
    ELSIF v_count_22 > 0 AND v_count_2817 > 0 THEN
        DBMS_OUTPUT.PUT_LINE('✅ Les deux transactions passeraient le filtre');
        DBMS_OUTPUT.PUT_LINE('→ Le problème est ailleurs (pas dans RNADGENEXPGES01.sql)');
    END IF;

    DBMS_OUTPUT.PUT_LINE('============================================================================');
END;
/

PROMPT
PROMPT ============================================================================
PROMPT FIN SIMULATION
PROMPT ============================================================================
