-- ============================================================================
-- VÉRIFICATION PARAMÉTRAGE - Comptes 342 vs 394
-- ============================================================================
-- Date: 07/02/2026
-- Objectif: Vérifier pourquoi 342 pourrait être rejeté alors que 394 passe
-- Contexte: Les deux comptes SONT dans TA_RN_GESTION_ACCURATE
-- ============================================================================

SET LINESIZE 300
SET PAGESIZE 200

PROMPT ============================================================================
PROMPT DIAGNOSTIC PARAMÉTRAGE - Compte 342 (2817) vs 394 (22.36)
PROMPT ============================================================================

PROMPT
PROMPT ============================================================================
PROMPT 1. RIB DES TRANSACTIONS vs RIB DES COMPTES
PROMPT ============================================================================
PROMPT Transaction 22.36: RIB = 00010207054 (de TA_RN_IMPORT_GESTION_JC)
PROMPT Transaction 2817 : RIB = 00016111832 (de TA_RN_IMPORT_GESTION_JC)
PROMPT
PROMPT Comptes paramétrés:

SELECT
    CA.ID_COMPTE_ACCURATE,
    CA.NUM_COMPTE_ACCURATE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CBS.RIBBANKCODE,
    CBS.RIBBRANCHCODE,
    CBS.RIBIDENTIFICATION,
    CBS.RIBCHECKDIGIT,
    CBS.RIBBANKCODE||CBS.RIBBRANCHCODE||CBS.RIBIDENTIFICATION||CBS.RIBCHECKDIGIT AS RIB_COMPLET
FROM TA_RN_COMPTE_ACCURATE CA
    JOIN TA_RN_GESTION_ACCURATE GA ON GA.ID_COMPTE_ACCURATE = CA.ID_COMPTE_ACCURATE
    JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE CA.ID_COMPTE_ACCURATE IN (342, 394)
ORDER BY CA.ID_COMPTE_ACCURATE;

PROMPT
PROMPT VÉRIFICATION:
PROMPT - Compte 394: RIB doit contenir 00010207054
PROMPT - Compte 342: RIB doit contenir 00016111832
PROMPT

PROMPT ============================================================================
PROMPT 2. COMPARAISON DES PARAMÈTRES - 342 vs 394
PROMPT ============================================================================

SELECT
    CA.ID_COMPTE_ACCURATE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO,
    CA.FLAG_ACTIF,
    CA.DATE_DEBUT,
    CA.DATE_FIN,
    CBS.GENERATIONCONTREPARTIE,
    CBS.NUMERO AS NUM_CBS,
    GA.ID_COMPTE_BANCAIRE_SYSTEME
FROM TA_RN_COMPTE_ACCURATE CA
    JOIN TA_RN_GESTION_ACCURATE GA ON GA.ID_COMPTE_ACCURATE = CA.ID_COMPTE_ACCURATE
    JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE CA.ID_COMPTE_ACCURATE IN (342, 394)
ORDER BY CA.ID_COMPTE_ACCURATE;

PROMPT
PROMPT Les deux doivent avoir:
PROMPT - TYPE_RAPPRO = 'B'
PROMPT - FLAG_ACTIF = 'O'
PROMPT - DATE_FIN = NULL ou > SYSDATE
PROMPT

PROMPT ============================================================================
PROMPT 3. EXCLUSIONS SOCIÉTÉS - Comptes 342 vs 394
PROMPT ============================================================================
PROMPT Transaction 22.36: CODE_SOCIETE = 00838038
PROMPT Transaction 2817 : CODE_SOCIETE = 90141615

-- Pour le compte 394
SELECT
    '394 (22.36)' AS COMPTE,
    ES.ID_COMPTE_BANCAIRE_SYSTEME,
    S.CODE AS CODE_SOCIETE,
    S.NOM AS NOM_SOCIETE,
    'EXCLUE ❌' AS STATUT
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    JOIN TA_RN_SOCIETE S ON S.ID_SOCIETE = ES.ID_SOCIETE
WHERE GA.ID_COMPTE_ACCURATE = 394

UNION ALL

-- Pour le compte 342
SELECT
    '342 (2817)' AS COMPTE,
    ES.ID_COMPTE_BANCAIRE_SYSTEME,
    S.CODE AS CODE_SOCIETE,
    S.NOM AS NOM_SOCIETE,
    'EXCLUE ❌' AS STATUT
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    JOIN TA_RN_SOCIETE S ON S.ID_SOCIETE = ES.ID_SOCIETE
WHERE GA.ID_COMPTE_ACCURATE = 342

ORDER BY 1, 3;

PROMPT
PROMPT Si vide → Aucune exclusion de société ✅
PROMPT Si lignes → Sociétés exclues pour ces comptes
PROMPT    → Vérifier si 00838038 ou 90141615 sont dans la liste
PROMPT

PROMPT ============================================================================
PROMPT 4. EXCLUSIONS DEVISES - Comptes 342 vs 394
PROMPT ============================================================================
PROMPT Les deux transactions sont en EUR

SELECT
    CASE WHEN GA.ID_COMPTE_ACCURATE = 394 THEN '394 (22.36)' ELSE '342 (2817)' END AS COMPTE,
    ED.ID_COMPTE_BANCAIRE_SYSTEME,
    D.CODE_ISO_DEVISE,
    'EXCLUE ❌' AS STATUT
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_EXCLUSION_DEVISE ED ON ED.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    JOIN TA_RN_DEVISE D ON D.ID_DEVISE = ED.ID_DEVISE
WHERE GA.ID_COMPTE_ACCURATE IN (342, 394)
ORDER BY 1;

PROMPT
PROMPT Si EUR dans la liste → Les transactions en EUR sont EXCLUES ❌
PROMPT

PROMPT ============================================================================
PROMPT 5. EXCLUSIONS MODE DE RÈGLEMENT - Comptes 342 vs 394
PROMPT ============================================================================
PROMPT Les deux transactions ont SETTLEMENTMODE = 'VO'

SELECT
    CASE WHEN GA.ID_COMPTE_ACCURATE = 394 THEN '394 (22.36)' ELSE '342 (2817)' END AS COMPTE,
    EMR.ID_COMPTE_BANCAIRE_SYSTEME,
    MR.CODE_MODE_REGLEMENT,
    MR.LIBELLE,
    'EXCLU ❌' AS STATUT
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_EXCLUSION_MR EMR ON EMR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    JOIN TA_RN_MODE_REGLEMENT MR ON MR.ID_MODE_REGLEMENT = EMR.ID_MODE_REGLEMENT
WHERE GA.ID_COMPTE_ACCURATE IN (342, 394)
ORDER BY 1, 3;

PROMPT
PROMPT Si VO dans la liste → Les transactions VO sont EXCLUES ❌
PROMPT

PROMPT ============================================================================
PROMPT 6. EXCLUSIONS TYPE DE RÈGLEMENT - Comptes 342 vs 394
PROMPT ============================================================================
PROMPT Les deux transactions ont TYPEREGLEMENT = 'DEC'

SELECT
    CASE WHEN GA.ID_COMPTE_ACCURATE = 394 THEN '394 (22.36)' ELSE '342 (2817)' END AS COMPTE,
    ETR.ID_COMPTE_BANCAIRE_SYSTEME,
    ETR.TYPE_REGLEMENT,
    'EXCLU ❌' AS STATUT
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_EXCLUSION_TR ETR ON ETR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE GA.ID_COMPTE_ACCURATE IN (342, 394)
ORDER BY 1, 3;

PROMPT
PROMPT Si DEC dans la liste → Les transactions DEC sont EXCLUES ❌
PROMPT

PROMPT ============================================================================
PROMPT 7. MODE CUMUL - Comptes 342 vs 394
PROMPT ============================================================================
PROMPT Transaction 22.36: CLIENT=00838038, MODE=VO
PROMPT Transaction 2817 : CLIENT=90141615, MODE=VO

SELECT
    CASE WHEN GA.ID_COMPTE_ACCURATE = 394 THEN '394 (22.36)' ELSE '342 (2817)' END AS COMPTE,
    CMR.ID_COMPTE_BANCAIRE_SYSTEME,
    P.CODE_PRODUIT,
    MR.CODE_MODE_REGLEMENT,
    'MODE CUMUL ACTIF ❌' AS STATUT
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_CUMUL_MR CMR ON CMR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    JOIN TA_RN_PRODUIT P ON P.ID_PRODUIT = CMR.ID_PRODUIT
    JOIN TA_RN_MODE_REGLEMENT MR ON MR.ID_MODE_REGLEMENT = CMR.ID_MODE_REGLEMENT
WHERE GA.ID_COMPTE_ACCURATE IN (342, 394)
ORDER BY 1, 2, 3, 4;

PROMPT
PROMPT Si lignes avec CODE_PRODUIT='ALL' ou '00838038'/'90141615' ET CODE_MODE='VO'
PROMPT   → Les transactions seront CUMULÉES, pas exportées en détail ❌
PROMPT

PROMPT ============================================================================
PROMPT 8. VÉRIFICATION CODES SOCIÉTÉS EXISTENT DANS TA_RN_SOCIETE
PROMPT ============================================================================

SELECT
    CODE,
    NOM,
    ID_SOCIETE
FROM TA_RN_SOCIETE
WHERE CODE IN ('00838038', '90141615')
ORDER BY CODE;

PROMPT
PROMPT Si 90141615 absent → LibelleSociete() retournera ''
PROMPT   → Peut empêcher le traitement
PROMPT

PROMPT ============================================================================
PROMPT 9. RÉSUMÉ - DIFFÉRENCES ENTRE 342 et 394
PROMPT ============================================================================

WITH exclusions_394 AS (
    SELECT COUNT(*) AS nb_exclusions
    FROM TA_RN_GESTION_ACCURATE GA
        LEFT JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_EXCLUSION_DEVISE ED ON ED.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_EXCLUSION_MR EMR ON EMR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_EXCLUSION_TR ETR ON ETR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_CUMUL_MR CMR ON CMR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 394
      AND (ES.ID_SOCIETE IS NOT NULL OR ED.ID_DEVISE IS NOT NULL
           OR EMR.ID_MODE_REGLEMENT IS NOT NULL OR ETR.TYPE_REGLEMENT IS NOT NULL
           OR CMR.ID_MODE_REGLEMENT IS NOT NULL)
),
exclusions_342 AS (
    SELECT COUNT(*) AS nb_exclusions
    FROM TA_RN_GESTION_ACCURATE GA
        LEFT JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_EXCLUSION_DEVISE ED ON ED.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_EXCLUSION_MR EMR ON EMR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_EXCLUSION_TR ETR ON ETR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
        LEFT JOIN TA_RN_CUMUL_MR CMR ON CMR.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342
      AND (ES.ID_SOCIETE IS NOT NULL OR ED.ID_DEVISE IS NOT NULL
           OR EMR.ID_MODE_REGLEMENT IS NOT NULL OR ETR.TYPE_REGLEMENT IS NOT NULL
           OR CMR.ID_MODE_REGLEMENT IS NOT NULL)
)
SELECT
    '394 (22.36)' AS COMPTE,
    E394.nb_exclusions AS NB_REGLES_EXCLUSION
FROM exclusions_394 E394
UNION ALL
SELECT
    '342 (2817)' AS COMPTE,
    E342.nb_exclusions AS NB_REGLES_EXCLUSION
FROM exclusions_342 E342
ORDER BY 1;

PROMPT
PROMPT Si 342 a PLUS de règles d'exclusion que 394 → Cause probable du rejet
PROMPT

PROMPT ============================================================================
PROMPT FIN VÉRIFICATION PARAMÉTRAGE
PROMPT ============================================================================
