-- ============================================================
-- VERIFICATION : DTC670 Original vs Optimise (modifs minimales)
-- SQL_ID : 4v9ag77cam8uu
-- Date : 20/02/2026
-- Objectif : S'assurer que les modifications n'introduisent
--            AUCUNE regression
-- ============================================================
-- Parametres : Remplacer :B1 et :B2 par vos valeurs
--   :B1 = '28/02/2026' (date arrete)
--   :B2 = 'RB' (type rapro)
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200
SET PAGESIZE 1000
SET TIMING ON

PROMPT ============================================================
PROMPT VERIFICATION DTC670 - SQL_ID 4v9ag77cam8uu
PROMPT Original vs Optimise (modifications minimales)
PROMPT ============================================================
PROMPT

-- ============================================================
-- ETAPE 1/5 : COMPTAGE REQUETE ORIGINALE
-- ============================================================
PROMPT [1/5] Comptage ORIGINAL...

SELECT 'ORIGINAL' AS VERSION, COUNT(*) AS NB_LIGNES FROM (
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
UNION
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND (SELECT MAX(E.TRANSACTION_DATE)
       FROM BRR_TRANSACTIONS E
       WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
         AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND (BRR_TRANSACTIONS.STATE = 'RECONCILED')
);


-- ============================================================
-- ETAPE 2/5 : COMPTAGE REQUETE OPTIMISEE
-- ============================================================
PROMPT
PROMPT [2/5] Comptage OPTIMISE...

SELECT 'OPTIMISE' AS VERSION, COUNT(*) AS NB_LIGNES FROM (
SELECT /*+ LEADING(BRR_TRANSACTIONS BS_ACCTS BA_CPME)
           USE_HASH(BS_ACCTS BA_CPME)
           NO_MERGE */ DISTINCT
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT /*+ NO_UNNEST */ (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
  AND (SELECT /*+ NO_UNNEST */ B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'OUTSTANDING'
UNION ALL
SELECT /*+ LEADING(BRR_TRANSACTIONS BS_ACCTS BA_CPME)
           USE_HASH(BS_ACCTS BA_CPME)
           NO_MERGE */ DISTINCT
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT /*+ NO_UNNEST */ (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
  AND (SELECT /*+ NO_UNNEST */ B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND (SELECT /*+ NO_UNNEST */ MAX(E.TRANSACTION_DATE)
       FROM BRR_TRANSACTIONS E
       WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
         AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'RECONCILED'
);


-- ============================================================
-- ETAPE 3/5 : IDs dans ORIGINAL mais PAS dans OPTIMISE
-- ============================================================
PROMPT
PROMPT [3/5] IDs dans ORIGINAL mais PAS dans OPTIMISE...
PROMPT (Si aucune ligne = OK)

SELECT 'ORIGINAL_ONLY' AS SOURCE, ID_ECRITURE FROM (
    -- ORIGINAL
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
           FROM BS_ACCTS BS_ACCTS2
           WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                      FROM BRR_ACCOUNT_HIERARCHIES H
                                      WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM
           FROM BS_ACCTS B
           WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                              FROM BRR_ACCOUNT_HIERARCHIES H
                              WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE)
                FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                  AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
    MINUS
    -- OPTIMISE
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
           FROM BS_ACCTS BS_ACCTS2
           WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                      FROM BRR_ACCOUNT_HIERARCHIES H
                                      WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM
           FROM BS_ACCTS B
           WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                              FROM BRR_ACCOUNT_HIERARCHIES H
                              WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE)
                FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                  AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 50;


-- ============================================================
-- ETAPE 4/5 : IDs dans OPTIMISE mais PAS dans ORIGINAL
-- ============================================================
PROMPT
PROMPT [4/5] IDs dans OPTIMISE mais PAS dans ORIGINAL...
PROMPT (Si aucune ligne = OK)

SELECT 'OPTIMISE_ONLY' AS SOURCE, ID_ECRITURE FROM (
    -- OPTIMISE
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
           FROM BS_ACCTS BS_ACCTS2
           WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                      FROM BRR_ACCOUNT_HIERARCHIES H
                                      WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM
           FROM BS_ACCTS B
           WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                              FROM BRR_ACCOUNT_HIERARCHIES H
                              WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE)
                FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                  AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
    MINUS
    -- ORIGINAL
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
           FROM BS_ACCTS BS_ACCTS2
           WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                      FROM BRR_ACCOUNT_HIERARCHIES H
                                      WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (SELECT B.ACCT_NUM
           FROM BS_ACCTS B
           WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                              FROM BRR_ACCOUNT_HIERARCHIES H
                              WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE)
                FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                  AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 50;


-- ============================================================
-- ETAPE 5/5 : RESUME
-- ============================================================
PROMPT
PROMPT [5/5] RESUME VERIFICATION DTC670
PROMPT ============================================================
PROMPT
PROMPT Resultats attendus :
PROMPT   - Etape 1 et 2 : MEME nombre de lignes
PROMPT   - Etape 3 : AUCUNE ligne (ORIGINAL_ONLY)
PROMPT   - Etape 4 : AUCUNE ligne (OPTIMISE_ONLY)
PROMPT
PROMPT Si ces conditions sont remplies :
PROMPT   => AUCUNE REGRESSION
PROMPT   => Deploiement DTC670_4v9ag77cam8uu_OPTIMISE.sql AUTORISE
PROMPT
PROMPT ============================================================
PROMPT FIN VERIFICATION DTC670
PROMPT ============================================================

SET TIMING OFF
