-- ============================================================================
-- VÉRIFICATION TA_RN_GESTION_ACCURATE - Comptes 394 vs 342
-- ============================================================================
-- Date: 07/02/2026
-- Objectif: Vérifier si les comptes 394 et 342 sont dans TA_RN_GESTION_ACCURATE
-- ============================================================================

SET LINESIZE 300
SET PAGESIZE 100

PROMPT ============================================================================
PROMPT 1. LES COMPTES 394 ET 342 SONT-ILS DANS TA_RN_GESTION_ACCURATE ?
PROMPT ============================================================================

SELECT
    '394 (22.36)' AS COMPTE,
    GA.ID_COMPTE_BANCAIRE_SYSTEME,
    GA.ID_COMPTE_ACCURATE,
    CBS.NUMERO AS NUM_COMPTE_BANCAIRE_SYSTEME,
    CBS.RIBBANKCODE||CBS.RIBBRANCHCODE||CBS.RIBIDENTIFICATION||CBS.RIBCHECKDIGIT AS RIB,
    CBS.GENERATIONCONTREPARTIE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
    JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE GA.ID_COMPTE_ACCURATE = 394

UNION ALL

SELECT
    '342 (2817)' AS COMPTE,
    GA.ID_COMPTE_BANCAIRE_SYSTEME,
    GA.ID_COMPTE_ACCURATE,
    CBS.NUMERO AS NUM_COMPTE_BANCAIRE_SYSTEME,
    CBS.RIBBANKCODE||CBS.RIBBRANCHCODE||CBS.RIBIDENTIFICATION||CBS.RIBCHECKDIGIT AS RIB,
    CBS.GENERATIONCONTREPARTIE,
    CA.NUM_COMPTE_ACCURATE,
    CA.TYPE_RAPPRO
FROM TA_RN_GESTION_ACCURATE GA
    JOIN TA_RN_COMPTE_ACCURATE CA ON CA.ID_COMPTE_ACCURATE = GA.ID_COMPTE_ACCURATE
    JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
WHERE GA.ID_COMPTE_ACCURATE = 342

ORDER BY 1;

PROMPT
PROMPT Si aucune ligne → Compte NON paramétré dans TA_RN_GESTION_ACCURATE ❌
PROMPT

PROMPT ============================================================================
PROMPT 2. VÉRIFICATION DES EXCLUSIONS - Sociétés
PROMPT ============================================================================

WITH trans_22 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '22.36' AND ROWNUM = 1
),
trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
),
cbs_394 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 394 AND ROWNUM = 1
),
cbs_342 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342 AND ROWNUM = 1
)
SELECT
    '22.36' AS TRANSACTION,
    T22.IDENTIFICATION AS CODE_SOCIETE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN ES.ID_SOCIETE IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS SOCIETE_EXCLUE
FROM trans_22 T22
    CROSS JOIN cbs_394 CBS
    LEFT JOIN TA_RN_SOCIETE S ON S.CODE = T22.IDENTIFICATION
    LEFT JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_SOCIETE = S.ID_SOCIETE
        AND ES.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    '2817' AS TRANSACTION,
    T2817.IDENTIFICATION AS CODE_SOCIETE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN ES.ID_SOCIETE IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS SOCIETE_EXCLUE
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_SOCIETE S ON S.CODE = T2817.IDENTIFICATION
    LEFT JOIN TA_RN_EXCLUSION_SOCIETE ES ON ES.ID_SOCIETE = S.ID_SOCIETE
        AND ES.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME;

PROMPT
PROMPT ============================================================================
PROMPT 3. VÉRIFICATION DES EXCLUSIONS - Devises
PROMPT ============================================================================

WITH trans_22 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '22.36' AND ROWNUM = 1
),
trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
),
cbs_394 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 394 AND ROWNUM = 1
),
cbs_342 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342 AND ROWNUM = 1
)
SELECT
    '22.36' AS TRANSACTION,
    T22.OPERATIONNETAMOUNTCURRENCY AS DEVISE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN ED.ID_DEVISE IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS DEVISE_EXCLUE
FROM trans_22 T22
    CROSS JOIN cbs_394 CBS
    LEFT JOIN TA_RN_DEVISE D ON D.CODE_ISO_DEVISE = T22.OPERATIONNETAMOUNTCURRENCY
    LEFT JOIN TA_RN_EXCLUSION_DEVISE ED ON ED.ID_DEVISE = D.ID_DEVISE
        AND ED.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    '2817' AS TRANSACTION,
    T2817.OPERATIONNETAMOUNTCURRENCY AS DEVISE,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN ED.ID_DEVISE IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS DEVISE_EXCLUE
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_DEVISE D ON D.CODE_ISO_DEVISE = T2817.OPERATIONNETAMOUNTCURRENCY
    LEFT JOIN TA_RN_EXCLUSION_DEVISE ED ON ED.ID_DEVISE = D.ID_DEVISE
        AND ED.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME;

PROMPT
PROMPT ============================================================================
PROMPT 4. VÉRIFICATION DES EXCLUSIONS - Modes de Règlement
PROMPT ============================================================================

WITH trans_22 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '22.36' AND ROWNUM = 1
),
trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
),
cbs_394 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 394 AND ROWNUM = 1
),
cbs_342 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342 AND ROWNUM = 1
)
SELECT
    '22.36' AS TRANSACTION,
    T22.SETTLEMENTMODE AS MODE_REGLEMENT,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN EMR.ID_MODE_REGLEMENT IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS MODE_REGLEMENT_EXCLU
FROM trans_22 T22
    CROSS JOIN cbs_394 CBS
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.CODE_MODE_REGLEMENT = T22.SETTLEMENTMODE
    LEFT JOIN TA_RN_EXCLUSION_MR EMR ON EMR.ID_MODE_REGLEMENT = MR.ID_MODE_REGLEMENT
        AND EMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    '2817' AS TRANSACTION,
    T2817.SETTLEMENTMODE AS MODE_REGLEMENT,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN EMR.ID_MODE_REGLEMENT IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS MODE_REGLEMENT_EXCLU
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_MODE_REGLEMENT MR ON MR.CODE_MODE_REGLEMENT = T2817.SETTLEMENTMODE
    LEFT JOIN TA_RN_EXCLUSION_MR EMR ON EMR.ID_MODE_REGLEMENT = MR.ID_MODE_REGLEMENT
        AND EMR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME;

PROMPT
PROMPT ============================================================================
PROMPT 5. VÉRIFICATION DES EXCLUSIONS - Types de Règlement
PROMPT ============================================================================

WITH trans_22 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '22.36' AND ROWNUM = 1
),
trans_2817 AS (
    SELECT * FROM TA_RN_IMPORT_GESTION WHERE OPERATIONNETAMOUNT = '2817' AND ROWNUM = 1
),
cbs_394 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 394 AND ROWNUM = 1
),
cbs_342 AS (
    SELECT CBS.ID_COMPTE_BANCAIRE_SYSTEME
    FROM TA_RN_GESTION_ACCURATE GA
        JOIN TA_RN_COMPTE_BANCAIRE_SYSTEME CBS ON CBS.ID_COMPTE_BANCAIRE_SYSTEME = GA.ID_COMPTE_BANCAIRE_SYSTEME
    WHERE GA.ID_COMPTE_ACCURATE = 342 AND ROWNUM = 1
)
SELECT
    '22.36' AS TRANSACTION,
    T22.TYPEREGLEMENT AS TYPE_REGLEMENT,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN ETR.ID_COMPTE_BANCAIRE_SYSTEME IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS TYPE_REGLEMENT_EXCLU
FROM trans_22 T22
    CROSS JOIN cbs_394 CBS
    LEFT JOIN TA_RN_EXCLUSION_TR ETR ON ETR.TYPE_REGLEMENT = T22.TYPEREGLEMENT
        AND ETR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME

UNION ALL

SELECT
    '2817' AS TRANSACTION,
    T2817.TYPEREGLEMENT AS TYPE_REGLEMENT,
    CBS.ID_COMPTE_BANCAIRE_SYSTEME,
    CASE WHEN ETR.ID_COMPTE_BANCAIRE_SYSTEME IS NOT NULL THEN 'OUI ❌ EXCLU' ELSE 'NON ✅' END AS TYPE_REGLEMENT_EXCLU
FROM trans_2817 T2817
    CROSS JOIN cbs_342 CBS
    LEFT JOIN TA_RN_EXCLUSION_TR ETR ON ETR.TYPE_REGLEMENT = T2817.TYPEREGLEMENT
        AND ETR.ID_COMPTE_BANCAIRE_SYSTEME = CBS.ID_COMPTE_BANCAIRE_SYSTEME;

PROMPT
PROMPT ============================================================================
PROMPT 6. RÉSUMÉ - Compte 394 vs 342
PROMPT ============================================================================

SELECT
    'Compte 394 dans TA_RN_GESTION_ACCURATE ?' AS VERIFICATION,
    CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END AS RESULTAT
FROM TA_RN_GESTION_ACCURATE
WHERE ID_COMPTE_ACCURATE = 394

UNION ALL

SELECT
    'Compte 342 dans TA_RN_GESTION_ACCURATE ?' AS VERIFICATION,
    CASE WHEN COUNT(*) > 0 THEN 'OUI ✅' ELSE 'NON ❌' END AS RESULTAT
FROM TA_RN_GESTION_ACCURATE
WHERE ID_COMPTE_ACCURATE = 342;

PROMPT
PROMPT ============================================================================
PROMPT FIN VÉRIFICATION
PROMPT ============================================================================
