-- ============================================================
-- VERIFICATION : Curseur Package vs Requete Optimisee
-- Objectif : S'assurer que les 2 requetes retournent EXACTEMENT
--            les memes donnees
-- Date : 20/02/2026
-- Parametres : s_DateArrete = '28/02/2026', s_TypeRapro = 'RB'
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200
SET PAGESIZE 1000
SET TIMING ON

PROMPT ============================================================
PROMPT VERIFICATION PACKAGE vs REQUETE OPTIMISEE
PROMPT Parametres : DATE_ARRETE = 28/02/2026, TYPE_RAPRO = RB
PROMPT ============================================================

-- ============================================================
-- PARTIE 1 : REQUETE EXACTE DU PACKAGE (Curseur_Attendus_DC_Max)
-- Source : PKG_RNADEXTAUTO01 lignes 471-629
-- Variables remplacees par valeurs hardcodees
-- ============================================================

PROMPT
PROMPT [1/5] Comptage requete PACKAGE (Curseur_Attendus_DC_Max)...

SELECT 'PACKAGE' AS SOURCE, COUNT(*) AS NB_LIGNES FROM (
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    (select TO_CHAR('28/02/2026') from dual) as DATE_ARRETE,
    (select decode(rpad(acct_num,length(acct_num)-2), 'RB', 'Rapprochement Bancaire',
                                                    'RC', 'Rapprochement de Contrôle',
                                                    'JC', 'Justification de compte',
                                                    'CL', 'Compte de liaison')
        from BS_ACCTS BS_ACCTS2 where BS_ACCTS2.ACCT_ID = (select H.level_03_account_id
                                                            From BRR_ACCOUNT_HIERARCHIES H
                                                            where H.account_id = BS_ACCTS.ACCT_ID)) as TYPE_RAPRO,
    (select B.ACCT_NUM from BS_ACCTS B where B.ACCT_ID = (select H.level_02_account_id
                                                from BRR_ACCOUNT_HIERARCHIES H
                                                where H.account_id = BS_ACCTS.ACCT_ID)) as SERVICE,
    (select acct_name from BS_ACCTS ACCTS2 where ACCTS2.acct_id = BS_ACCTS.acct_group) as SOCIETE,
    BA_CPME.compte_bancaire as COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME as LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY as DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') as DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE as LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) as DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) as CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'), 'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')) as SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE,'STATEMENT', 'B','CASHBOOK', 'C') as COTE_SUSPENS,
    (select TO_DATE('28/02/2026', 'DD/MM/RRRR') - TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') from dual) as ANCIENNETE_J,
    (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) as ANCIENNETE_M,
    (select libelle_anciennete from BA_CATEG_ANCIENNETE BACA
     where (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) >= BACA.borne_inf
     and   (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) < BACA.borne_sup) as BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)
                                      ,'RECEIPTCASHBOOK', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)) as PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)
                                       ,'PAYMENTCASHBOOK', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)) as PILIER_MONTANT_CREDIT,
    BA_CPME.methode as METHODE_PROVISION,
    (select taux from BA_METHODE_PROVISION MEPR
         where methode = (select methode from BA_COMPTE_METHODE CPME where CPME.ACCOUNT_ID = BS_ACCTS.acct_id)
         and (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) >= MEPR.borne_inf
         and (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) < MEPR.borne_sup) as TAUX,
    0 as MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE as STATUT,
    null as DATE_APUREMENT,
    null as DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1,5) as PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT as COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO as NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT), null, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT), DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) as DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') as SENS_DELTA,
    '' as NUMERO_FICHE,
    '' as DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID as ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED WHEN TO_DATE('01/01/1980','DD/MM/RRRR') THEN NULL
         ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR') END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS, BS_ACCTS BS_ACCTS, BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
AND (select (rpad(acct_num,length(acct_num)-2))
     from BS_ACCTS BS_ACCTS2 where BS_ACCTS2.ACCT_ID = (select H.level_03_account_id
                                                        From BRR_ACCOUNT_HIERARCHIES H
                                                        where H.account_id = BS_ACCTS.ACCT_ID)) = 'RB'
AND (select B.ACCT_NUM from BS_ACCTS B where B.ACCT_ID = (select H.level_02_account_id
                                                          from BRR_ACCOUNT_HIERARCHIES H
                                                           where H.account_id = BS_ACCTS.ACCT_ID)) = 'GESTION'
AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
AND (BRR_TRANSACTIONS.STATE='OUTSTANDING')
UNION
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    (select TO_CHAR('28/02/2026') from dual) as DATE_ARRETE,
    (select decode(rpad(acct_num,length(acct_num)-2), 'RB', 'Rapprochement Bancaire',
                                                    'RC', 'Rapprochement de Contrôle',
                                                    'JC', 'Justification de compte',
                                                    'CL', 'Compte de liaison')
        from BS_ACCTS BS_ACCTS2 where BS_ACCTS2.ACCT_ID = (select H.level_03_account_id
                                                            From BRR_ACCOUNT_HIERARCHIES H
                                                            where H.account_id = BS_ACCTS.ACCT_ID)) as TYPE_RAPRO,
    (select B.ACCT_NUM from BS_ACCTS B where B.ACCT_ID = (select H.level_02_account_id
                                                             from BRR_ACCOUNT_HIERARCHIES H
                                                           where H.account_id = BS_ACCTS.ACCT_ID)) as SERVICE,
    (select acct_name from BS_ACCTS ACCTS2 where ACCTS2.acct_id = BS_ACCTS.acct_group) as SOCIETE,
    BA_CPME.compte_bancaire as COMPTE_BANCAIRE,
    BS_ACCTS.ACCT_NAME as LIBELLE_COMPTE,
    BS_ACCTS.ACCT_CURRENCY as DEVISE,
    TO_CHAR(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') as DATE_OPERATION_SUSPENS,
    BRR_TRANSACTIONS.NARRATIVE as LIBELLE_SUSPENS,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) as DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT) as CREDIT,
    DECODE(BRR_TRANSACTIONS.NUMERIC_TWO, 0, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','ABD','PAYMENTSTATEMENT','ACC','RECEIPTCASHBOOK','ABC','RECEIPTSTATEMENT','ACD'), 'A'||BRR_TRANSACTIONS.FLAG_C||DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D')) as SENS_ATTENDU,
    DECODE(BRR_TRANSACTIONS.SIDE,'STATEMENT', 'B','CASHBOOK', 'C') as COTE_SUSPENS,
    (select TO_DATE('28/02/2026', 'DD/MM/RRRR') - TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR') from dual) as ANCIENNETE_J,
    (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) as ANCIENNETE_M,
    (select libelle_anciennete from BA_CATEG_ANCIENNETE BACA
     where (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) >= BACA.borne_inf
     and   (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) < BACA.borne_sup) as BORNE_ANCIENNETE,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)
                                       ,'RECEIPTCASHBOOK', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)) as PILIER_MONTANT_DEBIT,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)
                                       ,'PAYMENTCASHBOOK', (select libelle_pilier from BA_PILIERS_MONTANTS PIMO where BRR_TRANSACTIONS.AMOUNT >= PIMO.borne_inf and BRR_TRANSACTIONS.AMOUNT < PIMO.borne_sup)) as PILIER_MONTANT_CREDIT,
    BA_CPME.methode as METHODE_PROVISION,
    (select taux from BA_METHODE_PROVISION MEPR
         where methode = (select methode from BA_COMPTE_METHODE CPME where CPME.ACCOUNT_ID = BS_ACCTS.acct_id)
         and (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) >= MEPR.borne_inf
         and (select months_between(TO_DATE('28/02/2026', 'DD/MM/RRRR'), TO_DATE(BRR_TRANSACTIONS.TRANSACTION_DATE, 'DD/MM/RRRR')) from dual) < MEPR.borne_sup) as TAUX,
    0 as MONTANT_PROVISION,
    BRR_TRANSACTIONS.STATE as STATUT,
    TO_DATE(BRR_TRANSACTIONS.UPDATE_TIME, 'DD/MM/RRRR') as DATE_APUREMENT,
    (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E
                                    WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                                    AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) as DC_MAX,
    SUBSTR(BRR_TRANSACTIONS.CHARACTER_SIXTEEN, 1,5) as PRIORITE,
    BRR_TRANSACTIONS.LAST_NOTE_TEXT as COMMENTAIRE,
    BRR_TRANSACTIONS.NUMERIC_TWO as NETTING,
    DECODE(DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT), null, DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'RECEIPTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'PAYMENTCASHBOOK', BRR_TRANSACTIONS.AMOUNT), DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTSTATEMENT',BRR_TRANSACTIONS.AMOUNT,'RECEIPTCASHBOOK', BRR_TRANSACTIONS.AMOUNT)) as DELTA,
    DECODE(BRR_TRANSACTIONS.PAYMENT_OR_RECEIPT||BRR_TRANSACTIONS.SIDE,'PAYMENTCASHBOOK','D','PAYMENTSTATEMENT','C','RECEIPTCASHBOOK','C','RECEIPTSTATEMENT','D') as SENS_DELTA,
    '' as NUMERO_FICHE,
    '' as DERNIER_STATUT,
    BRR_TRANSACTIONS.RECORD_ID as ID_ECRITURE,
    CASE BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED WHEN TO_DATE('01/01/1980','DD/MM/RRRR') THEN NULL
         ELSE TO_CHAR(BRR_TRANSACTIONS.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR') END AS ANNOTE_LE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS, BS_ACCTS BS_ACCTS, BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
AND (select (rpad(acct_num,length(acct_num)-2))
     from BS_ACCTS BS_ACCTS2 where BS_ACCTS2.ACCT_ID = (select H.level_03_account_id
                                                        From BRR_ACCOUNT_HIERARCHIES H
                                                        where H.account_id = BS_ACCTS.ACCT_ID)) = 'RB'
AND (select B.ACCT_NUM from BS_ACCTS B where B.ACCT_ID = (select H.level_02_account_id
                                                          from BRR_ACCOUNT_HIERARCHIES H
                                                           where H.account_id = BS_ACCTS.ACCT_ID)) = 'GESTION'
AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E
                                    WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                                    AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR')
AND (BRR_TRANSACTIONS.STATE='RECONCILED')
);


-- ============================================================
-- PARTIE 2 : REQUETE OPTIMISEE
-- ============================================================

PROMPT
PROMPT [2/5] Comptage requete OPTIMISEE...

SELECT 'OPTIMISE' AS SOURCE, COUNT(*) AS NB_LIGNES FROM (
WITH
params AS (
    SELECT TO_DATE('28/02/2026', 'DD/MM/RRRR') AS date_arrete FROM DUAL
),
compte_hierarchie AS (
    SELECT
        H.ACCOUNT_ID,
        H.LEVEL_02_ACCOUNT_ID,
        H.LEVEL_03_ACCOUNT_ID,
        B2.ACCT_NUM AS SERVICE,
        B3.ACCT_NUM AS TYPE_CODE,
        RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE,
        DECODE(RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2),
            'RB', 'Rapprochement Bancaire',
            'RC', 'Rapprochement de Controle',
            'JC', 'Justification de compte',
            'CL', 'Compte de liaison') AS TYPE_RAPRO
    FROM BRR_ACCOUNT_HIERARCHIES H
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
),
transactions_base AS (
    SELECT /*+ USE_HASH(T A H) */
        T.RECORD_ID,
        T.ACCOUNT_ID,
        T.TRANSACTION_DATE,
        T.NARRATIVE,
        T.AMOUNT,
        T.PAYMENT_OR_RECEIPT,
        T.SIDE,
        T.NUMERIC_TWO,
        T.FLAG_C,
        T.STATE,
        T.UPDATE_TIME,
        T.RECONCILIATION_REFERENCE,
        T.CHARACTER_SIXTEEN,
        T.LAST_NOTE_TEXT,
        T.DATE_LAST_NOTE_ADDED,
        T.PAYMENT_OR_RECEIPT || T.SIDE AS PAY_SIDE,
        P.date_arrete,
        P.date_arrete - T.TRANSACTION_DATE AS ANCIENNETE_J,
        MONTHS_BETWEEN(P.date_arrete, T.TRANSACTION_DATE) AS ANCIENNETE_M
    FROM BRR_TRANSACTIONS T
    CROSS JOIN params P
    WHERE T.TRANSACTION_DATE <= P.date_arrete
      AND T.STATE IN ('OUTSTANDING', 'RECONCILED')
),
dc_max_calc AS (
    SELECT
        RECONCILIATION_REFERENCE,
        ACCOUNT_ID,
        MAX(TRANSACTION_DATE) AS DC_MAX
    FROM BRR_TRANSACTIONS
    WHERE STATE = 'RECONCILED'
    GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
),
donnees_completes AS (
    SELECT
        '28/02/2026' AS DATE_ARRETE,
        CH.TYPE_RAPRO,
        CH.SERVICE,
        (SELECT ACCT_NAME FROM BS_ACCTS WHERE ACCT_ID = A.ACCT_GROUP) AS SOCIETE,
        CM.COMPTE_BANCAIRE,
        A.ACCT_NAME AS LIBELLE_COMPTE,
        A.ACCT_CURRENCY AS DEVISE,
        TO_CHAR(T.TRANSACTION_DATE, 'DD/MM/RRRR') AS DATE_OPERATION_SUSPENS,
        T.NARRATIVE AS LIBELLE_SUSPENS,
        DECODE(T.PAY_SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT) AS DEBIT,
        DECODE(T.PAY_SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT) AS CREDIT,
        DECODE(T.NUMERIC_TWO, 0,
            DECODE(T.PAY_SIDE, 'PAYMENTCASHBOOK', 'ABD', 'PAYMENTSTATEMENT', 'ACC', 'RECEIPTCASHBOOK', 'ABC', 'RECEIPTSTATEMENT', 'ACD'),
            'A' || T.FLAG_C || DECODE(T.PAY_SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D')
        ) AS SENS_ATTENDU,
        DECODE(T.SIDE, 'STATEMENT', 'B', 'CASHBOOK', 'C') AS COTE_SUSPENS,
        T.ANCIENNETE_J,
        T.ANCIENNETE_M,
        BACA.LIBELLE_ANCIENNETE AS BORNE_ANCIENNETE,
        CASE WHEN T.PAY_SIDE IN ('PAYMENTSTATEMENT', 'RECEIPTCASHBOOK') THEN PIMO.LIBELLE_PILIER END AS PILIER_MONTANT_DEBIT,
        CASE WHEN T.PAY_SIDE IN ('RECEIPTSTATEMENT', 'PAYMENTCASHBOOK') THEN PIMO.LIBELLE_PILIER END AS PILIER_MONTANT_CREDIT,
        CM.METHODE AS METHODE_PROVISION,
        MEPR.TAUX,
        0 AS MONTANT_PROVISION,
        T.STATE AS STATUT,
        CASE WHEN T.STATE = 'RECONCILED' THEN TO_DATE(T.UPDATE_TIME, 'DD/MM/RRRR') END AS DATE_APUREMENT,
        CASE WHEN T.STATE = 'RECONCILED' THEN DCM.DC_MAX END AS DC_MAX,
        SUBSTR(T.CHARACTER_SIXTEEN, 1, 5) AS PRIORITE,
        T.LAST_NOTE_TEXT AS COMMENTAIRE,
        T.NUMERIC_TWO AS NETTING,
        COALESCE(
            DECODE(T.PAY_SIDE, 'PAYMENTSTATEMENT', T.AMOUNT, 'RECEIPTCASHBOOK', T.AMOUNT),
            DECODE(T.PAY_SIDE, 'RECEIPTSTATEMENT', T.AMOUNT, 'PAYMENTCASHBOOK', T.AMOUNT)
        ) AS DELTA,
        DECODE(T.PAY_SIDE, 'PAYMENTCASHBOOK', 'D', 'PAYMENTSTATEMENT', 'C', 'RECEIPTCASHBOOK', 'C', 'RECEIPTSTATEMENT', 'D') AS SENS_DELTA,
        '' AS NUMERO_FICHE,
        '' AS DERNIER_STATUT,
        T.RECORD_ID AS ID_ECRITURE,
        CASE T.DATE_LAST_NOTE_ADDED
            WHEN TO_DATE('01/01/1980', 'DD/MM/RRRR') THEN NULL
            ELSE TO_CHAR(T.DATE_LAST_NOTE_ADDED, 'DD/MM/RRRR')
        END AS ANNOTE_LE,
        T.date_arrete AS P_DATE_ARRETE
    FROM transactions_base T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN BA_CATEG_ANCIENNETE BACA
        ON T.ANCIENNETE_M >= BACA.BORNE_INF
        AND T.ANCIENNETE_M < BACA.BORNE_SUP
    LEFT JOIN BA_PILIERS_MONTANTS PIMO
        ON T.AMOUNT >= PIMO.BORNE_INF
        AND T.AMOUNT < PIMO.BORNE_SUP
    LEFT JOIN BA_METHODE_PROVISION MEPR
        ON MEPR.METHODE = CM.METHODE
        AND T.ANCIENNETE_M >= MEPR.BORNE_INF
        AND T.ANCIENNETE_M < MEPR.BORNE_SUP
    LEFT JOIN dc_max_calc DCM
        ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
        AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
        AND T.STATE = 'RECONCILED'
)
SELECT DISTINCT
    DATE_ARRETE, TYPE_RAPRO, SERVICE, SOCIETE, COMPTE_BANCAIRE, LIBELLE_COMPTE, DEVISE,
    DATE_OPERATION_SUSPENS, LIBELLE_SUSPENS, DEBIT, CREDIT, SENS_ATTENDU, COTE_SUSPENS,
    ANCIENNETE_J, ANCIENNETE_M, BORNE_ANCIENNETE, PILIER_MONTANT_DEBIT, PILIER_MONTANT_CREDIT,
    METHODE_PROVISION, TAUX, MONTANT_PROVISION, STATUT, DATE_APUREMENT, DC_MAX,
    PRIORITE, COMMENTAIRE, NETTING, DELTA, SENS_DELTA, NUMERO_FICHE, DERNIER_STATUT,
    ID_ECRITURE, ANNOTE_LE
FROM donnees_completes
WHERE (STATUT = 'OUTSTANDING')
   OR (STATUT = 'RECONCILED' AND DC_MAX >= P_DATE_ARRETE)
);


-- ============================================================
-- PARTIE 3 : COMPARAISON PAR ID_ECRITURE (RECORD_ID)
-- ============================================================

PROMPT
PROMPT [3/5] IDs dans PACKAGE mais PAS dans OPTIMISE...

SELECT 'PKG_ONLY' AS SOURCE, ID_ECRITURE FROM (
    -- IDs du package
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS, BS_ACCTS, BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (select rpad(acct_num,length(acct_num)-2) from BS_ACCTS BS_ACCTS2
           where BS_ACCTS2.ACCT_ID = (select H.level_03_account_id from BRR_ACCOUNT_HIERARCHIES H
           where H.account_id = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (select B.ACCT_NUM from BS_ACCTS B where B.ACCT_ID = (select H.level_02_account_id
           from BRR_ACCOUNT_HIERARCHIES H where H.account_id = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
    MINUS
    -- IDs optimise
    SELECT DISTINCT T.RECORD_ID
    FROM BRR_TRANSACTIONS T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN BRR_ACCOUNT_HIERARCHIES H ON H.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN (
        SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
        FROM BRR_TRANSACTIONS WHERE STATE = 'RECONCILED'
        GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
    ) DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE AND DCM.ACCOUNT_ID = T.ACCOUNT_ID AND T.STATE = 'RECONCILED'
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
      AND T.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND T.STATE IN ('OUTSTANDING', 'RECONCILED')
      AND ((T.STATE = 'OUTSTANDING') OR (T.STATE = 'RECONCILED' AND DCM.DC_MAX >= TO_DATE('28/02/2026', 'DD/MM/RRRR')))
)
WHERE ROWNUM <= 50;


PROMPT
PROMPT [4/5] IDs dans OPTIMISE mais PAS dans PACKAGE...

SELECT 'OPT_ONLY' AS SOURCE, ID_ECRITURE FROM (
    -- IDs optimise
    SELECT DISTINCT T.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN BRR_ACCOUNT_HIERARCHIES H ON H.ACCOUNT_ID = T.ACCOUNT_ID
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN (
        SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
        FROM BRR_TRANSACTIONS WHERE STATE = 'RECONCILED'
        GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
    ) DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE AND DCM.ACCOUNT_ID = T.ACCOUNT_ID AND T.STATE = 'RECONCILED'
    WHERE B2.ACCT_NUM = 'GESTION'
      AND RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) = 'RB'
      AND T.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND T.STATE IN ('OUTSTANDING', 'RECONCILED')
      AND ((T.STATE = 'OUTSTANDING') OR (T.STATE = 'RECONCILED' AND DCM.DC_MAX >= TO_DATE('28/02/2026', 'DD/MM/RRRR')))
    MINUS
    -- IDs package
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID
    FROM BRR_TRANSACTIONS, BS_ACCTS, BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (select rpad(acct_num,length(acct_num)-2) from BS_ACCTS BS_ACCTS2
           where BS_ACCTS2.ACCT_ID = (select H.level_03_account_id from BRR_ACCOUNT_HIERARCHIES H
           where H.account_id = BS_ACCTS.ACCT_ID)) = 'RB'
      AND (select B.ACCT_NUM from BS_ACCTS B where B.ACCT_ID = (select H.level_02_account_id
           from BRR_ACCOUNT_HIERARCHIES H where H.account_id = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('28/02/2026', 'DD/MM/RRRR')
      AND (
          (BRR_TRANSACTIONS.STATE = 'OUTSTANDING')
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE) FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('28/02/2026', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 50;


-- ============================================================
-- PARTIE 5 : RESUME
-- ============================================================

PROMPT
PROMPT [5/5] RESUME VERIFICATION
PROMPT ============================================================
PROMPT
PROMPT Si les etapes 3 et 4 ne retournent AUCUNE ligne :
PROMPT   => REQUETE PACKAGE et OPTIMISEE sont IDENTIQUES
PROMPT   => L'optimisation peut etre deployee en toute securite
PROMPT
PROMPT Si des lignes apparaissent :
PROMPT   => DIFFERENCE DETECTEE - Analyser les ID_ECRITURE
PROMPT
PROMPT ============================================================
PROMPT FIN VERIFICATION
PROMPT ============================================================

SET TIMING OFF
