-- ============================================================
-- VERIFICATION : DTC670 Original vs Optimise COMPLET (CTE)
-- SQL_ID : 4v9ag77cam8uu
-- Date : 20/02/2026
-- ============================================================
-- Compare PKG_RNADEXTAUTO01_ORIGINAL vs PKG_RNADEXTAUTO01_DEPLOY_FULL_OPTIM
-- ============================================================

SET SERVEROUTPUT ON SIZE UNLIMITED
SET LINESIZE 200
SET PAGESIZE 1000
SET TIMING ON

-- Parametres (a modifier selon vos besoins)
DEFINE P_DATE_ARRETE = '28/02/2026'
DEFINE P_TYPE_RAPRO = 'RB'

PROMPT ============================================================
PROMPT VERIFICATION DTC670 - OPTIMISATION COMPLETE (CTE)
PROMPT Original vs Full Optimise
PROMPT Date arrete : &P_DATE_ARRETE
PROMPT Type rapro  : &P_TYPE_RAPRO
PROMPT ============================================================
PROMPT

-- ============================================================
-- ETAPE 1/5 : COMPTAGE REQUETE ORIGINALE
-- ============================================================
PROMPT [1/5] Comptage ORIGINAL...

SELECT 'ORIGINAL' AS VERSION, COUNT(*) AS NB_LIGNES FROM (
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = '&P_TYPE_RAPRO'
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'OUTSTANDING'
UNION
SELECT /*+ optimizer_features_enable('10.2.0.4') */ DISTINCT
    BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
     BS_ACCTS BS_ACCTS,
     BA_COMPTE_METHODE BA_CPME
WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
  AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
  AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
       FROM BS_ACCTS BS_ACCTS2
       WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                  FROM BRR_ACCOUNT_HIERARCHIES H
                                  WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = '&P_TYPE_RAPRO'
  AND (SELECT B.ACCT_NUM
       FROM BS_ACCTS B
       WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                          FROM BRR_ACCOUNT_HIERARCHIES H
                          WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
  AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND (SELECT MAX(E.TRANSACTION_DATE)
       FROM BRR_TRANSACTIONS E
       WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
         AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND BRR_TRANSACTIONS.STATE = 'RECONCILED'
);


-- ============================================================
-- ETAPE 2/5 : COMPTAGE REQUETE OPTIMISEE COMPLETE (CTE)
-- ============================================================
PROMPT
PROMPT [2/5] Comptage OPTIMISE COMPLET (CTE)...

SELECT 'OPTIMISE_CTE' AS VERSION, COUNT(*) AS NB_LIGNES FROM (
WITH
-- CTE 1 : Pre-calcul DC_MAX
dc_max_calc AS (
    SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
    FROM BRR_TRANSACTIONS
    WHERE RECONCILIATION_REFERENCE IS NOT NULL
    GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
),
-- CTE 2 : Hierarchie des comptes
compte_hierarchie AS (
    SELECT H.ACCOUNT_ID,
           B2.ACCT_NUM AS SERVICE,
           RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE
    FROM BRR_ACCOUNT_HIERARCHIES H
    JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
    JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
)
-- OUTSTANDING
SELECT DISTINCT T.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS T
JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
WHERE CH.TYPE_RAPRO_CODE = '&P_TYPE_RAPRO'
  AND CH.SERVICE = 'GESTION'
  AND T.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND T.STATE = 'OUTSTANDING'
UNION ALL
-- RECONCILED avec DC_MAX
SELECT DISTINCT T.RECORD_ID AS ID_ECRITURE
FROM BRR_TRANSACTIONS T
JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
JOIN dc_max_calc DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
                     AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
WHERE CH.TYPE_RAPRO_CODE = '&P_TYPE_RAPRO'
  AND CH.SERVICE = 'GESTION'
  AND T.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
  AND T.STATE = 'RECONCILED'
  AND DCM.DC_MAX >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
);


-- ============================================================
-- ETAPE 3/5 : IDs dans ORIGINAL mais PAS dans OPTIMISE CTE
-- ============================================================
PROMPT
PROMPT [3/5] IDs dans ORIGINAL mais PAS dans OPTIMISE CTE...
PROMPT (Si aucune ligne = OK)

SELECT 'ORIGINAL_ONLY' AS SOURCE, ID_ECRITURE FROM (
    -- ORIGINAL
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
           FROM BS_ACCTS BS_ACCTS2
           WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                      FROM BRR_ACCOUNT_HIERARCHIES H
                                      WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = '&P_TYPE_RAPRO'
      AND (SELECT B.ACCT_NUM
           FROM BS_ACCTS B
           WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                              FROM BRR_ACCOUNT_HIERARCHIES H
                              WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
      AND (
          BRR_TRANSACTIONS.STATE = 'OUTSTANDING'
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE)
                FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                  AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'))
      )
    MINUS
    -- OPTIMISE CTE
    WITH
    dc_max_calc AS (
        SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
        FROM BRR_TRANSACTIONS
        WHERE RECONCILIATION_REFERENCE IS NOT NULL
        GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
    ),
    compte_hierarchie AS (
        SELECT H.ACCOUNT_ID, B2.ACCT_NUM AS SERVICE,
               RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE
        FROM BRR_ACCOUNT_HIERARCHIES H
        JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
        JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    )
    SELECT DISTINCT T.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN dc_max_calc DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
                              AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
    WHERE CH.TYPE_RAPRO_CODE = '&P_TYPE_RAPRO'
      AND CH.SERVICE = 'GESTION'
      AND T.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
      AND (
          T.STATE = 'OUTSTANDING'
          OR
          (T.STATE = 'RECONCILED' AND DCM.DC_MAX >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 50;


-- ============================================================
-- ETAPE 4/5 : IDs dans OPTIMISE CTE mais PAS dans ORIGINAL
-- ============================================================
PROMPT
PROMPT [4/5] IDs dans OPTIMISE CTE mais PAS dans ORIGINAL...
PROMPT (Si aucune ligne = OK)

SELECT 'OPTIMISE_ONLY' AS SOURCE, ID_ECRITURE FROM (
    -- OPTIMISE CTE
    WITH
    dc_max_calc AS (
        SELECT RECONCILIATION_REFERENCE, ACCOUNT_ID, MAX(TRANSACTION_DATE) AS DC_MAX
        FROM BRR_TRANSACTIONS
        WHERE RECONCILIATION_REFERENCE IS NOT NULL
        GROUP BY RECONCILIATION_REFERENCE, ACCOUNT_ID
    ),
    compte_hierarchie AS (
        SELECT H.ACCOUNT_ID, B2.ACCT_NUM AS SERVICE,
               RPAD(B3.ACCT_NUM, LENGTH(B3.ACCT_NUM)-2) AS TYPE_RAPRO_CODE
        FROM BRR_ACCOUNT_HIERARCHIES H
        JOIN BS_ACCTS B2 ON B2.ACCT_ID = H.LEVEL_02_ACCOUNT_ID
        JOIN BS_ACCTS B3 ON B3.ACCT_ID = H.LEVEL_03_ACCOUNT_ID
    )
    SELECT DISTINCT T.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS T
    JOIN BS_ACCTS A ON A.ACCT_ID = T.ACCOUNT_ID
    JOIN BA_COMPTE_METHODE CM ON CM.ACCOUNT_ID = A.ACCT_ID
    JOIN compte_hierarchie CH ON CH.ACCOUNT_ID = A.ACCT_ID
    LEFT JOIN dc_max_calc DCM ON DCM.RECONCILIATION_REFERENCE = T.RECONCILIATION_REFERENCE
                              AND DCM.ACCOUNT_ID = T.ACCOUNT_ID
    WHERE CH.TYPE_RAPRO_CODE = '&P_TYPE_RAPRO'
      AND CH.SERVICE = 'GESTION'
      AND T.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
      AND (
          T.STATE = 'OUTSTANDING'
          OR
          (T.STATE = 'RECONCILED' AND DCM.DC_MAX >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'))
      )
    MINUS
    -- ORIGINAL
    SELECT DISTINCT BRR_TRANSACTIONS.RECORD_ID AS ID_ECRITURE
    FROM BRR_TRANSACTIONS BRR_TRANSACTIONS,
         BS_ACCTS BS_ACCTS,
         BA_COMPTE_METHODE BA_CPME
    WHERE BS_ACCTS.ACCT_ID = BRR_TRANSACTIONS.ACCOUNT_ID
      AND BA_CPME.ACCOUNT_ID = BS_ACCTS.ACCT_ID
      AND (SELECT (RPAD(ACCT_NUM, LENGTH(ACCT_NUM)-2))
           FROM BS_ACCTS BS_ACCTS2
           WHERE BS_ACCTS2.ACCT_ID = (SELECT H.LEVEL_03_ACCOUNT_ID
                                      FROM BRR_ACCOUNT_HIERARCHIES H
                                      WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = '&P_TYPE_RAPRO'
      AND (SELECT B.ACCT_NUM
           FROM BS_ACCTS B
           WHERE B.ACCT_ID = (SELECT H.LEVEL_02_ACCOUNT_ID
                              FROM BRR_ACCOUNT_HIERARCHIES H
                              WHERE H.ACCOUNT_ID = BS_ACCTS.ACCT_ID)) = 'GESTION'
      AND BRR_TRANSACTIONS.TRANSACTION_DATE <= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR')
      AND (
          BRR_TRANSACTIONS.STATE = 'OUTSTANDING'
          OR
          (BRR_TRANSACTIONS.STATE = 'RECONCILED'
           AND (SELECT MAX(E.TRANSACTION_DATE)
                FROM BRR_TRANSACTIONS E
                WHERE E.RECONCILIATION_REFERENCE = BRR_TRANSACTIONS.RECONCILIATION_REFERENCE
                  AND E.ACCOUNT_ID = BRR_TRANSACTIONS.ACCOUNT_ID) >= TO_DATE('&P_DATE_ARRETE', 'DD/MM/RRRR'))
      )
)
WHERE ROWNUM <= 50;


-- ============================================================
-- ETAPE 5/5 : RESUME
-- ============================================================
PROMPT
PROMPT [5/5] RESUME VERIFICATION DTC670 - OPTIMISATION COMPLETE
PROMPT ============================================================
PROMPT
PROMPT Resultats attendus :
PROMPT   - Etape 1 et 2 : MEME nombre de lignes
PROMPT   - Etape 3 : AUCUNE ligne (ORIGINAL_ONLY)
PROMPT   - Etape 4 : AUCUNE ligne (OPTIMISE_ONLY)
PROMPT
PROMPT Si ces conditions sont remplies :
PROMPT   => AUCUNE REGRESSION
PROMPT   => Deploiement PKG_RNADEXTAUTO01_DEPLOY_FULL_OPTIM.sql AUTORISE
PROMPT
PROMPT ============================================================
PROMPT FIN VERIFICATION DTC670 - OPTIMISATION COMPLETE
PROMPT ============================================================

SET TIMING OFF
