-- ============================================================================
-- REQUETE SOURCE : Consultation Compte ACCURATE
-- Description : Requête de base pour consulter les informations d'un compte
--
-- CHAMPS MODIFIABLES :
--   - GCC.NUM_COMPTE_COMPTABLE
--   - RCA.FLAG_ACTIF
--   - RS.CODE (peut être une liste séparée par virgule)
--
-- PARAMETRE WHERE :
--   - RCA.NUM_COMPTE_ACCURATE (ex: 'BBNP42304-EUR')
-- ============================================================================

SELECT DISTINCT
    G3.ACCT_NUM||'-'||G2.ACCT_NUM||'-'||G1.ACCT_NUM AS GROUPEG,
    RCA.FLAG_ACTIF,
    RCA.NUM_COMPTE_ACCURATE,
    LISTAGG(DISTINCT RS.CODE, ',') AS Lst_CodeSociete,
    LISTAGG(DISTINCT RCC.Num_Compte_COMPTABLE, ',') AS lst_Cpt_COMPTABLE,
    BCI.SOCIETE,
    BCI.LIBELLE_COMPTE_COMPTABLE,
    RCA.NOM AS NomCompteACCURATE,
    RCA.type_rappro,
    BCM.METHODE,
    BCM.COMPTE_BANCAIRE,
    GCC.NUM_COMPTE_COMPTABLE AS NumCompteComptable,
    BANQUE,
    REPLACE(REPLACE(BCI.RIB,'/',''),' ','') AS RIB,
    BCI.RIB AS RIB_ACCURATE,
    RPB.ID_COMPTE_BANCAIRE,
    RPB.FLAG_ACTIF AS Banque_ACTIF,
    RCB.NOM AS NomCompteBancaire,
    RGA.id_compte_bancaire_systeme,
    RCBS.RIB AS RCBS_RIB,
    RCBS.TIERS,
    RCBS.GENERATIONCONTREPARTIE,
    LISTAGG(DISTINCT ANM.account_number, ',') AS Lst_SousCompte,
    RD.ID_DEVISE,
    RD.CODE_ISO_DEVISE,
    BCI.ACCOUNT_ID,
    LISTAGG(DISTINCT RCA.ID_COMPTE_ACCURATE, ',') AS lst_ID_Cpt_ACCURATE,
    RCB.BRANCHCODE,
    RCB.BANKCODE,
    RCB.IDENTIFICATION
FROM EXP_RNAPA.TA_RN_COMPTE_ACCURATE RCA
    LEFT JOIN BANKREC.bs_account_number_map ANM ON (RCA.NUM_COMPTE_ACCURATE||'-CB' = ANM.account_number OR RCA.NUM_COMPTE_ACCURATE||'-ST' = ANM.account_number)
    LEFT JOIN EXP_RNAPA.TA_RN_BC_INFOS BCI ON RCA.NUM_COMPTE_ACCURATE = BCI.compte_comptable
    LEFT JOIN EXP_RNAPA.TA_RN_COMPTA_ACCURATE CtaA ON CtaA.ID_COMPTE_ACCURATE = RCA.ID_COMPTE_ACCURATE
    LEFT JOIN EXP_RNAPA.TA_RN_PERIMETRE_COMPTA RPC ON RPC.ID_PERIMETRE_COMPTA = CtaA.ID_PERIMETRE_COMPTA
    LEFT JOIN EXP_RNAPA.TA_RN_BANQUE_ACCURATE RBA ON RBA.ID_COMPTE_ACCURATE = RCA.ID_COMPTE_ACCURATE
    LEFT JOIN EXP_RNAPA.TA_RN_PERIMETRE_BANQUE RPB ON RPB.ID_PERIMETRE_BANQUE = RBA.ID_PERIMETRE_BANQUE
    LEFT JOIN EXP_RNAPA.TA_RN_COMPTE_BANCAIRE RCB ON RCB.ID_COMPTE_BANCAIRE = RPB.ID_COMPTE_BANCAIRE
    LEFT JOIN EXP_RNAPA.TA_RN_COMPTE_COMPTABLE RCC ON RCC.ID_COMPTE_COMPTABLE = RPC.id_compte_comptable
    LEFT JOIN EXP_RNAPA.TA_RN_GESTION_ACCURATE RGA ON RGA.id_compte_accurate = RCA.ID_COMPTE_ACCURATE
    LEFT JOIN EXP_RNAPA.TA_RN_COMPTE_BANCAIRE_SYSTEME RCBS ON RCBS.id_compte_bancaire_systeme = RGA.id_compte_bancaire_systeme
    LEFT JOIN EXP_RNAPA.TA_RN_SOCIETE RS ON RPC.ID_SOCIETE = RS.ID_SOCIETE
    LEFT JOIN EXP_RNAPA.TA_RN_DEVISE RD ON RPC.ID_DEVISE = RD.ID_DEVISE
    LEFT JOIN EXP_RNAPA.BA_COMPTE_METHODE BCM ON RCA.NUM_COMPTE_ACCURATE = BCM.COMPTE_COMPTABLE
    LEFT JOIN EXP_RNAPA.TA_RN_GEST_COMPTE_COMPTABLE GCC ON GCC.COMPTE_BANCAIRE = BCM.COMPTE_BANCAIRE
    LEFT JOIN BANKREC.BRR_ACCOUNTS A ON BCI.ACCOUNT_ID = A.Account_ID
    LEFT JOIN BS_ACCTS G1 ON G1.ACCT_ID = A.ACCOUNT_GROUP
    LEFT JOIN BS_ACCTS G2 ON G2.ACCT_ID = G1.ACCT_GROUP
    LEFT JOIN BS_ACCTS G3 ON G3.ACCT_ID = G2.ACCT_GROUP
    LEFT JOIN BS_ACCTS G4 ON G4.ACCT_ID = G3.ACCT_GROUP
WHERE 1 = 1
    AND RCA.NUM_COMPTE_ACCURATE = 'BBNP42304-EUR'
    AND RCA.FLAG_ACTIF = 'O'
GROUP BY
    (G3.ACCT_NUM||'-'||G2.ACCT_NUM||'-'||G1.ACCT_NUM),
    BCI.ACCOUNT_ID,
    BCI.SOCIETE,
    RCA.NUM_COMPTE_ACCURATE,
    BCI.LIBELLE_COMPTE_COMPTABLE,
    BCM.METHODE,
    BCM.COMPTE_BANCAIRE,
    GCC.NUM_COMPTE_COMPTABLE,
    RD.ID_DEVISE,
    RD.CODE_ISO_DEVISE,
    BANQUE,
    REPLACE(REPLACE(BCI.RIB,'/',''),' ',''),
    BCI.RIB,
    RCB.BRANCHCODE,
    RCB.BANKCODE,
    RCB.IDENTIFICATION,
    RCA.NOM,
    RCA.FLAG_ACTIF,
    RCA.type_rappro,
    RPB.ID_COMPTE_BANCAIRE,
    RPB.FLAG_ACTIF,
    RCB.NOM,
    RGA.id_compte_bancaire_systeme,
    RCBS.RIB,
    RCBS.TIERS,
    RCBS.GENERATIONCONTREPARTIE
ORDER BY FLAG_ACTIF DESC, GROUPEG DESC, RCA.NUM_COMPTE_ACCURATE;


-- ============================================================================
-- DIFFERENCES ENTRE REQUETE SOURCE ET FONCTION FN_CONSULT_COMPTE_ACCURATE
-- ============================================================================
--
-- 1. LISTAGG :
--    - SOURCE  : LISTAGG(DISTINCT RS.CODE, ',') sans WITHIN GROUP ni OVER
--    - FONCTION: LISTAGG(DISTINCT RS.CODE, ',') WITHIN GROUP (ORDER BY RS.CODE) OVER (PARTITION BY ...)
--    => La fonction utilise la syntaxe analytique pour éviter les erreurs avec DISTINCT + GROUP BY
--
-- 2. ORDER BY :
--    - SOURCE  : ORDER BY FLAG_ACTIF DESC, GROUPEG DESC, RCA.NUM_COMPTE_ACCURATE
--    - FONCTION: Pas de ORDER BY (peut être ajouté dans le SELECT appelant)
--
-- 3. Alias colonnes :
--    - SOURCE  : RCBS.RIB (sans alias explicite)
--    - FONCTION: RCBS.RIB AS RCBS_RIB (alias explicite pour éviter conflit avec BCI.RIB)
--
-- 4. WHERE :
--    - SOURCE  : Valeurs en dur ('BBNP42304-EUR', 'O')
--    - FONCTION: Paramètres dynamiques avec filtres optionnels
--
-- ============================================================================
